# Generated by Django 5.2 on 2025-06-30 02:54

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del tipo de préstamo', max_length=100, unique=True, verbose_name='Nombre del tipo')),
                ('codigo', models.CharField(help_text='Código único del tipo de préstamo', max_length=20, unique=True, verbose_name='Código')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del tipo de préstamo', null=True, verbose_name='Descripción')),
                ('tasa_interes_defecto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tasa de interés anual por defecto', max_digits=5, verbose_name='Tasa de interés por defecto (%)')),
                ('plazo_maximo_meses', models.PositiveIntegerField(default=12, help_text='Plazo máximo permitido en meses', verbose_name='Plazo máximo (meses)')),
                ('monto_maximo', models.DecimalField(blank=True, decimal_places=2, help_text='Monto máximo permitido para este tipo', max_digits=12, null=True, verbose_name='Monto máximo')),
                ('requiere_garantia', models.BooleanField(default=False, help_text='Si este tipo de préstamo requiere garantía', verbose_name='Requiere garantía')),
                ('requiere_aprobacion', models.BooleanField(default=True, help_text='Si requiere aprobación de un superior', verbose_name='Requiere aprobación')),
                ('activo', models.BooleanField(default=True, help_text='Si está activo, estará disponible para nuevos préstamos', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Tipo de Préstamo',
                'verbose_name_plural': 'Tipos de Préstamo',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_prestamo', models.CharField(help_text='Número único del préstamo', max_length=20, unique=True, verbose_name='Número de préstamo')),
                ('monto_solicitado', models.DecimalField(decimal_places=2, help_text='Monto solicitado por el empleado', max_digits=12, verbose_name='Monto solicitado')),
                ('monto_aprobado', models.DecimalField(blank=True, decimal_places=2, help_text='Monto aprobado (puede ser diferente al solicitado)', max_digits=12, null=True, verbose_name='Monto aprobado')),
                ('tasa_interes', models.DecimalField(decimal_places=2, help_text='Tasa de interés anual aplicada', max_digits=5, verbose_name='Tasa de interés (%)')),
                ('plazo_meses', models.PositiveIntegerField(help_text='Plazo del préstamo en meses', verbose_name='Plazo (meses)')),
                ('cuota_mensual', models.DecimalField(blank=True, decimal_places=2, help_text='Cuota mensual calculada', max_digits=12, null=True, verbose_name='Cuota mensual')),
                ('fecha_solicitud', models.DateField(default=datetime.date.today, verbose_name='Fecha de solicitud')),
                ('fecha_aprobacion', models.DateField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('fecha_desembolso', models.DateField(blank=True, null=True, verbose_name='Fecha de desembolso')),
                ('fecha_primer_pago', models.DateField(blank=True, help_text='Fecha programada para el primer pago', null=True, verbose_name='Fecha primer pago')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de aprobación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('desembolsado', 'Desembolsado'), ('activo', 'Activo (en pago)'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('en_mora', 'En mora')], default='pendiente', help_text='Estado actual del préstamo', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre el préstamo', null=True, verbose_name='Observaciones')),
                ('garantia_descripcion', models.TextField(blank=True, help_text='Descripción de la garantía ofrecida', null=True, verbose_name='Descripción de garantía')),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saldo pendiente por pagar', max_digits=12, verbose_name='Saldo pendiente')),
                ('total_pagado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total pagado hasta la fecha', max_digits=12, verbose_name='Total pagado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_aprobados', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='payroll.empleado', verbose_name='Empleado')),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_solicitados', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
                ('tipo_prestamo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='prestamos.tipoprestamo', verbose_name='Tipo de préstamo')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_solicitud', '-numero_prestamo'],
            },
        ),
        migrations.CreateModel(
            name='PagoPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pago', models.PositiveIntegerField(help_text='Número consecutivo del pago', verbose_name='Número de pago')),
                ('monto_pago', models.DecimalField(decimal_places=2, help_text='Monto pagado', max_digits=12, verbose_name='Monto del pago')),
                ('monto_capital', models.DecimalField(decimal_places=2, help_text='Parte del pago que va a capital', max_digits=12, verbose_name='Monto a capital')),
                ('monto_interes', models.DecimalField(decimal_places=2, help_text='Parte del pago que va a interés', max_digits=12, verbose_name='Monto a interés')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de pago')),
                ('fecha_programada', models.DateField(help_text='Fecha en que estaba programado el pago', verbose_name='Fecha programada')),
                ('tipo_pago', models.CharField(choices=[('nomina', 'Descuento de nómina'), ('efectivo', 'Pago en efectivo'), ('transferencia', 'Transferencia bancaria'), ('cheque', 'Cheque'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de pago')),
                ('referencia', models.CharField(blank=True, help_text='Referencia del pago (número de cheque, transferencia, etc.)', max_length=100, null=True, verbose_name='Referencia')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('nomina_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descuentos_prestamos', to='payroll.nomina', verbose_name='Nómina relacionada')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_prestamos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='prestamos.prestamo', verbose_name='Préstamo')),
            ],
            options={
                'verbose_name': 'Pago de Préstamo',
                'verbose_name_plural': 'Pagos de Préstamo',
                'ordering': ['prestamo', 'numero_pago'],
                'indexes': [models.Index(fields=['prestamo', 'fecha_pago'], name='prestamos_p_prestam_9fd7c1_idx'), models.Index(fields=['fecha_pago'], name='prestamos_p_fecha_p_032060_idx')],
                'unique_together': {('prestamo', 'numero_pago')},
            },
        ),
        migrations.AddIndex(
            model_name='prestamo',
            index=models.Index(fields=['empleado', 'estado'], name='prestamos_p_emplead_e2ad3b_idx'),
        ),
        migrations.AddIndex(
            model_name='prestamo',
            index=models.Index(fields=['numero_prestamo'], name='prestamos_p_numero__9b4dbf_idx'),
        ),
        migrations.AddIndex(
            model_name='prestamo',
            index=models.Index(fields=['estado'], name='prestamos_p_estado_ca1dfe_idx'),
        ),
    ]
