# Generated by Django 5.2 on 2025-08-22 01:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCantidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único de la unidad (ej: m2, m3, ml)', max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Código')),
                ('descripcion', models.CharField(help_text='Descripción completa de la unidad de medida', max_length=100, verbose_name='Descripción')),
                ('simbolo', models.CharField(blank=True, help_text='Símbolo de la unidad (ej: m², m³)', max_length=10, null=True, verbose_name='Símbolo')),
                ('activo', models.BooleanField(default=True, help_text='Si está activo, estará disponible para asignar', verbose_name='Activo')),
                ('es_sistema', models.BooleanField(default=False, help_text='Las unidades del sistema no se pueden eliminar', verbose_name='Es del sistema')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización', verbose_name='Orden')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('organization', models.ForeignKey(blank=True, help_text='Organización a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organizacion')),
            ],
            options={
                'verbose_name': 'Tipo de Cantidad',
                'verbose_name_plural': 'Tipos de Cantidad',
                'ordering': ['orden', 'codigo'],
                'indexes': [models.Index(fields=['activo'], name='tipos_canti_activo_55cf7c_idx'), models.Index(fields=['codigo'], name='tipos_canti_codigo_7a42f5_idx')],
            },
        ),
    ]
