# Generated by Django 4.2.7 on 2026-02-25 01:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_seed_plans_and_convert_fk"),
        ("tipos_cantidad", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tipocantidad",
            name="codigo",
            field=models.CharField(
                help_text="Código único de la unidad (ej: m2, m3, ml)",
                max_length=10,
                validators=[django.core.validators.MinLengthValidator(1)],
                verbose_name="Código",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tipocantidad",
            unique_together={("organization", "codigo")},
        ),
    ]
