# Generated by Django 5.2 on 2025-06-30 02:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, help_text='Foto de perfil del usuario', null=True, upload_to='perfiles/fotos/', verbose_name='Foto de perfil')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('N', 'Prefiero no decir')], max_length=1, null=True, verbose_name='Género')),
                ('estado_civil', models.CharField(blank=True, choices=[('soltero', 'Soltero/a'), ('casado', 'Casado/a'), ('union_libre', 'Unión libre'), ('divorciado', 'Divorciado/a'), ('viudo', 'Viudo/a')], max_length=20, null=True, verbose_name='Estado civil')),
                ('nacionalidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nacionalidad')),
                ('telefono', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener entre 9 y 15 dígitos.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('telefono_emergencia', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener entre 9 y 15 dígitos.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono de emergencia')),
                ('contacto_emergencia', models.CharField(blank=True, help_text='Nombre del contacto de emergencia', max_length=200, null=True, verbose_name='Contacto de emergencia')),
                ('direccion_residencia', models.TextField(blank=True, null=True, verbose_name='Dirección de residencia')),
                ('ciudad_residencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad de residencia')),
                ('codigo_postal', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código postal')),
                ('tipo_sangre', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True, verbose_name='Tipo de sangre')),
                ('alergias', models.TextField(blank=True, help_text='Alergias conocidas', null=True, verbose_name='Alergias')),
                ('medicamentos', models.TextField(blank=True, help_text='Medicamentos que toma regularmente', null=True, verbose_name='Medicamentos')),
                ('nivel_educacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nivel de educación')),
                ('profesion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Profesión')),
                ('habilidades', models.TextField(blank=True, help_text='Habilidades profesionales principales', null=True, verbose_name='Habilidades')),
                ('banco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco')),
                ('numero_cuenta', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de cuenta')),
                ('tipo_cuenta', models.CharField(blank=True, choices=[('ahorros', 'Ahorros'), ('corriente', 'Corriente')], max_length=20, null=True, verbose_name='Tipo de cuenta')),
                ('tema_preferido', models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro'), ('auto', 'Automático')], default='auto', max_length=20, verbose_name='Tema preferido')),
                ('idioma_preferido', models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', max_length=10, verbose_name='Idioma preferido')),
                ('recibir_notificaciones', models.BooleanField(default=True, help_text='Recibir notificaciones por email', verbose_name='Recibir notificaciones')),
                ('acepta_biometria', models.BooleanField(default=False, help_text='Acepta usar datos biométricos para autenticación', verbose_name='Acepta biometría')),
                ('perfil_completado', models.BooleanField(default=False, help_text='Si el perfil tiene la información mínima completa', verbose_name='Perfil completado')),
                ('privacidad_publica', models.BooleanField(default=False, help_text='Si algunos datos pueden ser visibles a otros usuarios', verbose_name='Información pública')),
                ('ultima_actualizacion_perfil', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'ordering': ['usuario__first_name', 'usuario__last_name'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionNotificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_prestamos', models.BooleanField(default=True, help_text='Recibir notificaciones sobre préstamos', verbose_name='Notificaciones de préstamos')),
                ('notif_nomina', models.BooleanField(default=True, help_text='Recibir notificaciones sobre nómina', verbose_name='Notificaciones de nómina')),
                ('notif_documentos', models.BooleanField(default=True, help_text='Recibir notificaciones sobre documentos', verbose_name='Notificaciones de documentos')),
                ('notif_sistema', models.BooleanField(default=True, help_text='Recibir notificaciones importantes del sistema', verbose_name='Notificaciones del sistema')),
                ('via_email', models.BooleanField(default=True, help_text='Recibir notificaciones por correo electrónico', verbose_name='Vía email')),
                ('via_sms', models.BooleanField(default=False, help_text='Recibir notificaciones por SMS', verbose_name='Vía SMS')),
                ('via_plataforma', models.BooleanField(default=True, help_text='Mostrar notificaciones en la plataforma', verbose_name='En la plataforma')),
                ('horario_inicio', models.TimeField(default='08:00', help_text='Hora desde la cual recibir notificaciones', verbose_name='Hora inicio notificaciones')),
                ('horario_fin', models.TimeField(default='18:00', help_text='Hora hasta la cual recibir notificaciones', verbose_name='Hora fin notificaciones')),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_notificaciones', to='perfil.perfil', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Configuración de Notificaciones',
                'verbose_name_plural': 'Configuraciones de Notificaciones',
            },
        ),
    ]
