# Generated by Django 4.2.7 on 2026-02-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roles", "0001_initial"),
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="roles",
            field=models.ManyToManyField(
                blank=True,
                related_name="usuarios",
                through="roles.AsignacionRol",
                to="roles.rol",
                verbose_name="Roles",
            ),
        ),
    ]
