# Generated by Django 5.2.5 on 2026-02-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0002_customuser_roles"),
        ("roles", "0002_add_permisos_to_rol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="roles",
            field=models.ManyToManyField(
                blank=True,
                related_name="usuarios",
                through="roles.AsignacionRol",
                through_fields=("usuario", "rol"),
                to="roles.rol",
                verbose_name="Roles",
            ),
        ),
    ]
