# Generated by Django 4.2.7 on 2026-02-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("perfil", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracionnotificaciones",
            name="notif_contabilidad",
            field=models.BooleanField(
                default=True,
                help_text="Recibir notificaciones sobre contabilidad",
                verbose_name="Notificaciones de contabilidad",
            ),
        ),
        migrations.AddField(
            model_name="configuracionnotificaciones",
            name="notif_contratos",
            field=models.BooleanField(
                default=True,
                help_text="Recibir notificaciones sobre contratos",
                verbose_name="Notificaciones de contratos",
            ),
        ),
        migrations.AddField(
            model_name="configuracionnotificaciones",
            name="notif_empleados",
            field=models.BooleanField(
                default=True,
                help_text="Recibir notificaciones sobre empleados",
                verbose_name="Notificaciones de empleados",
            ),
        ),
        migrations.AddField(
            model_name="configuracionnotificaciones",
            name="notif_proyectos",
            field=models.BooleanField(
                default=True,
                help_text="Recibir notificaciones sobre proyectos",
                verbose_name="Notificaciones de proyectos",
            ),
        ),
        migrations.AddField(
            model_name="configuracionnotificaciones",
            name="notif_seguridad",
            field=models.BooleanField(
                default=True,
                help_text="Recibir alertas de seguridad",
                verbose_name="Notificaciones de seguridad",
            ),
        ),
        migrations.AddField(
            model_name="configuracionnotificaciones",
            name="sonido_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Activar sonido al recibir notificaciones",
                verbose_name="Sonido de notificaciones",
            ),
        ),
    ]
