# Generated by Django 4.2.7 on 2026-01-01 19:01

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("perfil", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="perfil",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
