# Generated by Django 4.2.7 on 2026-01-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("perfil", "0002_alter_perfil_managers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="configuracionnotificaciones",
            options={
                "ordering": ["-id"],
                "verbose_name": "Configuración de Notificaciones",
                "verbose_name_plural": "Configuraciones de Notificaciones",
            },
        ),
        migrations.AddField(
            model_name="perfil",
            name="departamento_expedicion_cedula",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Departamento de expedición de cédula",
            ),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="lugar_expedicion_cedula",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Lugar de expedición de cédula (Municipio)",
            ),
        ),
    ]
