# Generated by Django 5.2.5 on 2026-03-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("perfil", "0002_add_notification_preference_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="mostrar_modal_proyecto",
            field=models.BooleanField(
                default=True,
                help_text="Si se debe mostrar el selector de proyecto al iniciar sesión",
                verbose_name="Mostrar modal de proyecto al iniciar",
            ),
        ),
    ]
