# Generated by Django 5.2.5 on 2026-03-03 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("perfil", "0003_add_mostrar_modal_proyecto"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="proyecto_fijo",
            field=models.UUIDField(
                blank=True,
                help_text="UUID del proyecto que se selecciona automáticamente al iniciar sesión",
                null=True,
                verbose_name="Proyecto fijo",
            ),
        ),
    ]
