# Generated by Django 4.2.7 on 2026-03-13 02:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_add_rbac_rol_to_invitacion"),
        ("perfil", "0004_add_proyecto_fijo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="numero_cedula",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El número de cédula debe contener entre 8 y 12 dígitos.",
                        regex="^\\d{8,12}$",
                    )
                ],
                verbose_name="Número de cédula",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="perfil",
            unique_together={("organization", "numero_cedula")},
        ),
    ]
