# Generated by Django 5.2 on 2025-07-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.RenameField(
            model_name='notificacion',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('error', 'Error'), ('success', 'Éxito')], default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='titulo',
            field=models.CharField(default='Notificación', max_length=255),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='mensaje',
            field=models.TextField(),
        ),
    ]
