# Generated by Django 5.2.5 on 2026-02-27 03:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0011_remove_notificacion_core_notifi_fecha_fa2c60_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        verbose_name="Fecha de modificación",
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("mercadopago", "MercadoPago"),
                            ("manual", "Manual"),
                        ],
                        max_length=20,
                        verbose_name="Pasarela",
                    ),
                ),
                (
                    "gateway_payment_method_id",
                    models.CharField(
                        help_text="Token del método de pago en Stripe/MP (pm_xxx)",
                        max_length=255,
                        verbose_name="ID en pasarela",
                    ),
                ),
                (
                    "card_brand",
                    models.CharField(
                        choices=[
                            ("visa", "Visa"),
                            ("mastercard", "Mastercard"),
                            ("amex", "American Express"),
                            ("diners", "Diners Club"),
                            ("other", "Otra"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Marca de tarjeta",
                    ),
                ),
                (
                    "card_last4",
                    models.CharField(max_length=4, verbose_name="Últimos 4 dígitos"),
                ),
                (
                    "card_exp_month",
                    models.PositiveSmallIntegerField(verbose_name="Mes de expiración"),
                ),
                (
                    "card_exp_year",
                    models.PositiveSmallIntegerField(verbose_name="Año de expiración"),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="Método por defecto"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to="core.organizacion",
                        verbose_name="Organización",
                    ),
                ),
            ],
            options={
                "verbose_name": "Método de pago",
                "verbose_name_plural": "Métodos de pago",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        verbose_name="Fecha de modificación",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trialing", "En periodo de prueba"),
                            ("active", "Activa"),
                            ("past_due", "Pago pendiente"),
                            ("canceled", "Cancelada"),
                            ("suspended", "Suspendida"),
                            ("expired", "Expirada"),
                        ],
                        db_index=True,
                        default="trialing",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Mensual"), ("yearly", "Anual")],
                        default="monthly",
                        max_length=10,
                        verbose_name="Ciclo de facturación",
                    ),
                ),
                (
                    "trial_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Inicio del trial"
                    ),
                ),
                (
                    "trial_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fin del trial"
                    ),
                ),
                (
                    "current_period_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Inicio del periodo actual"
                    ),
                ),
                (
                    "current_period_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fin del periodo actual"
                    ),
                ),
                (
                    "canceled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Cancelada el"
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("mercadopago", "MercadoPago"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="Pasarela de pago",
                    ),
                ),
                (
                    "gateway_subscription_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="ID suscripción en gateway",
                    ),
                ),
                (
                    "gateway_customer_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="ID cliente en gateway",
                    ),
                ),
                (
                    "cancel_reason",
                    models.TextField(
                        blank=True, default="", verbose_name="Motivo de cancelación"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadatos"
                    ),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="core.organizacion",
                        verbose_name="Organización",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="core.plan",
                        verbose_name="Plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suscripción",
                "verbose_name_plural": "Suscripciones",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        verbose_name="Fecha de modificación",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="Formato: INV-YYYY-NNNNNN",
                        max_length=30,
                        unique=True,
                        verbose_name="Número de factura",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("pending", "Pendiente"),
                            ("paid", "Pagada"),
                            ("failed", "Fallida"),
                            ("voided", "Anulada"),
                            ("refunded", "Reembolsada"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Subtotal"
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=19.0,
                        help_text="IVA Colombia: 19%",
                        max_digits=5,
                        verbose_name="Tasa de impuesto (%)",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Valor del impuesto",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="COP", max_length=3, verbose_name="Moneda"
                    ),
                ),
                (
                    "billing_period_start",
                    models.DateTimeField(verbose_name="Inicio del periodo"),
                ),
                (
                    "billing_period_end",
                    models.DateTimeField(verbose_name="Fin del periodo"),
                ),
                ("due_date", models.DateField(verbose_name="Fecha de vencimiento")),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Pagada el"
                    ),
                ),
                (
                    "gateway_invoice_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="ID factura en gateway",
                    ),
                ),
                (
                    "gateway_payment_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="ID pago en gateway",
                    ),
                ),
                (
                    "pdf_url",
                    models.URLField(blank=True, default="", verbose_name="URL del PDF"),
                ),
                (
                    "billing_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Razón social",
                    ),
                ),
                (
                    "billing_nit",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="NIT"
                    ),
                ),
                (
                    "billing_address",
                    models.TextField(
                        blank=True, default="", verbose_name="Dirección de facturación"
                    ),
                ),
                (
                    "billing_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="Email de facturación",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="core.organizacion",
                        verbose_name="Organización",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="billing.subscription",
                        verbose_name="Suscripción",
                    ),
                ),
            ],
            options={
                "verbose_name": "Factura",
                "verbose_name_plural": "Facturas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        verbose_name="Fecha de modificación",
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("users", "Usuarios"),
                            ("storage_mb", "Almacenamiento (MB)"),
                            ("empleados", "Empleados"),
                            ("nominas_mes", "Nóminas por mes"),
                            ("prestamos", "Préstamos activos"),
                        ],
                        max_length=30,
                        verbose_name="Métrica",
                    ),
                ),
                (
                    "current_value",
                    models.IntegerField(default=0, verbose_name="Valor actual"),
                ),
                ("limit_value", models.IntegerField(default=0, verbose_name="Límite")),
                (
                    "recorded_at",
                    models.DateTimeField(auto_now=True, verbose_name="Registrado el"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="core.organizacion",
                        verbose_name="Organización",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de uso",
                "verbose_name_plural": "Registros de uso",
                "ordering": ["organization", "metric"],
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        verbose_name="Fecha de modificación",
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        help_text="ID único del evento del gateway (evt_xxx)",
                        max_length=255,
                        unique=True,
                        verbose_name="ID del evento",
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("mercadopago", "MercadoPago"),
                            ("manual", "Manual"),
                        ],
                        max_length=20,
                        verbose_name="Pasarela",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="Ej: payment_intent.succeeded",
                        max_length=100,
                        verbose_name="Tipo de evento",
                    ),
                ),
                ("payload", models.JSONField(default=dict, verbose_name="Payload")),
                (
                    "processed",
                    models.BooleanField(default=False, verbose_name="Procesado"),
                ),
                (
                    "error",
                    models.TextField(blank=True, default="", verbose_name="Error"),
                ),
            ],
            options={
                "verbose_name": "Evento webhook",
                "verbose_name_plural": "Eventos webhook",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_id"], name="billing_web_event_i_0dccbf_idx"
                    ),
                    models.Index(
                        fields=["event_type"], name="billing_web_event_t_2f4669_idx"
                    ),
                    models.Index(
                        fields=["processed"], name="billing_web_process_775ecd_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        verbose_name="Fecha de modificación",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="COP", max_length=3, verbose_name="Moneda"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("processing", "Procesando"),
                            ("succeeded", "Exitoso"),
                            ("failed", "Fallido"),
                            ("refunded", "Reembolsado"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("mercadopago", "MercadoPago"),
                            ("manual", "Manual"),
                        ],
                        max_length=20,
                        verbose_name="Pasarela",
                    ),
                ),
                (
                    "gateway_payment_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="ID pago en gateway",
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(
                        blank=True, default="", verbose_name="Motivo de fallo"
                    ),
                ),
                (
                    "idempotency_key",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Evita cobros duplicados",
                        unique=True,
                        verbose_name="Clave de idempotencia",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadatos"
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="billing.invoice",
                        verbose_name="Factura",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="billing.paymentmethod",
                        verbose_name="Método de pago",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="billing_pay_status_b7739e_idx"
                    ),
                    models.Index(
                        fields=["idempotency_key"],
                        name="billing_pay_idempot_96c174_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PlanFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        verbose_name="Fecha de modificación",
                    ),
                ),
                (
                    "feature_code",
                    models.CharField(
                        help_text="Identificador único del feature (ej: nomina_electronica)",
                        max_length=50,
                        verbose_name="Código de feature",
                    ),
                ),
                (
                    "feature_name",
                    models.CharField(
                        help_text="Nombre legible del feature",
                        max_length=100,
                        verbose_name="Nombre del feature",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(default=True, verbose_name="Habilitado"),
                ),
                (
                    "limit_value",
                    models.IntegerField(
                        blank=True,
                        help_text="Límite numérico (null = ilimitado si enabled)",
                        null=True,
                        verbose_name="Límite",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_features",
                        to="core.plan",
                        verbose_name="Plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature de plan",
                "verbose_name_plural": "Features de plan",
                "ordering": ["plan", "feature_code"],
                "unique_together": {("plan", "feature_code")},
            },
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["status"], name="billing_sub_status_948046_idx"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["trial_end"], name="billing_sub_trial_e_03420b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["current_period_end"], name="billing_sub_current_c59a21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["status"], name="billing_inv_status_541249_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["number"], name="billing_inv_number_dc410a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="usagerecord",
            unique_together={("organization", "metric")},
        ),
    ]
