# Generated by Django 5.2.5 on 2026-02-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0002_seed_plan_features"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="gateway",
            field=models.CharField(
                choices=[
                    ("stripe", "Stripe"),
                    ("wompi", "Wompi"),
                    ("mercadopago", "MercadoPago"),
                    ("manual", "Manual"),
                ],
                max_length=20,
                verbose_name="Pasarela",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="gateway",
            field=models.CharField(
                choices=[
                    ("stripe", "Stripe"),
                    ("wompi", "Wompi"),
                    ("mercadopago", "MercadoPago"),
                    ("manual", "Manual"),
                ],
                max_length=20,
                verbose_name="Pasarela",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="gateway",
            field=models.CharField(
                choices=[
                    ("stripe", "Stripe"),
                    ("wompi", "Wompi"),
                    ("mercadopago", "MercadoPago"),
                    ("manual", "Manual"),
                ],
                default="manual",
                max_length=20,
                verbose_name="Pasarela de pago",
            ),
        ),
        migrations.AlterField(
            model_name="webhookevent",
            name="gateway",
            field=models.CharField(
                choices=[
                    ("stripe", "Stripe"),
                    ("wompi", "Wompi"),
                    ("mercadopago", "MercadoPago"),
                    ("manual", "Manual"),
                ],
                max_length=20,
                verbose_name="Pasarela",
            ),
        ),
    ]
