# Generated by Django 5.2 on 2025-06-30 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('icono', models.CharField(blank=True, help_text='Clase CSS del icono', max_length=100, null=True, verbose_name='Icono')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización', verbose_name='Orden')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Categoría de Documento',
                'verbose_name_plural': 'Categorías de Documento',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('manual', 'Manual'), ('guia', 'Guía'), ('politica', 'Política'), ('procedimiento', 'Procedimiento'), ('formato', 'Formato'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de documento')),
                ('archivo', models.FileField(help_text='Archivo del documento', upload_to='documentacion/', verbose_name='Archivo')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Versión')),
                ('tags', models.CharField(blank=True, help_text='Etiquetas separadas por comas para búsqueda', max_length=500, null=True, verbose_name='Etiquetas')),
                ('es_publico', models.BooleanField(default=True, help_text='Si es visible para todos los usuarios', verbose_name='Es público')),
                ('requiere_descarga', models.BooleanField(default=False, help_text='Si se debe descargar en lugar de ver en línea', verbose_name='Requiere descarga')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='documentacion.categoriadocumento', verbose_name='Categoría')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['categoria__orden', 'orden', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='DescargaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_descarga', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de descarga')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descargas_documentos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descargas', to='documentacion.documento', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Descarga de Documento',
                'verbose_name_plural': 'Descargas de Documento',
                'ordering': ['-fecha_descarga'],
            },
        ),
        migrations.CreateModel(
            name='VersionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, verbose_name='Versión')),
                ('archivo', models.FileField(upload_to='documentacion/versiones/', verbose_name='Archivo de la versión')),
                ('notas_version', models.TextField(blank=True, help_text='Cambios realizados en esta versión', null=True, verbose_name='Notas de la versión')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='documentacion.documento', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Versión de Documento',
                'verbose_name_plural': 'Versiones de Documento',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('documento', 'version')},
            },
        ),
    ]
