# Generated by Django 4.2.7 on 2026-01-10 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("configuracion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametrosistema",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organización a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organizacion",
            ),
        ),
        migrations.AddField(
            model_name="logconfiguracion",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organización a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organizacion",
            ),
        ),
    ]
