# Generated by Django 4.2.7 on 2026-01-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracion", "0004_remove_duplicate_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuraciongeneral",
            name="cuenta_prestamos_defecto",
            field=models.CharField(
                blank=True,
                help_text="Código de cuenta contable para préstamos (cartera)",
                max_length=20,
                null=True,
                verbose_name="Cuenta de préstamos por defecto",
            ),
        ),
        migrations.AddField(
            model_name="configuraciongeneral",
            name="cuenta_intereses_prestamo_defecto",
            field=models.CharField(
                blank=True,
                help_text="Código de cuenta contable para intereses de préstamos",
                max_length=20,
                null=True,
                verbose_name="Cuenta de intereses de préstamos",
            ),
        ),
        migrations.AddField(
            model_name="configuraciongeneral",
            name="cuenta_mora_prestamo_defecto",
            field=models.CharField(
                blank=True,
                help_text="Código de cuenta contable para mora de préstamos",
                max_length=20,
                null=True,
                verbose_name="Cuenta de mora de préstamos",
            ),
        ),
    ]
