# Generated by Django 4.2.7 on 2026-01-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracion", "0005_add_prestamos_cuentas_defecto"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuraciongeneral",
            name="cuenta_otras_deducciones_defecto",
            field=models.CharField(
                blank=True,
                help_text="Código de cuenta contable para otras deducciones de nómina",
                max_length=20,
                null=True,
                verbose_name="Cuenta otras deducciones",
            ),
        ),
    ]
