# Generated by Django 4.2.7 on 2026-02-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configuracion", "0006_add_cuenta_otras_deducciones_defecto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracionemail",
            name="email_remitente",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Dirección de email que aparecerá como remitente",
                max_length=254,
                verbose_name="Email remitente",
            ),
        ),
        migrations.AlterField(
            model_name="configuracionemail",
            name="nombre_remitente",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nombre que aparecerá como remitente",
                max_length=255,
                verbose_name="Nombre remitente",
            ),
        ),
        migrations.AlterField(
            model_name="configuracionemail",
            name="password_smtp",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Contraseña para autenticación SMTP",
                max_length=255,
                verbose_name="Contraseña SMTP",
            ),
        ),
        migrations.AlterField(
            model_name="configuracionemail",
            name="servidor_smtp",
            field=models.CharField(
                blank=True,
                default="smtp.gmail.com",
                help_text="Dirección del servidor SMTP",
                max_length=255,
                verbose_name="Servidor SMTP",
            ),
        ),
        migrations.AlterField(
            model_name="configuracionemail",
            name="usuario_smtp",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Usuario para autenticación SMTP",
                max_length=255,
                verbose_name="Usuario SMTP",
            ),
        ),
    ]
