# Generated by Django 4.2.7 on 2026-03-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_add_rbac_rol_to_invitacion"),
        ("configuracion", "0007_alter_configuracionemail_email_remitente_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parametrosistema",
            name="codigo",
            field=models.CharField(
                help_text="Código único del parámetro",
                max_length=100,
                verbose_name="Código",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="configuracionmodulo",
            unique_together={("organization", "modulo")},
        ),
        migrations.AlterUniqueTogether(
            name="parametrosistema",
            unique_together={("organization", "codigo")},
        ),
    ]
