# Generated by Django 5.2 on 2025-06-30 02:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del parámetro', max_length=100, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del parámetro', max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del parámetro', null=True, verbose_name='Descripción')),
                ('tipo_valor', models.CharField(choices=[('string', 'Texto'), ('integer', 'Número entero'), ('decimal', 'Número decimal'), ('boolean', 'Verdadero/Falso'), ('date', 'Fecha'), ('json', 'JSON')], max_length=20, verbose_name='Tipo de valor')),
                ('valor', models.TextField(help_text='Valor del parámetro', verbose_name='Valor')),
                ('valor_defecto', models.TextField(blank=True, help_text='Valor por defecto del parámetro', null=True, verbose_name='Valor por defecto')),
                ('es_sistema', models.BooleanField(default=False, help_text='Los parámetros del sistema no se pueden eliminar', verbose_name='Es del sistema')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Parámetro del Sistema',
                'verbose_name_plural': 'Parámetros del Sistema',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(help_text='Nombre oficial de la empresa', max_length=200, verbose_name='Nombre de la empresa')),
                ('nit', models.CharField(help_text='Número de identificación tributaria', max_length=50, verbose_name='NIT')),
                ('direccion', models.TextField(help_text='Dirección principal de la empresa', verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono principal')),
                ('email', models.EmailField(help_text='Email principal de la empresa', max_length=254, verbose_name='Email principal')),
                ('sitio_web', models.URLField(blank=True, null=True, verbose_name='Sitio web')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='configuracion/logos/', verbose_name='Logo de la empresa')),
                ('moneda', models.CharField(default='COP', help_text='Código de moneda (ej: COP, USD)', max_length=10, verbose_name='Moneda')),
                ('simbolo_moneda', models.CharField(default='$', max_length=5, verbose_name='Símbolo de moneda')),
                ('zona_horaria', models.CharField(default='America/Bogota', help_text='Zona horaria de la empresa', max_length=50, verbose_name='Zona horaria')),
                ('formato_fecha', models.CharField(choices=[('%d/%m/%Y', 'DD/MM/YYYY'), ('%m/%d/%Y', 'MM/DD/YYYY'), ('%Y-%m-%d', 'YYYY-MM-DD')], default='%d/%m/%Y', max_length=20, verbose_name='Formato de fecha')),
                ('dia_pago_nomina', models.PositiveIntegerField(default=30, help_text='Día del mes para pago de nómina', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Día de pago de nómina')),
                ('periodo_nomina', models.CharField(choices=[('mensual', 'Mensual'), ('quincenal', 'Quincenal'), ('semanal', 'Semanal')], default='mensual', max_length=20, verbose_name='Período de nómina')),
                ('cuenta_efectivo_defecto', models.CharField(blank=True, help_text='Código de cuenta contable para efectivo', max_length=20, null=True, verbose_name='Cuenta de efectivo por defecto')),
                ('cuenta_nomina_defecto', models.CharField(blank=True, help_text='Código de cuenta contable para nómina', max_length=20, null=True, verbose_name='Cuenta de nómina por defecto')),
                ('sesion_timeout_minutos', models.PositiveIntegerField(default=30, help_text='Tiempo de inactividad antes de cerrar sesión', verbose_name='Timeout de sesión (minutos)')),
                ('max_intentos_login', models.PositiveIntegerField(default=3, help_text='Máximo intentos fallidos antes de bloquear cuenta', verbose_name='Máximo intentos de login')),
                ('requiere_cambio_password', models.BooleanField(default=True, help_text='Si los usuarios deben cambiar contraseña periódicamente', verbose_name='Requiere cambio de contraseña')),
                ('dias_cambio_password', models.PositiveIntegerField(default=90, help_text='Cada cuántos días se debe cambiar la contraseña', verbose_name='Días para cambio de contraseña')),
                ('servidor_email', models.CharField(blank=True, help_text='Servidor SMTP para envío de correos', max_length=100, null=True, verbose_name='Servidor de email')),
                ('puerto_email', models.PositiveIntegerField(default=587, verbose_name='Puerto de email')),
                ('email_usuario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario de email')),
                ('usar_tls', models.BooleanField(default=True, help_text='Usar conexión segura TLS para email', verbose_name='Usar TLS')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Configuración General',
                'verbose_name_plural': 'Configuración General',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(help_text='Nombre del módulo a configurar', max_length=100, verbose_name='Módulo')),
                ('activo', models.BooleanField(default=True, help_text='Si el módulo está activo y disponible', verbose_name='Módulo activo')),
                ('version', models.CharField(blank=True, help_text='Versión del módulo', max_length=20, null=True, verbose_name='Versión')),
                ('configuracion_json', models.JSONField(blank=True, default=dict, help_text='Configuración específica del módulo en formato JSON', verbose_name='Configuración JSON')),
                ('orden_menu', models.PositiveIntegerField(default=0, help_text='Orden de aparición en el menú principal', verbose_name='Orden en menú')),
                ('icono', models.CharField(blank=True, help_text='Clase CSS del icono del módulo', max_length=100, null=True, verbose_name='Icono')),
                ('color', models.CharField(blank=True, help_text='Color principal del módulo', max_length=20, null=True, verbose_name='Color')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Configuración de Módulo',
                'verbose_name_plural': 'Configuraciones de Módulo',
                'ordering': ['orden_menu', 'modulo'],
                'unique_together': {('modulo',)},
            },
        ),
        migrations.CreateModel(
            name='LogConfiguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cambio', models.CharField(choices=[('general', 'Configuración General'), ('parametro', 'Parámetro'), ('modulo', 'Configuración Módulo')], max_length=20, verbose_name='Tipo de cambio')),
                ('item_modificado', models.CharField(help_text='Nombre o código del item modificado', max_length=200, verbose_name='Item modificado')),
                ('valor_anterior', models.TextField(blank=True, null=True, verbose_name='Valor anterior')),
                ('valor_nuevo', models.TextField(blank=True, null=True, verbose_name='Valor nuevo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del cambio')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del cambio')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de Configuración',
                'verbose_name_plural': 'Logs de Configuración',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
