# Generated by Django 5.2 on 2025-06-30 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logconfiguracion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Log de Configuración', 'verbose_name_plural': 'Logs de Configuración'},
        ),
        migrations.RemoveField(
            model_name='logconfiguracion',
            name='fecha_cambio',
        ),
        migrations.AddField(
            model_name='logconfiguracion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='logconfiguracion',
            name='nivel',
            field=models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('error', 'Error'), ('success', 'Éxito')], default='info', max_length=10, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='logconfiguracion',
            name='tipo_cambio',
            field=models.CharField(choices=[('general', 'Configuración General'), ('parametro', 'Parámetro'), ('modulo', 'Configuración Módulo'), ('sistema', 'Sistema')], max_length=20, verbose_name='Tipo de cambio'),
        ),
        migrations.AlterField(
            model_name='logconfiguracion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
