# Generated by Django 5.2 on 2025-06-30 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAyuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('icono', models.CharField(blank=True, help_text='Clase CSS del icono', max_length=100, null=True, verbose_name='Icono')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización', verbose_name='Orden')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Categoría de Ayuda',
                'verbose_name_plural': 'Categorías de Ayuda',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ArticuloAyuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('contenido', models.TextField(help_text='Contenido del artículo (soporta HTML)', verbose_name='Contenido')),
                ('tags', models.CharField(blank=True, help_text='Etiquetas separadas por comas para búsqueda', max_length=500, null=True, verbose_name='Etiquetas')),
                ('es_faq', models.BooleanField(default=False, help_text='Si es una pregunta frecuente', verbose_name='Es FAQ')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('publicado', models.BooleanField(default=True, verbose_name='Publicado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articulos_ayuda_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='ayuda.categoriaayuda', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Artículo de Ayuda',
                'verbose_name_plural': 'Artículos de Ayuda',
                'ordering': ['categoria__orden', 'orden', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('descripcion', models.TextField(help_text='Descripción detallada del problema o consulta', verbose_name='Descripción')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10, verbose_name='Prioridad')),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En proceso'), ('esperando_usuario', 'Esperando usuario'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='abierto', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_soporte', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Solicitud de Soporte',
                'verbose_name_plural': 'Solicitudes de Soporte',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField(verbose_name='Respuesta')),
                ('es_interna', models.BooleanField(default=False, help_text='Si es una nota interna, no visible para el usuario', verbose_name='Es interna')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de respuesta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='ayuda.solicitudsoporte', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Respuesta de Soporte',
                'verbose_name_plural': 'Respuestas de Soporte',
                'ordering': ['fecha_respuesta'],
            },
        ),
    ]
