# Generated by Django 4.2.7 on 2026-01-03 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0004_alter_logauditoria_objeto_id"),
        ("roles", "0002_alter_asignacionrol_estado"),
        ("payroll", "0001_initial"),
        ("cargos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historialcargo",
            name="empleado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historial_cargos",
                to="payroll.empleado",
                verbose_name="Empleado",
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="cargo_superior",
            field=models.ForeignKey(
                blank=True,
                help_text="Cargo del cual depende jerárquicamente",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cargos_subordinados",
                to="cargos.cargo",
                verbose_name="Cargo superior",
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organización a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organizacion",
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="roles_permitidos",
            field=models.ManyToManyField(
                blank=True,
                help_text="Roles que pueden ser asignados a este cargo",
                related_name="cargos_permitidos",
                to="roles.rol",
                verbose_name="Roles permitidos",
            ),
        ),
        migrations.AddIndex(
            model_name="historialcargo",
            index=models.Index(
                fields=["empleado", "fecha_inicio"],
                name="cargos_hist_emplead_96c82e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="historialcargo",
            index=models.Index(
                fields=["cargo_nuevo", "fecha_inicio"],
                name="cargos_hist_cargo_n_e6a28a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(fields=["activo"], name="cargos_carg_activo_2e51c4_idx"),
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(
                fields=["nivel_jerarquico"], name="cargos_carg_nivel_j_0f40c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(fields=["codigo"], name="cargos_carg_codigo_683cdd_idx"),
        ),
    ]
