# Generated by Django 4.2.7 on 2026-01-10 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cargos", "0002_initial"),
        ("nomina", "0002_initial"),
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historialcargo",
            name="empleado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historial_cargos",
                to="nomina.empleado",
                verbose_name="Empleado",
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="cargo_superior",
            field=models.ForeignKey(
                blank=True,
                help_text="Cargo del cual depende jerárquicamente",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cargos_subordinados",
                to="cargos.cargo",
                verbose_name="Cargo superior",
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organización a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organizacion",
            ),
        ),
    ]
