# Generated by Django 5.2 on 2025-08-22 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargos', '0002_initial'),
        ('payroll', '0001_initial'),
        ('roles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='roles_permitidos',
            field=models.ManyToManyField(blank=True, help_text='Roles que pueden ser asignados a este cargo', related_name='cargos_permitidos', to='roles.rol', verbose_name='Roles permitidos'),
        ),
        migrations.AddField(
            model_name='historialcargo',
            name='cargo_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historiales_anterior', to='cargos.cargo', verbose_name='Cargo anterior'),
        ),
        migrations.AddField(
            model_name='historialcargo',
            name='cargo_nuevo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historiales_nuevo', to='cargos.cargo', verbose_name='Cargo nuevo'),
        ),
        migrations.AddField(
            model_name='historialcargo',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_cargo_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='historialcargo',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_cargos', to='payroll.empleado', verbose_name='Empleado'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['activo'], name='cargos_carg_activo_2e51c4_idx'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['nivel_jerarquico'], name='cargos_carg_nivel_j_0f40c3_idx'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['codigo'], name='cargos_carg_codigo_683cdd_idx'),
        ),
        migrations.AddIndex(
            model_name='historialcargo',
            index=models.Index(fields=['empleado', 'fecha_inicio'], name='cargos_hist_emplead_96c82e_idx'),
        ),
        migrations.AddIndex(
            model_name='historialcargo',
            index=models.Index(fields=['cargo_nuevo', 'fecha_inicio'], name='cargos_hist_cargo_n_e6a28a_idx'),
        ),
    ]
