# Generated by Django 4.2.7 on 2026-01-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cargos", "0003_initial"),
        ("roles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargo",
            name="roles_permitidos",
            field=models.ManyToManyField(
                blank=True,
                help_text="Roles que pueden ser asignados a este cargo",
                related_name="cargos_permitidos",
                to="roles.rol",
                verbose_name="Roles permitidos",
            ),
        ),
        migrations.AddIndex(
            model_name="historialcargo",
            index=models.Index(
                fields=["empleado", "fecha_inicio"],
                name="cargos_hist_emplead_96c82e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="historialcargo",
            index=models.Index(
                fields=["cargo_nuevo", "fecha_inicio"],
                name="cargos_hist_cargo_n_e6a28a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(fields=["activo"], name="cargos_carg_activo_2e51c4_idx"),
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(
                fields=["nivel_jerarquico"], name="cargos_carg_nivel_j_0f40c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(fields=["codigo"], name="cargos_carg_codigo_683cdd_idx"),
        ),
    ]
