# Generated by Django 4.2.7 on 2026-01-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
        ("cargos", "0004_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargo",
            name="codigo",
            field=models.CharField(
                help_text="Código único del cargo", max_length=20, verbose_name="Código"
            ),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="nombre",
            field=models.CharField(
                help_text="Nombre único del cargo",
                max_length=150,
                verbose_name="Nombre del cargo",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cargo",
            unique_together={("organization", "nombre"), ("organization", "codigo")},
        ),
    ]
