# Generated by Django 4.2.7 on 2026-02-22 03:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cargos", "0005_fix_unique_per_organization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cargo",
            name="salario_base_maximo",
        ),
        migrations.RemoveField(
            model_name="cargo",
            name="salario_base_minimo",
        ),
    ]
