# Generated by Django 4.2.7 on 2026-02-22 03:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cargos", "0006_remove_salary_range_from_cargo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cargo",
            name="es_temporal",
        ),
        migrations.RemoveField(
            model_name="cargo",
            name="limite_aprobacion",
        ),
        migrations.RemoveField(
            model_name="cargo",
            name="puede_aprobar",
        ),
        migrations.RemoveField(
            model_name="cargo",
            name="requiere_aprobacion",
        ),
    ]
