# Generated by Django 5.2 on 2025-08-22 01:20

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Ej: Excavación manual, Instalación tubería PVC, Pintura de fachada', max_length=100, verbose_name='Nombre del Trabajo/Servicio')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del trabajo o servicio', verbose_name='Descripción')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio por unidad de medida (por m², m³, ml o global)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio Unitario')),
                ('tipo_cantidad', models.CharField(choices=[('m2', 'Metro cuadrado (m²)'), ('m3', 'Metro cúbico (m³)'), ('ml', 'Metro lineal (ml)'), ('global', 'Global')], default='m2', help_text='Unidad de medida para el trabajo', max_length=10, verbose_name='Tipo de Medición')),
                ('codigo', models.CharField(blank=True, help_text='Código interno del trabajo (opcional)', max_length=50, verbose_name='Código')),
                ('activo', models.BooleanField(default=True, help_text='Si el trabajo/servicio está disponible', verbose_name='Activo')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre el trabajo', verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.organizacion', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Item de Trabajo',
                'verbose_name_plural': 'Items de Trabajo',
                'ordering': ['nombre'],
                'unique_together': {('organization', 'nombre')},
            },
        ),
    ]
