# Generated by Django 4.2.7 on 2026-01-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArticuloAyuda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=220, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "contenido",
                    models.TextField(
                        help_text="Contenido del artículo (soporta HTML)",
                        verbose_name="Contenido",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Etiquetas separadas por comas para búsqueda",
                        max_length=500,
                        null=True,
                        verbose_name="Etiquetas",
                    ),
                ),
                (
                    "es_faq",
                    models.BooleanField(
                        default=False,
                        help_text="Si es una pregunta frecuente",
                        verbose_name="Es FAQ",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                (
                    "publicado",
                    models.BooleanField(default=True, verbose_name="Publicado"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "vistas",
                    models.PositiveIntegerField(default=0, verbose_name="Vistas"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Artículo de Ayuda",
                "verbose_name_plural": "Artículos de Ayuda",
                "ordering": ["categoria__orden", "orden", "titulo"],
            },
        ),
        migrations.CreateModel(
            name="CategoriaAyuda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Nombre de la categoría",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "icono",
                    models.CharField(
                        blank=True,
                        help_text="Clase CSS del icono",
                        max_length=100,
                        null=True,
                        verbose_name="Icono",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Orden de visualización",
                        verbose_name="Orden",
                    ),
                ),
                ("activa", models.BooleanField(default=True, verbose_name="Activa")),
            ],
            options={
                "verbose_name": "Categoría de Ayuda",
                "verbose_name_plural": "Categorías de Ayuda",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pregunta", models.CharField(max_length=300, verbose_name="Pregunta")),
                ("respuesta", models.TextField(verbose_name="Respuesta")),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("cuenta", "Cuenta"),
                            ("facturacion", "Facturación"),
                            ("tecnico", "Técnico"),
                            ("seguridad", "Seguridad"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="Categoría",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "vistas",
                    models.PositiveIntegerField(default=0, verbose_name="Vistas"),
                ),
                (
                    "util_si",
                    models.PositiveIntegerField(default=0, verbose_name="Útil - Sí"),
                ),
                (
                    "util_no",
                    models.PositiveIntegerField(default=0, verbose_name="Útil - No"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pregunta Frecuente",
                "verbose_name_plural": "Preguntas Frecuentes",
                "ordering": ["categoria", "orden", "pregunta"],
            },
        ),
        migrations.CreateModel(
            name="PasoTutorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_paso",
                    models.PositiveIntegerField(verbose_name="Número de paso"),
                ),
                (
                    "titulo",
                    models.CharField(max_length=200, verbose_name="Título del paso"),
                ),
                ("contenido", models.TextField(verbose_name="Contenido")),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tutoriales/pasos/",
                        verbose_name="Imagen",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL del video"
                    ),
                ),
                (
                    "codigo_ejemplo",
                    models.TextField(
                        blank=True, null=True, verbose_name="Código de ejemplo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Paso de Tutorial",
                "verbose_name_plural": "Pasos de Tutorial",
                "ordering": ["tutorial", "numero_paso"],
            },
        ),
        migrations.CreateModel(
            name="ProgresoTutorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completado",
                    models.BooleanField(default=False, verbose_name="Completado"),
                ),
                (
                    "fecha_inicio",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de inicio"
                    ),
                ),
                (
                    "fecha_completado",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de completado"
                    ),
                ),
                (
                    "tiempo_total",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Tiempo total en segundos",
                        verbose_name="Tiempo total",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progreso de Tutorial",
                "verbose_name_plural": "Progreso de Tutoriales",
            },
        ),
        migrations.CreateModel(
            name="RecursoAyuda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("archivo", "Archivo"),
                            ("enlace", "Enlace"),
                            ("video", "Video"),
                            ("imagen", "Imagen"),
                        ],
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="ayuda/recursos/",
                        verbose_name="Archivo",
                    ),
                ),
                ("url", models.URLField(blank=True, null=True, verbose_name="URL")),
                ("orden", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurso de Ayuda",
                "verbose_name_plural": "Recursos de Ayuda",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="RespuestaSoporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("respuesta", models.TextField(verbose_name="Respuesta")),
                (
                    "es_interna",
                    models.BooleanField(
                        default=False,
                        help_text="Si es una nota interna, no visible para el usuario",
                        verbose_name="Es interna",
                    ),
                ),
                (
                    "fecha_respuesta",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de respuesta"
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta de Soporte",
                "verbose_name_plural": "Respuestas de Soporte",
                "ordering": ["fecha_respuesta"],
            },
        ),
        migrations.CreateModel(
            name="SolicitudSoporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asunto", models.CharField(max_length=200, verbose_name="Asunto")),
                (
                    "descripcion",
                    models.TextField(
                        help_text="Descripción detallada del problema o consulta",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                            ("critica", "Crítica"),
                        ],
                        default="media",
                        max_length=10,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("abierta", "Abierta"),
                            ("en_proceso", "En proceso"),
                            ("esperando_usuario", "Esperando usuario"),
                            ("resuelta", "Resuelta"),
                            ("cerrada", "Cerrada"),
                        ],
                        default="abierta",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        default="general",
                        help_text="Categoría de la solicitud",
                        max_length=50,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de Soporte",
                "verbose_name_plural": "Solicitudes de Soporte",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="TipoAyuda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("articulo", "Artículo"),
                            ("faq", "FAQ"),
                            ("tutorial", "Tutorial"),
                            ("video", "Video"),
                            ("documento", "Documento"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "icono",
                    models.CharField(
                        blank=True,
                        help_text="Clase CSS del icono",
                        max_length=100,
                        null=True,
                        verbose_name="Icono",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Color hexadecimal o nombre CSS",
                        max_length=20,
                        null=True,
                        verbose_name="Color",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Ayuda",
                "verbose_name_plural": "Tipos de Ayuda",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Tutorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=220, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "dificultad",
                    models.CharField(
                        choices=[
                            ("basico", "Básico"),
                            ("intermedio", "Intermedio"),
                            ("avanzado", "Avanzado"),
                        ],
                        default="basico",
                        max_length=15,
                        verbose_name="Dificultad",
                    ),
                ),
                (
                    "tiempo_estimado",
                    models.PositiveIntegerField(
                        help_text="Tiempo estimado en minutos",
                        verbose_name="Tiempo estimado",
                    ),
                ),
                (
                    "imagen_portada",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tutoriales/portadas/",
                        verbose_name="Imagen de portada",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Etiquetas separadas por comas",
                        max_length=500,
                        null=True,
                        verbose_name="Etiquetas",
                    ),
                ),
                (
                    "publicado",
                    models.BooleanField(default=False, verbose_name="Publicado"),
                ),
                (
                    "destacado",
                    models.BooleanField(default=False, verbose_name="Destacado"),
                ),
                (
                    "vistas",
                    models.PositiveIntegerField(default=0, verbose_name="Vistas"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tutorial",
                "verbose_name_plural": "Tutoriales",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
