# Generated by Django 4.2.7 on 2026-01-10 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("ayuda", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorial",
            name="autor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tutoriales_creados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Autor",
            ),
        ),
        migrations.AddField(
            model_name="tutorial",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tutoriales",
                to="ayuda.tipoayuda",
                verbose_name="Categoría",
            ),
        ),
        migrations.AddField(
            model_name="tutorial",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organización a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organizacion",
            ),
        ),
        migrations.AddField(
            model_name="tipoayuda",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organización a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organizacion",
            ),
        ),
        migrations.AddField(
            model_name="solicitudsoporte",
            name="asignado_a",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="solicitudes_asignadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Asignado a",
            ),
        ),
        migrations.AddField(
            model_name="solicitudsoporte",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organización a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organizacion",
            ),
        ),
        migrations.AddField(
            model_name="solicitudsoporte",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="solicitudes_soporte",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AddField(
            model_name="respuestasoporte",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organización a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organizacion",
            ),
        ),
        migrations.AddField(
            model_name="respuestasoporte",
            name="solicitud",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="respuestas",
                to="ayuda.solicitudsoporte",
                verbose_name="Solicitud",
            ),
        ),
        migrations.AddField(
            model_name="respuestasoporte",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AddField(
            model_name="recursoayuda",
            name="articulo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recursos",
                to="ayuda.articuloayuda",
                verbose_name="Artículo",
            ),
        ),
        migrations.AddField(
            model_name="recursoayuda",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organización a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organizacion",
            ),
        ),
        migrations.AddField(
            model_name="recursoayuda",
            name="paso_tutorial",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recursos",
                to="ayuda.pasotutorial",
                verbose_name="Paso de tutorial",
            ),
        ),
        migrations.AddField(
            model_name="recursoayuda",
            name="tutorial",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recursos",
                to="ayuda.tutorial",
                verbose_name="Tutorial",
            ),
        ),
        migrations.AddField(
            model_name="progresotutorial",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organización a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organizacion",
            ),
        ),
        migrations.AddField(
            model_name="progresotutorial",
            name="paso_actual",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ayuda.pasotutorial",
                verbose_name="Paso actual",
            ),
        ),
        migrations.AddField(
            model_name="progresotutorial",
            name="tutorial",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progreso_usuarios",
                to="ayuda.tutorial",
                verbose_name="Tutorial",
            ),
        ),
        migrations.AddField(
            model_name="progresotutorial",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progreso_tutoriales",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AddField(
            model_name="pasotutorial",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organización a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organizacion",
            ),
        ),
        migrations.AddField(
            model_name="pasotutorial",
            name="tutorial",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pasos",
                to="ayuda.tutorial",
                verbose_name="Tutorial",
            ),
        ),
        migrations.AddField(
            model_name="faq",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organización a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organizacion",
            ),
        ),
        migrations.AddField(
            model_name="categoriaayuda",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organización a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organizacion",
            ),
        ),
        migrations.AddField(
            model_name="articuloayuda",
            name="autor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="articulos_ayuda_creados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Autor",
            ),
        ),
        migrations.AddField(
            model_name="articuloayuda",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articulos",
                to="ayuda.categoriaayuda",
                verbose_name="Categoría",
            ),
        ),
        migrations.AddField(
            model_name="articuloayuda",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organización a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organizacion",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="progresotutorial",
            unique_together={("usuario", "tutorial")},
        ),
        migrations.AlterUniqueTogether(
            name="pasotutorial",
            unique_together={("tutorial", "numero_paso")},
        ),
    ]
