# Generated by Django 4.2.7 on 2026-03-13 02:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_add_rbac_rol_to_invitacion"),
        ("ayuda", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articuloayuda",
            name="slug",
            field=models.SlugField(blank=True, max_length=220, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="categoriaayuda",
            name="nombre",
            field=models.CharField(
                max_length=100, verbose_name="Nombre de la categoría"
            ),
        ),
        migrations.AlterField(
            model_name="recursoayuda",
            name="archivo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="ayuda/recursos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "pdf",
                            "doc",
                            "docx",
                            "xls",
                            "xlsx",
                            "csv",
                            "txt",
                            "png",
                            "jpg",
                            "jpeg",
                            "gif",
                            "mp4",
                            "webm",
                        ]
                    )
                ],
                verbose_name="Archivo",
            ),
        ),
        migrations.AlterField(
            model_name="tutorial",
            name="slug",
            field=models.SlugField(blank=True, max_length=220, verbose_name="Slug"),
        ),
        migrations.AlterUniqueTogether(
            name="articuloayuda",
            unique_together={("organization", "slug")},
        ),
        migrations.AlterUniqueTogether(
            name="categoriaayuda",
            unique_together={("organization", "nombre")},
        ),
        migrations.AlterUniqueTogether(
            name="tutorial",
            unique_together={("organization", "slug")},
        ),
    ]
