# Generated by Django 4.2.7 on 2026-01-10 21:18

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConceptoLaboral",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código único del concepto",
                        max_length=20,
                        verbose_name="Código",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("DEVENGADO", "Devengado"),
                            ("DEDUCCION", "Deducción"),
                        ],
                        help_text="Define si aumenta o reduce el salario",
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "aplica_porcentaje",
                    models.BooleanField(
                        default=False,
                        help_text="¿El valor se calcula como porcentaje?",
                        verbose_name="Aplica Porcentaje",
                    ),
                ),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        help_text="Porcentaje a aplicar (si aplica_porcentaje=True)",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.000")),
                            django.core.validators.MaxValueValidator(
                                Decimal("100.000")
                            ),
                        ],
                        verbose_name="Porcentaje (%)",
                    ),
                ),
                (
                    "monto_fijo",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Monto fijo a aplicar (si aplica_porcentaje=False)",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Monto Fijo",
                    ),
                ),
                (
                    "base_calculo",
                    models.CharField(
                        choices=[
                            ("SALARIO", "Salario"),
                            ("IBC", "Ingreso Base de Cotización"),
                            ("DEVENGADO", "Total Devengado"),
                        ],
                        default="SALARIO",
                        help_text="Sobre qué valor se calcula el porcentaje",
                        max_length=20,
                        verbose_name="Base de Cálculo",
                    ),
                ),
                (
                    "es_legal",
                    models.BooleanField(
                        default=False,
                        help_text="¿Es un concepto de ley (salud, pensión)?",
                        verbose_name="Es Concepto Legal",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Orden de aplicación en la nómina",
                        verbose_name="Orden",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Concepto Laboral",
                "verbose_name_plural": "Conceptos Laborales",
                "ordering": ["tipo", "orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Contrato",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "salario",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Salario mensual del empleado",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Salario",
                    ),
                ),
                (
                    "nivel_arl",
                    models.CharField(
                        choices=[
                            ("I", "Nivel I - Riesgo Mínimo (0.522%)"),
                            ("II", "Nivel II - Riesgo Bajo (1.044%)"),
                            ("III", "Nivel III - Riesgo Medio (2.436%)"),
                            ("IV", "Nivel IV - Riesgo Alto (4.350%)"),
                            ("V", "Nivel V - Riesgo Máximo (6.960%)"),
                        ],
                        default="I",
                        max_length=5,
                        verbose_name="Nivel de Riesgo ARL",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de Inicio")),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True,
                        help_text="Dejar vacío para contratos indefinidos",
                        null=True,
                        verbose_name="Fecha de Fin",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si es el contrato vigente del empleado",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "cargo",
                    models.CharField(
                        blank=True,
                        help_text="Cargo o posición del empleado",
                        max_length=100,
                        verbose_name="Cargo",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Contrato",
                "verbose_name_plural": "Contratos",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("CC", "Cédula de Ciudadanía"),
                            ("CE", "Cédula de Extranjería"),
                            ("TI", "Tarjeta de Identidad"),
                            ("PA", "Pasaporte"),
                            ("NIT", "NIT"),
                        ],
                        default="CC",
                        max_length=5,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El documento debe contener entre 5 y 20 dígitos",
                                regex="^[0-9]{5,20}$",
                            )
                        ],
                        verbose_name="Número de Documento",
                    ),
                ),
                (
                    "primer_nombre",
                    models.CharField(max_length=50, verbose_name="Primer Nombre"),
                ),
                (
                    "segundo_nombre",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Segundo Nombre"
                    ),
                ),
                (
                    "primer_apellido",
                    models.CharField(max_length=50, verbose_name="Primer Apellido"),
                ),
                (
                    "segundo_apellido",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Segundo Apellido"
                    ),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Nacimiento"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono"
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Dirección"
                    ),
                ),
                (
                    "ciudad",
                    models.CharField(blank=True, max_length=100, verbose_name="Ciudad"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("inactivo", "Inactivo"),
                            ("retirado", "Retirado"),
                        ],
                        default="activo",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_ingreso",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Ingreso",
                    ),
                ),
                (
                    "fecha_retiro",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Retiro"
                    ),
                ),
                (
                    "banco",
                    models.CharField(blank=True, max_length=100, verbose_name="Banco"),
                ),
                (
                    "tipo_cuenta",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ahorros", "Cuenta de Ahorros"),
                            ("corriente", "Cuenta Corriente"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Cuenta",
                    ),
                ),
                (
                    "numero_cuenta",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Número de Cuenta"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Empleado",
                "verbose_name_plural": "Empleados",
                "ordering": ["primer_apellido", "primer_nombre"],
            },
        ),
        migrations.CreateModel(
            name="NominaConcepto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "base",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Base de Cálculo",
                    ),
                ),
                (
                    "porcentaje_aplicado",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        max_digits=6,
                        verbose_name="Porcentaje Aplicado",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Valor",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("DEVENGADO", "Devengado"),
                            ("DEDUCCION", "Deducción"),
                        ],
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Concepto de Nómina",
                "verbose_name_plural": "Conceptos de Nómina",
                "ordering": ["tipo", "concepto__orden"],
            },
        ),
        migrations.CreateModel(
            name="NominaItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Valor Unitario",
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Valor Total",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Item de Nómina",
                "verbose_name_plural": "Items de Nómina",
                "ordering": ["item__nombre"],
            },
        ),
        migrations.CreateModel(
            name="TipoContrato",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: Término Indefinido, Término Fijo, Prestación de Servicios",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código corto del tipo de contrato",
                        max_length=20,
                        verbose_name="Código",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "aplica_salud",
                    models.BooleanField(
                        default=True,
                        help_text="¿Se descuenta salud al empleado?",
                        verbose_name="Aplica Salud",
                    ),
                ),
                (
                    "aplica_pension",
                    models.BooleanField(
                        default=True,
                        help_text="¿Se descuenta pensión al empleado?",
                        verbose_name="Aplica Pensión",
                    ),
                ),
                (
                    "aplica_arl",
                    models.BooleanField(
                        default=True,
                        help_text="¿Se paga ARL por este empleado?",
                        verbose_name="Aplica ARL",
                    ),
                ),
                (
                    "aplica_parafiscales",
                    models.BooleanField(
                        default=True,
                        help_text="¿Se pagan parafiscales (Caja, SENA, ICBF)?",
                        verbose_name="Aplica Parafiscales",
                    ),
                ),
                (
                    "ibc_porcentaje",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100.00"),
                        help_text="Porcentaje del ingreso que se toma como IBC (100% laboral, 40% servicios)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="Porcentaje IBC (%)",
                    ),
                ),
                (
                    "requiere_fecha_fin",
                    models.BooleanField(
                        default=False,
                        help_text="¿El contrato debe tener fecha de finalización?",
                        verbose_name="Requiere Fecha Fin",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organización a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organizacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Contrato",
                "verbose_name_plural": "Tipos de Contrato",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="ParametroLegal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "concepto",
                    models.CharField(
                        choices=[
                            ("SALUD", "Salud"),
                            ("PENSION", "Pensión"),
                            ("ARL_I", "ARL Nivel I"),
                            ("ARL_II", "ARL Nivel II"),
                            ("ARL_III", "ARL Nivel III"),
                            ("ARL_IV", "ARL Nivel IV"),
                            ("ARL_V", "ARL Nivel V"),
                            ("CAJA", "Caja de Compensación"),
                            ("SENA", "SENA"),
                            ("ICBF", "ICBF"),
                            ("SMMLV", "Salario Mínimo"),
                            ("AUX_TRANSPORTE", "Auxilio de Transporte"),
                        ],
                        max_length=20,
                        verbose_name="Concepto",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Descripción"
                    ),
                ),
                (
                    "porcentaje_total",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        help_text="Porcentaje total del aporte",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.000")),
                            django.core.validators.MaxValueValidator(
                                Decimal("100.000")
                            ),
                        ],
                        verbose_name="Porcentaje Total (%)",
                    ),
                ),
                (
                    "porcentaje_empleado",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        help_text="Porcentaje que paga el empleado",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.000")),
                            django.core.validators.MaxValueValidator(
                                Decimal("100.000")
                            ),
                        ],
                        verbose_name="Porcentaje Empleado (%)",
                    ),
                ),
                (
                    "porcentaje_empleador",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        help_text="Porcentaje que paga el empleador",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.000")),
                            django.core.validators.MaxValueValidator(
                                Decimal("100.000")
                            ),
                        ],
                        verbose_name="Porcentaje Empleador (%)",
                    ),
                ),
                (
                    "valor_fijo",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Valor fijo (usado para SMMLV y Auxilio de Transporte)",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Valor Fijo",
                    ),
                ),
                (
                    "vigente_desde",
                    models.DateField(
                        help_text="Fecha desde la cual aplica este parámetro",
                        verbose_name="Vigente Desde",
                    ),
                ),
                (
                    "vigente_hasta",
                    models.DateField(
                        blank=True,
                        help_text="Fecha hasta la cual aplica (vacío = vigente indefinidamente)",
                        null=True,
                        verbose_name="Vigente Hasta",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organización a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organizacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parámetro Legal",
                "verbose_name_plural": "Parámetros Legales",
                "ordering": ["concepto", "-vigente_desde"],
            },
        ),
        migrations.CreateModel(
            name="NominaSimple",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        help_text="Número consecutivo de la nómina",
                        max_length=20,
                        verbose_name="Número",
                    ),
                ),
                ("periodo_inicio", models.DateField(verbose_name="Inicio del Período")),
                ("periodo_fin", models.DateField(verbose_name="Fin del Período")),
                (
                    "fecha_pago",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Pago"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("calculada", "Calculada"),
                            ("aprobada", "Aprobada"),
                            ("pagada", "Pagada"),
                            ("anulada", "Anulada"),
                        ],
                        default="borrador",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "salario_base",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Salario Base",
                    ),
                ),
                (
                    "ibc",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="IBC (Ingreso Base de Cotización)",
                    ),
                ),
                (
                    "total_items",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total Items de Trabajo",
                    ),
                ),
                (
                    "total_devengado",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Salario + Items + Devengados",
                        max_digits=12,
                        verbose_name="Total Devengado",
                    ),
                ),
                (
                    "total_deducciones",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Salud + Pensión + Otros descuentos",
                        max_digits=12,
                        verbose_name="Total Deducciones",
                    ),
                ),
                (
                    "total_prestamos",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total Préstamos",
                    ),
                ),
                (
                    "total_pagar",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total Devengado - Total Deducciones - Préstamos",
                        max_digits=12,
                        verbose_name="Total a Pagar",
                    ),
                ),
                (
                    "aporte_salud_empleador",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Aporte Salud Empleador",
                    ),
                ),
                (
                    "aporte_pension_empleador",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Aporte Pensión Empleador",
                    ),
                ),
                (
                    "aporte_arl",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Aporte ARL",
                    ),
                ),
                (
                    "aporte_caja",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Aporte Caja de Compensación",
                    ),
                ),
                (
                    "aporte_sena",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Aporte SENA",
                    ),
                ),
                (
                    "aporte_icbf",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Aporte ICBF",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "calculada_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Cálculo"
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nominas",
                        to="nomina.contrato",
                        verbose_name="Contrato",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organización a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organizacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nómina",
                "verbose_name_plural": "Nóminas",
                "ordering": ["-periodo_fin", "-numero"],
            },
        ),
        migrations.CreateModel(
            name="NominaPrestamo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "valor_cuota",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Valor de la Cuota",
                    ),
                ),
                (
                    "numero_cuota",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Número de Cuota"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nomina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prestamos",
                        to="nomina.nominasimple",
                        verbose_name="Nómina",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organización a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organizacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Descuento de Préstamo",
                "verbose_name_plural": "Descuentos de Préstamos",
                "ordering": ["prestamo__created_at"],
            },
        ),
    ]
