# Generated by Django 4.2.7 on 2026-01-10 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("items", "0001_initial"),
        ("prestamos", "0001_initial"),
        ("core", "0002_initial"),
        ("nomina", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nominaprestamo",
            name="prestamo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="descuentos_nomina",
                to="prestamos.prestamo",
                verbose_name="Préstamo",
            ),
        ),
        migrations.AddField(
            model_name="nominaitem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nomina_items",
                to="items.item",
                verbose_name="Item de Trabajo",
            ),
        ),
        migrations.AddField(
            model_name="nominaitem",
            name="nomina",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="nomina.nominasimple",
                verbose_name="Nómina",
            ),
        ),
        migrations.AddField(
            model_name="nominaitem",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organización a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organizacion",
            ),
        ),
        migrations.AddField(
            model_name="nominaconcepto",
            name="concepto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nomina_conceptos",
                to="nomina.conceptolaboral",
                verbose_name="Concepto",
            ),
        ),
        migrations.AddField(
            model_name="nominaconcepto",
            name="nomina",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conceptos",
                to="nomina.nominasimple",
                verbose_name="Nómina",
            ),
        ),
        migrations.AddField(
            model_name="nominaconcepto",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organización a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organizacion",
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organización a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organizacion",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="empleado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contratos",
                to="nomina.empleado",
                verbose_name="Empleado",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organización a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organizacion",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="tipo_contrato",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contratos",
                to="nomina.tipocontrato",
                verbose_name="Tipo de Contrato",
            ),
        ),
        migrations.AddField(
            model_name="conceptolaboral",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organización a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organizacion",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tipocontrato",
            unique_together={("organization", "codigo")},
        ),
        migrations.AddIndex(
            model_name="parametrolegal",
            index=models.Index(
                fields=["organization", "concepto", "activo"],
                name="nomina_para_organiz_a59200_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="parametrolegal",
            index=models.Index(
                fields=["vigente_desde", "vigente_hasta"],
                name="nomina_para_vigente_ac7fe9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="nominasimple",
            index=models.Index(
                fields=["organization", "contrato", "periodo_inicio"],
                name="nomina_nomi_organiz_8a0d62_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="nominasimple",
            index=models.Index(fields=["estado"], name="nomina_nomi_estado_8b03bb_idx"),
        ),
        migrations.AddIndex(
            model_name="nominasimple",
            index=models.Index(
                fields=["-periodo_fin"], name="nomina_nomi_periodo_2cc2cc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="nominasimple",
            unique_together={("organization", "numero")},
        ),
        migrations.AlterUniqueTogether(
            name="nominaconcepto",
            unique_together={("nomina", "concepto")},
        ),
        migrations.AddIndex(
            model_name="empleado",
            index=models.Index(
                fields=["organization", "estado"], name="nomina_empl_organiz_cc071c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="empleado",
            index=models.Index(
                fields=["numero_documento"], name="nomina_empl_numero__a90510_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="empleado",
            unique_together={("organization", "numero_documento")},
        ),
        migrations.AddIndex(
            model_name="contrato",
            index=models.Index(
                fields=["organization", "empleado", "activo"],
                name="nomina_cont_organiz_67459b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contrato",
            index=models.Index(
                fields=["fecha_inicio", "fecha_fin"],
                name="nomina_cont_fecha_i_15a9b6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conceptolaboral",
            index=models.Index(
                fields=["organization", "tipo", "activo"],
                name="nomina_conc_organiz_bb7b73_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="conceptolaboral",
            unique_together={("organization", "codigo")},
        ),
    ]
