# Generated by Django 4.2.7 on 2026-01-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nomina", "0003_alter_parametrolegal_concepto"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="departamento",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Departamento"
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="foto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="empleados/fotos/",
                verbose_name="Foto de Perfil",
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="genero",
            field=models.CharField(
                blank=True,
                choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                max_length=1,
                verbose_name="Género",
            ),
        ),
    ]
