# Generated by Django 4.2.7 on 2026-01-12 19:47
# NOTE: This migration is now a no-op because 0005_alter_empleado_ciudad_alter_empleado_departamento.py
# handles the conversion. Kept for migration history compatibility.

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nomina", "0004_empleado_departamento_empleado_foto_empleado_genero"),
        ("locations", "0001_initial"),
    ]

    operations = [
        # No-op: conversion handled by 0005_alter_empleado_ciudad_alter_empleado_departamento.py
    ]
