# Generated by Django 4.2.7 on 2026-01-12 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
        ("nomina", "0004_empleado_departamento_empleado_foto_empleado_genero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleado",
            name="ciudad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="empleados",
                to="locations.municipio",
                verbose_name="Ciudad/Municipio",
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="departamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="empleados",
                to="locations.departamento",
                verbose_name="Departamento",
            ),
        ),
    ]
