# Generated by Django 4.2.7 on 2026-01-12 19:47

from django.db import migrations, models
import django.db.models.deletion


def limpiar_datos_ubicacion(apps, schema_editor):
    """Limpia los datos existentes antes de cambiar el tipo de campo"""
    Empleado = apps.get_model('nomina', 'Empleado')
    # Actualizar registros con strings vacíos a NULL
    Empleado.objects.filter(departamento='').update(departamento=None)
    Empleado.objects.filter(ciudad='').update(ciudad=None)


class Migration(migrations.Migration):
    dependencies = [
        ("nomina", "0004_empleado_departamento_empleado_foto_empleado_genero"),
        ("locations", "0001_initial"),
    ]

    operations = [
        # Paso 1: Hacer los campos actuales nullable
        migrations.AlterField(
            model_name='empleado',
            name='departamento',
            field=models.CharField(max_length=100, blank=True, null=True, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='ciudad',
            field=models.CharField(max_length=100, blank=True, null=True, verbose_name='Ciudad'),
        ),
        
        # Paso 2: Limpiar datos
        migrations.RunPython(limpiar_datos_ubicacion, migrations.RunPython.noop),
        
        # Paso 3: Crear nuevos campos temporales con ForeignKey
        migrations.AddField(
            model_name='empleado',
            name='departamento_new',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='empleados_nomina',
                to='locations.departamento',
                verbose_name='Departamento'
            ),
        ),
        migrations.AddField(
            model_name='empleado',
            name='ciudad_new',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='empleados_nomina',
                to='locations.municipio',
                verbose_name='Ciudad'
            ),
        ),
        
        # Paso 4: Eliminar campos antiguos
        migrations.RemoveField(
            model_name='empleado',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='ciudad',
        ),
        
        # Paso 5: Renombrar nuevos campos
        migrations.RenameField(
            model_name='empleado',
            old_name='departamento_new',
            new_name='departamento',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='ciudad_new',
            new_name='ciudad',
        ),
    ]
