# Generated by Django 4.2.7 on 2026-01-12 21:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nomina", "0005_alter_empleado_ciudad_alter_empleado_departamento"),
        ("nomina", "0005_change_departamento_ciudad_to_fk"),
        ("nomina", "0005_change_location_fields"),
    ]

    operations = []
