# Generated by Django 4.2.7 on 2026-01-13 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("nomina", "0006_merge_20260112_1625"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="usuario",
            field=models.OneToOneField(
                blank=True,
                help_text="Si el empleado tiene acceso al sistema, enlazar con su usuario",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="empleado",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario del Sistema",
            ),
        ),
    ]
