# Generated by Django 4.2.7 on 2026-01-13 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cargos", "0005_fix_unique_per_organization"),
        ("nomina", "0007_empleado_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrato",
            name="cargo",
            field=models.ForeignKey(
                blank=True,
                help_text="Cargo o posición del empleado",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contratos",
                to="cargos.cargo",
                verbose_name="Cargo",
            ),
        ),
    ]
