# Generated by GitHub Copilot on 2026-01-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0010_nomina_conceptos_seleccionados'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominasimple',
            name='incluir_salario_base',
            field=models.BooleanField(default=False, verbose_name='Incluir Salario Base'),
        ),
    ]
