# Generated by Django 4.2.7 on 2026-01-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nomina", "0011_nomina_incluir_salario_base"),
    ]

    operations = [
        migrations.AddField(
            model_name="nominasimple",
            name="cuotas_a_descontar",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Diccionario {prestamo_id: cantidad_cuotas}",
                null=True,
                verbose_name="Cuotas a Descontar por Préstamo",
            ),
        ),
    ]
