# Generated by Django 4.2.7 on 2026-02-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nomina", "0012_nominasimple_cuotas_a_descontar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parametrolegal",
            name="concepto",
            field=models.CharField(
                choices=[
                    ("SALUD", "Salud"),
                    ("PENSION", "Pensión"),
                    ("ARL_NIVEL_I", "ARL Nivel I"),
                    ("ARL_NIVEL_II", "ARL Nivel II"),
                    ("ARL_NIVEL_III", "ARL Nivel III"),
                    ("ARL_NIVEL_IV", "ARL Nivel IV"),
                    ("ARL_NIVEL_V", "ARL Nivel V"),
                    ("CAJA_COMPENSACION", "Caja de Compensación"),
                    ("SENA", "SENA"),
                    ("ICBF", "ICBF"),
                    ("CESANTIAS", "Cesantías"),
                    ("INTERESES_CESANTIAS", "Intereses sobre Cesantías"),
                    ("PRIMA_SERVICIOS", "Prima de Servicios"),
                    ("VACACIONES", "Vacaciones"),
                    ("SMMLV", "Salario Mínimo"),
                    ("AUXILIO_TRANSPORTE", "Auxilio de Transporte"),
                    ("TOPE_AUXILIO_TRANSPORTE", "Tope Auxilio Transporte"),
                    ("IBC_SERVICIOS", "IBC Servicios"),
                    ("UVT", "Unidad de Valor Tributario"),
                    ("TOPE_FSP", "Tope Fondo Solidaridad Pensional"),
                    ("TOPE_SUBSISTENCIA", "Tope Aporte Subsistencia"),
                    ("FSP", "Fondo de Solidaridad Pensional"),
                    ("SUBSISTENCIA", "Aporte Subsistencia"),
                ],
                max_length=30,
                verbose_name="Concepto",
            ),
        ),
    ]
