# Generated by Django 4.2.7 on 2026-02-18 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nomina", "0013_alter_parametrolegal_concepto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nominasimple",
            name="numero",
            field=models.CharField(
                blank=True,
                help_text="Número consecutivo de la nómina (se genera automáticamente)",
                max_length=20,
                verbose_name="Número",
            ),
        ),
    ]
