# Generated by Django 5.2.5 on 2026-02-28 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_activeproject_asignacionproyecto_and_more"),
        ("nomina", "0014_allow_blank_numero_nomina"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="proyecto",
            field=models.ForeignKey(
                blank=True,
                help_text="Proyecto al que está asignado este contrato",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contratos",
                to="dashboard.project",
                verbose_name="Proyecto",
            ),
        ),
        migrations.AddField(
            model_name="nominasimple",
            name="proyecto",
            field=models.ForeignKey(
                blank=True,
                help_text="Proyecto al que pertenece esta nómina",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nominas",
                to="dashboard.project",
                verbose_name="Proyecto",
            ),
        ),
    ]
