# Generated by Django 5.2 on 2025-08-22 01:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Nombre del contratista', max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(help_text='Apellido del contratista', max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(help_text='Email único del contratista', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Correo electrónico')),
                ('phone_number', models.CharField(blank=True, help_text='Número de teléfono de contacto', max_length=15, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe tener el formato: '+999999999'. Hasta 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('company', models.CharField(blank=True, help_text='Empresa a la que pertenece el contratista', max_length=100, verbose_name='Empresa')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro', verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización', verbose_name='Actualizado el')),
                ('organization', models.ForeignKey(blank=True, help_text='Organización a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organizacion')),
            ],
            options={
                'verbose_name': 'Contratista',
                'verbose_name_plural': 'Contratistas',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo del proyecto', max_length=150, verbose_name='Nombre del Proyecto')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del proyecto', verbose_name='Descripción')),
                ('start_date', models.DateField(help_text='Fecha de inicio del proyecto', verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, help_text='Fecha de finalización del proyecto (opcional)', null=True, verbose_name='Fecha de finalización')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro', verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización', verbose_name='Actualizado el')),
                ('contractor', models.ForeignKey(help_text='Contratista asignado al proyecto', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='dashboard.contractor', verbose_name='Contratista')),
                ('organization', models.ForeignKey(blank=True, help_text='Organización a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organizacion')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto del pago', max_digits=10, verbose_name='Monto')),
                ('payment_date', models.DateField(help_text='Fecha en que se realizó el pago', verbose_name='Fecha de pago')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el pago', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro', verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización', verbose_name='Actualizado el')),
                ('organization', models.ForeignKey(blank=True, help_text='Organización a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organizacion')),
                ('project', models.ForeignKey(help_text='Proyecto al que pertenece el pago', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='dashboard.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddIndex(
            model_name='contractor',
            index=models.Index(fields=['email'], name='dashboard_c_email_ee997e_idx'),
        ),
        migrations.AddIndex(
            model_name='contractor',
            index=models.Index(fields=['last_name', 'first_name'], name='dashboard_c_last_na_453a2f_idx'),
        ),
        migrations.AddIndex(
            model_name='contractor',
            index=models.Index(fields=['created_at'], name='dashboard_c_created_2a4e83_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['contractor'], name='dashboard_p_contrac_25b544_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['start_date'], name='dashboard_p_start_d_4666b6_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['end_date'], name='dashboard_p_end_dat_3af0e5_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_at'], name='dashboard_p_created_a4dc11_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['project'], name='dashboard_p_project_01d698_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='dashboard_p_payment_0bb2bf_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['amount'], name='dashboard_p_amount_68e1af_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='dashboard_p_created_b43229_idx'),
        ),
    ]
