# Generated by Django 4.2.7 on 2026-02-25 02:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contractor",
            name="organization",
        ),
        migrations.RemoveIndex(
            model_name="project",
            name="dashboard_p_contrac_25b544_idx",
        ),
        migrations.RemoveField(
            model_name="project",
            name="contractor",
        ),
        migrations.DeleteModel(
            name="Contractor",
        ),
    ]
