# Generated by Django 4.2.7 on 2026-02-25 02:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_remove_contractor_model"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
