# Generated by Django 5.2.5 on 2026-02-28 19:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_add_rbac_rol_to_invitacion"),
        ("dashboard", "0003_remove_payment_model"),
        ("nomina", "0014_allow_blank_numero_nomina"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActiveProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("single", "Proyecto único"),
                            ("all", "Todos los proyectos"),
                        ],
                        default="all",
                        max_length=10,
                        verbose_name="Modo",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Proyecto Activo",
                "verbose_name_plural": "Proyectos Activos",
            },
        ),
        migrations.CreateModel(
            name="AsignacionProyecto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("lider", "Líder"),
                            ("coordinador", "Coordinador"),
                            ("colaborador", "Colaborador"),
                            ("observador", "Observador"),
                        ],
                        default="colaborador",
                        max_length=20,
                        verbose_name="Rol en el proyecto",
                    ),
                ),
                (
                    "fecha_asignacion",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de asignación",
                    ),
                ),
                (
                    "fecha_desasignacion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de desasignación"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Asignación a Proyecto",
                "verbose_name_plural": "Asignaciones a Proyectos",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="centro_costo",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Centro de costo"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="cliente",
            field=models.CharField(
                blank=True,
                help_text="Empresa o cliente final del proyecto.",
                max_length=200,
                verbose_name="Cliente",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="codigo_proyecto",
            field=models.CharField(
                blank=True,
                help_text="Código único del proyecto, ej: PROJ-2026-001. Se auto-genera si se deja vacío.",
                max_length=30,
                verbose_name="Código",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="color",
            field=models.CharField(
                default="#6366f1",
                help_text="Color hex para la UI, ej: #6366f1",
                max_length=7,
                verbose_name="Color",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proyectos_creados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="estado",
            field=models.CharField(
                choices=[
                    ("planificacion", "Planificación"),
                    ("activo", "Activo"),
                    ("pausado", "Pausado"),
                    ("completado", "Completado"),
                    ("cancelado", "Cancelado"),
                ],
                default="planificacion",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="fecha_real_fin",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha real de finalización"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="icono",
            field=models.CharField(
                blank=True,
                default="briefcase",
                help_text="Slug del ícono (lucide-react)",
                max_length=50,
                verbose_name="Ícono",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="moneda",
            field=models.CharField(
                choices=[
                    ("COP", "Peso Colombiano"),
                    ("USD", "Dólar Estadounidense"),
                    ("EUR", "Euro"),
                ],
                default="COP",
                max_length=3,
                verbose_name="Moneda",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="notas_internas",
            field=models.TextField(blank=True, verbose_name="Notas internas"),
        ),
        migrations.AddField(
            model_name="project",
            name="presupuesto_aprobado",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Presupuesto aprobado",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="presupuesto_estimado",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Presupuesto estimado",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="prioridad",
            field=models.CharField(
                choices=[
                    ("baja", "Baja"),
                    ("media", "Media"),
                    ("alta", "Alta"),
                    ("critica", "Crítica"),
                ],
                default="media",
                max_length=10,
                verbose_name="Prioridad",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="progreso",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Progreso (%)",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="responsable",
            field=models.ForeignKey(
                blank=True,
                help_text="Líder o encargado del proyecto. Por defecto, quien lo crea.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proyectos_responsable",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsable",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de etiquetas flexibles",
                verbose_name="Etiquetas",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de finalización estimada"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Nombre del Proyecto"),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateField(verbose_name="Fecha de inicio"),
        ),
        migrations.AlterField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("organization", "codigo_proyecto")},
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["organization", "estado"], name="dashboard_p_organiz_64cc57_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["codigo_proyecto"], name="dashboard_p_codigo__892ba3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["prioridad"], name="dashboard_p_priorid_3279cb_idx"
            ),
        ),
        migrations.AddField(
            model_name="activeproject",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_selections",
                to="dashboard.project",
                verbose_name="Proyecto activo",
            ),
        ),
        migrations.AddField(
            model_name="activeproject",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="active_project",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AddField(
            model_name="asignacionproyecto",
            name="empleado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asignaciones_proyecto",
                to="nomina.empleado",
                verbose_name="Empleado",
            ),
        ),
        migrations.AddField(
            model_name="asignacionproyecto",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organización a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organizacion",
            ),
        ),
        migrations.AddField(
            model_name="asignacionproyecto",
            name="proyecto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asignaciones",
                to="dashboard.project",
                verbose_name="Proyecto",
            ),
        ),
        migrations.AddIndex(
            model_name="asignacionproyecto",
            index=models.Index(
                fields=["proyecto", "activo"], name="dashboard_a_proyect_d1abac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asignacionproyecto",
            index=models.Index(
                fields=["empleado", "activo"], name="dashboard_a_emplead_4f9ace_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="asignacionproyecto",
            unique_together={("proyecto", "empleado")},
        ),
    ]
