# Generated by Django 5.2.5 on 2026-03-01 15:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_activeproject_asignacionproyecto_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asignacionproyecto",
            name="rol",
        ),
    ]
