# Generated by Django 5.2 on 2025-06-27 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('tipo_cantidad', models.CharField(choices=[('m2', 'Metro cuadrado (m²)'), ('m3', 'Metro cúbico (m³)'), ('ml', 'Metro lineal (ml)'), ('global', 'Global')], default='m2', max_length=10, verbose_name='Tipo de cantidad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Ítem',
                'verbose_name_plural': 'Ítems',
                'ordering': ['name'],
            },
        ),
    ]
