# Generated by Django 5.2 on 2025-06-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tipo_cantidad',
            field=models.CharField(choices=[('m2', 'Metro cuadrado (m²)'), ('global', 'Global'), ('ml', 'Metro lineal (ml)')], default='m2', max_length=10, verbose_name='Tipo de cantidad'),
        ),
    ]
