# Generated by Django 5.2 on 2025-06-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tipo_cantidad',
            field=models.CharField(choices=[('m2', 'Metro cuadrado (m²)'), ('m3', 'Metro cúbico (m³)'), ('ml', 'Metro lineal (ml)'), ('global', 'Global')], default='m2', max_length=10, verbose_name='Tipo de cantidad'),
        ),
    ]
