# Generated by Django 4.2.7 on 2026-01-10 21:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre completo del departamento",
                        max_length=100,
                        verbose_name="Nombre del Departamento",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        blank=True,
                        help_text="Código DANE del departamento",
                        max_length=10,
                        verbose_name="Código",
                    ),
                ),
                (
                    "capital",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Capital"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        help_text="Región geográfica (Andina, Caribe, etc.)",
                        max_length=50,
                        verbose_name="Región",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departamentos",
                        to="core.organizacion",
                        verbose_name="Organización",
                    ),
                ),
            ],
            options={
                "verbose_name": "Departamento",
                "verbose_name_plural": "Departamentos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Municipio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre del Municipio"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        blank=True,
                        help_text="Código DANE del municipio",
                        max_length=10,
                        verbose_name="Código",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="municipios",
                        to="locations.departamento",
                        verbose_name="Departamento",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="municipios",
                        to="core.organizacion",
                        verbose_name="Organización",
                    ),
                ),
            ],
            options={
                "verbose_name": "Municipio",
                "verbose_name_plural": "Municipios",
                "ordering": ["departamento__nombre", "nombre"],
                "indexes": [
                    models.Index(
                        fields=["departamento", "nombre"],
                        name="locations_m_departa_08534c_idx",
                    ),
                    models.Index(
                        fields=["codigo"], name="locations_m_codigo_f321c5_idx"
                    ),
                ],
                "unique_together": {
                    ("organization", "departamento", "codigo"),
                    ("departamento", "nombre"),
                },
            },
        ),
        migrations.AddIndex(
            model_name="departamento",
            index=models.Index(fields=["codigo"], name="locations_d_codigo_4aabc1_idx"),
        ),
        migrations.AddIndex(
            model_name="departamento",
            index=models.Index(fields=["nombre"], name="locations_d_nombre_96bb2f_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="departamento",
            unique_together={("organization", "nombre")},
        ),
    ]
