# Generated by Django 4.2.7 on 2026-02-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="departamento",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="municipio",
            unique_together={("departamento", "nombre")},
        ),
        migrations.AlterField(
            model_name="departamento",
            name="nombre",
            field=models.CharField(
                help_text="Nombre completo del departamento",
                max_length=100,
                unique=True,
                verbose_name="Nombre del Departamento",
            ),
        ),
        migrations.RemoveField(
            model_name="departamento",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="municipio",
            name="organization",
        ),
    ]
