# Generated by Django 5.2 on 2025-06-30 02:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlujoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('tipo_movimiento', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10, verbose_name='Tipo de movimiento')),
                ('concepto', models.CharField(max_length=200, verbose_name='Concepto')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Flujo de Caja',
                'verbose_name_plural': 'Flujo de Caja',
                'ordering': ['-fecha', 'tipo_movimiento'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción del movimiento')),
                ('valor_debito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor débito')),
                ('valor_credito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor crédito')),
                ('tercero', models.CharField(blank=True, help_text='Identificación o nombre del tercero', max_length=200, null=True, verbose_name='Tercero')),
                ('centro_costo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Centro de costo')),
            ],
            options={
                'verbose_name': 'Movimiento Contable',
                'verbose_name_plural': 'Movimientos Contables',
                'ordering': ['comprobante', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlanCuentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único de la cuenta contable', max_length=20, unique=True, verbose_name='Código de cuenta')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la cuenta')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('nivel', models.PositiveIntegerField(default=1, help_text='Nivel en la jerarquía del plan de cuentas', verbose_name='Nivel')),
                ('tipo_cuenta', models.CharField(choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('patrimonio', 'Patrimonio'), ('ingreso', 'Ingreso'), ('gasto', 'Gasto'), ('costo', 'Costo')], max_length=20, verbose_name='Tipo de cuenta')),
                ('naturaleza', models.CharField(choices=[('debito', 'Débito'), ('credito', 'Crédito')], max_length=10, verbose_name='Naturaleza de la cuenta')),
                ('acepta_movimientos', models.BooleanField(default=True, help_text='Si la cuenta acepta movimientos directos', verbose_name='Acepta movimientos')),
                ('requiere_tercero', models.BooleanField(default=False, help_text='Si los movimientos requieren especificar tercero', verbose_name='Requiere tercero')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Plan de Cuentas',
                'verbose_name_plural': 'Plan de Cuentas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ComprobanteContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número de comprobante')),
                ('tipo_comprobante', models.CharField(choices=[('diario', 'Diario'), ('ingreso', 'Ingreso'), ('egreso', 'Egreso'), ('nomina', 'Nómina'), ('ajuste', 'Ajuste'), ('cierre', 'Cierre')], max_length=20, verbose_name='Tipo de comprobante')),
                ('fecha', models.DateField(verbose_name='Fecha del comprobante')),
                ('descripcion', models.TextField(help_text='Descripción general del comprobante', verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('contabilizado', 'Contabilizado'), ('anulado', 'Anulado')], default='borrador', max_length=20, verbose_name='Estado')),
                ('total_debito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total débito')),
                ('total_credito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total crédito')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_contabilizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de contabilización')),
                ('contabilizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes_contabilizados', to=settings.AUTH_USER_MODEL, verbose_name='Contabilizado por')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('nomina_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes_contables', to='payroll.nomina', verbose_name='Nómina relacionada')),
            ],
            options={
                'verbose_name': 'Comprobante Contable',
                'verbose_name_plural': 'Comprobantes Contables',
                'ordering': ['-fecha', '-numero'],
            },
        ),
    ]
