# Generated by Django 5.2 on 2025-08-22 01:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceComprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(help_text='Período en formato YYYY-MM', max_length=7, verbose_name='Período')),
                ('saldo_inicial_debito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Saldo inicial débito')),
                ('saldo_inicial_credito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Saldo inicial crédito')),
                ('movimiento_debito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Movimientos débito')),
                ('movimiento_credito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Movimientos crédito')),
                ('saldo_final_debito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Saldo final débito')),
                ('saldo_final_credito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Saldo final crédito')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de generación')),
            ],
            options={
                'verbose_name': 'Balance de Comprobación',
                'verbose_name_plural': 'Balances de Comprobación',
                'ordering': ['periodo', 'cuenta__codigo'],
            },
        ),
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del centro de costo', max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del centro de costo', max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del centro de costo', null=True, verbose_name='Descripción')),
                ('nivel', models.PositiveIntegerField(default=1, help_text='Nivel en la jerarquía de centros de costo', verbose_name='Nivel')),
                ('presupuesto_anual', models.DecimalField(blank=True, decimal_places=2, help_text='Presupuesto anual asignado al centro de costo', max_digits=15, null=True, verbose_name='Presupuesto anual')),
                ('activo', models.BooleanField(default=True, help_text='Si el centro de costo está activo', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Centro de Costo',
                'verbose_name_plural': 'Centros de Costo',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ComprobanteContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número de comprobante')),
                ('tipo_comprobante', models.CharField(choices=[('diario', 'Diario'), ('ingreso', 'Ingreso'), ('egreso', 'Egreso'), ('nomina', 'Nómina'), ('ajuste', 'Ajuste'), ('cierre', 'Cierre')], max_length=20, verbose_name='Tipo de comprobante')),
                ('fecha', models.DateField(verbose_name='Fecha del comprobante')),
                ('descripcion', models.TextField(help_text='Descripción general del comprobante', verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('contabilizado', 'Contabilizado'), ('anulado', 'Anulado')], default='borrador', max_length=20, verbose_name='Estado')),
                ('total_debito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total débito')),
                ('total_credito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total crédito')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_contabilizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de contabilización')),
            ],
            options={
                'verbose_name': 'Comprobante Contable',
                'verbose_name_plural': 'Comprobantes Contables',
                'ordering': ['-fecha', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='FlujoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('tipo_movimiento', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10, verbose_name='Tipo de movimiento')),
                ('concepto', models.CharField(max_length=200, verbose_name='Concepto')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Flujo de Caja',
                'verbose_name_plural': 'Flujo de Caja',
                'ordering': ['-fecha', 'tipo_movimiento'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción del movimiento')),
                ('valor_debito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor débito')),
                ('valor_credito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor crédito')),
                ('tercero', models.CharField(blank=True, help_text='Identificación o nombre del tercero', max_length=200, null=True, verbose_name='Tercero')),
                ('centro_costo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Centro de costo')),
            ],
            options={
                'verbose_name': 'Movimiento Contable',
                'verbose_name_plural': 'Movimientos Contables',
                'ordering': ['comprobante', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlanCuentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único de la cuenta contable', max_length=20, unique=True, verbose_name='Código de cuenta')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la cuenta')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('nivel', models.PositiveIntegerField(default=1, help_text='Nivel en la jerarquía del plan de cuentas', verbose_name='Nivel')),
                ('tipo_cuenta', models.CharField(choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('patrimonio', 'Patrimonio'), ('ingreso', 'Ingreso'), ('gasto', 'Gasto'), ('costo', 'Costo')], max_length=20, verbose_name='Tipo de cuenta')),
                ('naturaleza', models.CharField(choices=[('debito', 'Débito'), ('credito', 'Crédito')], max_length=10, verbose_name='Naturaleza de la cuenta')),
                ('acepta_movimientos', models.BooleanField(default=True, help_text='Si la cuenta acepta movimientos directos', verbose_name='Acepta movimientos')),
                ('requiere_tercero', models.BooleanField(default=False, help_text='Si los movimientos requieren especificar tercero', verbose_name='Requiere tercero')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Plan de Cuentas',
                'verbose_name_plural': 'Plan de Cuentas',
                'ordering': ['codigo'],
            },
        ),
    ]
