# Generated by Django 5.2 on 2025-08-22 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancecomprobacion',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organización a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organizacion'),
        ),
        migrations.AddField(
            model_name='centrocosto',
            name='centro_padre',
            field=models.ForeignKey(blank=True, help_text='Centro de costo padre en la jerarquía', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcentros', to='contabilidad.centrocosto', verbose_name='Centro padre'),
        ),
        migrations.AddField(
            model_name='centrocosto',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organización a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organizacion'),
        ),
    ]
