# Generated by Django 4.2.7 on 2026-01-03 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("prestamos", "0001_initial"),
        ("core", "0004_alter_logauditoria_objeto_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contabilidad", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comprobantecontable",
            name="prestamo_relacionado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comprobantes_contables",
                to="prestamos.prestamo",
                verbose_name="Préstamo relacionado",
            ),
        ),
        migrations.AddField(
            model_name="centrocosto",
            name="centro_padre",
            field=models.ForeignKey(
                blank=True,
                help_text="Centro de costo padre en la jerarquía",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcentros",
                to="contabilidad.centrocosto",
                verbose_name="Centro padre",
            ),
        ),
        migrations.AddField(
            model_name="centrocosto",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organización a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organizacion",
            ),
        ),
        migrations.AddField(
            model_name="centrocosto",
            name="responsable",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario responsable del centro de costo",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsable",
            ),
        ),
        migrations.AddField(
            model_name="balancecomprobacion",
            name="cuenta",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="contabilidad.plancuentas",
                verbose_name="Cuenta",
            ),
        ),
        migrations.AddField(
            model_name="balancecomprobacion",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organización a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organizacion",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="balancecomprobacion",
            unique_together={("periodo", "cuenta")},
        ),
    ]
