# Generated by Django 4.2.7 on 2026-01-10 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contabilidad", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plancuentas",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organización a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organizacion",
            ),
        ),
        migrations.AddField(
            model_name="movimientocontable",
            name="comprobante",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movimientos",
                to="contabilidad.comprobantecontable",
                verbose_name="Comprobante",
            ),
        ),
        migrations.AddField(
            model_name="movimientocontable",
            name="cuenta",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movimientos",
                to="contabilidad.plancuentas",
                verbose_name="Cuenta",
            ),
        ),
        migrations.AddField(
            model_name="movimientocontable",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organización a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organizacion",
            ),
        ),
        migrations.AddField(
            model_name="flujocaja",
            name="comprobante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movimientos_flujo",
                to="contabilidad.comprobantecontable",
                verbose_name="Comprobante relacionado",
            ),
        ),
        migrations.AddField(
            model_name="flujocaja",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organización a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organizacion",
            ),
        ),
    ]
