# Generated by Django 5.2 on 2025-08-22 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad', '0002_initial'),
        ('core', '0001_initial'),
        ('payroll', '0001_initial'),
        ('prestamos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='centrocosto',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text='Usuario responsable del centro de costo', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='comprobantecontable',
            name='contabilizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes_contabilizados', to=settings.AUTH_USER_MODEL, verbose_name='Contabilizado por'),
        ),
        migrations.AddField(
            model_name='comprobantecontable',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='comprobantecontable',
            name='nomina_relacionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes_contables', to='payroll.nomina', verbose_name='Nómina relacionada'),
        ),
        migrations.AddField(
            model_name='comprobantecontable',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organización a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organizacion'),
        ),
        migrations.AddField(
            model_name='comprobantecontable',
            name='prestamo_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes_contables', to='prestamos.prestamo', verbose_name='Préstamo relacionado'),
        ),
        migrations.AddField(
            model_name='flujocaja',
            name='comprobante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_flujo', to='contabilidad.comprobantecontable', verbose_name='Comprobante relacionado'),
        ),
        migrations.AddField(
            model_name='flujocaja',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organización a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organizacion'),
        ),
        migrations.AddField(
            model_name='movimientocontable',
            name='comprobante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='contabilidad.comprobantecontable', verbose_name='Comprobante'),
        ),
        migrations.AddField(
            model_name='movimientocontable',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organización a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organizacion'),
        ),
        migrations.AddField(
            model_name='plancuentas',
            name='cuenta_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcuentas', to='contabilidad.plancuentas', verbose_name='Cuenta padre'),
        ),
        migrations.AddField(
            model_name='plancuentas',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organización a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organizacion'),
        ),
        migrations.AddField(
            model_name='movimientocontable',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='contabilidad.plancuentas', verbose_name='Cuenta'),
        ),
        migrations.AddField(
            model_name='balancecomprobacion',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.plancuentas', verbose_name='Cuenta'),
        ),
        migrations.AlterUniqueTogether(
            name='balancecomprobacion',
            unique_together={('periodo', 'cuenta')},
        ),
    ]
