# Generated by Django 4.2.7 on 2026-01-10 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0004_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movimientocontable",
            name="centro_costo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movimientos",
                to="contabilidad.centrocosto",
                verbose_name="Centro de costo",
            ),
        ),
    ]
