# Generated by Django 5.2.5 on 2026-02-28 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contabilidad", "0005_alter_movimiento_centro_costo_fk"),
        ("dashboard", "0003_remove_payment_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="comprobantecontable",
            name="proyecto",
            field=models.ForeignKey(
                blank=True,
                help_text="Proyecto al que pertenece este comprobante",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comprobantes",
                to="dashboard.project",
                verbose_name="Proyecto",
            ),
        ),
        migrations.AddField(
            model_name="flujocaja",
            name="proyecto",
            field=models.ForeignKey(
                blank=True,
                help_text="Proyecto al que pertenece este movimiento",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flujos_caja",
                to="dashboard.project",
                verbose_name="Proyecto",
            ),
        ),
    ]
