# Generated by Django 4.2.7 on 2026-03-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_add_rbac_rol_to_invitacion"),
        ("contabilidad", "0006_comprobantecontable_proyecto_flujocaja_proyecto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="centrocosto",
            name="codigo",
            field=models.CharField(
                help_text="Código único del centro de costo",
                max_length=20,
                verbose_name="Código",
            ),
        ),
        migrations.AlterField(
            model_name="comprobantecontable",
            name="numero",
            field=models.CharField(max_length=20, verbose_name="Número de comprobante"),
        ),
        migrations.AlterField(
            model_name="plancuentas",
            name="codigo",
            field=models.CharField(
                help_text="Código único de la cuenta contable",
                max_length=20,
                verbose_name="Código de cuenta",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="centrocosto",
            unique_together={("organization", "codigo")},
        ),
        migrations.AlterUniqueTogether(
            name="comprobantecontable",
            unique_together={("organization", "numero")},
        ),
        migrations.AlterUniqueTogether(
            name="plancuentas",
            unique_together={("organization", "codigo")},
        ),
    ]
