# Generated by Django 4.2.7 on 2026-01-03 20:13

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0004_alter_logauditoria_objeto_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("locations", "0001_initial"),
        ("items", "0001_initial"),
        ("cargos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                ("documento", models.CharField(max_length=20, unique=True)),
                ("correo", models.EmailField(blank=True, max_length=254)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("direccion", models.TextField(blank=True)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                (
                    "genero",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                        default="M",
                        max_length=1,
                    ),
                ),
                ("fecha_ingreso", models.DateField(blank=True, null=True)),
                (
                    "ibc_default",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="IBC por defecto para cálculo de seguridad social (típicamente 1 SMMLV para subcontratistas)",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="empleados/"),
                ),
                ("activo", models.BooleanField(default=True)),
                ("creado_el", models.DateTimeField(auto_now_add=True)),
                ("actualizado_el", models.DateTimeField(auto_now=True)),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cargos.cargo"
                    ),
                ),
                (
                    "departamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locations.departamento",
                    ),
                ),
                (
                    "municipio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locations.municipio",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organización a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organizacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empleado",
                "verbose_name_plural": "Empleados",
                "ordering": ["apellidos", "nombres"],
            },
        ),
        migrations.CreateModel(
            name="TipoContrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        choices=[
                            ("IND", "Indefinido"),
                            ("FIJ", "Término Fijo"),
                            ("OBR", "Obra o Labor"),
                            ("APR", "Aprendizaje"),
                            ("PSE", "Prestación de Servicios"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "requiere_fecha_fin",
                    models.BooleanField(
                        default=False,
                        help_text="Si el contrato requiere fecha de finalización",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tipo de Contrato",
                "verbose_name_plural": "Tipos de Contrato",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="TipoDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        choices=[
                            ("CC", "Cédula de Ciudadanía"),
                            ("CE", "Cédula de Extranjería"),
                            ("TI", "Tarjeta de Identidad"),
                            ("PA", "Pasaporte"),
                            ("RC", "Registro Civil"),
                            ("NIT", "NIT"),
                            ("DIE", "Documento de Identificación Extranjero"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tipo de Documento",
                "verbose_name_plural": "Tipos de Documento",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="TipoTrabajador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        choices=[
                            ("DEP", "Dependiente"),
                            ("APR", "Aprendiz"),
                            ("PEN", "Pensionado"),
                            ("SUB", "Subcontratista"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "requiere_nomina_electronica",
                    models.BooleanField(
                        default=True,
                        help_text="Si requiere generación de nómina electrónica DIAN",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tipo de Trabajador",
                "verbose_name_plural": "Tipos de Trabajador",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="WebhookConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("url", models.URLField()),
                ("secret", models.CharField(blank=True, max_length=200)),
                ("activo", models.BooleanField(default=True)),
                (
                    "eventos",
                    models.JSONField(
                        default=list, help_text="Lista de eventos suscritos"
                    ),
                ),
                ("reintentos_maximos", models.IntegerField(default=3)),
                ("timeout_segundos", models.IntegerField(default=10)),
                ("total_disparos", models.IntegerField(default=0)),
                ("total_exitosos", models.IntegerField(default=0)),
                ("total_fallidos", models.IntegerField(default=0)),
                ("ultimo_disparo", models.DateTimeField(blank=True, null=True)),
                (
                    "ultimo_estado",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("exito", "Éxito"),
                            ("error", "Error"),
                            ("timeout", "Timeout"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organización a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organizacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook",
                "verbose_name_plural": "Webhooks",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="PeriodoNomina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("MEN", "Mensual"),
                            ("QUI", "Quincenal"),
                            ("SEM", "Semanal"),
                        ],
                        default="MEN",
                        max_length=3,
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("fecha_pago", models.DateField()),
                ("fecha_pago_real", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ABI", "Abierto"),
                            ("CER", "Cerrado"),
                            ("PAG", "Pagado"),
                            ("APR", "Aprobado"),
                        ],
                        default="ABI",
                        max_length=3,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("creado_el", models.DateTimeField(auto_now_add=True)),
                ("actualizado_el", models.DateTimeField(auto_now=True)),
                ("fecha_cierre", models.DateTimeField(blank=True, null=True)),
                (
                    "cerrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="periodos_cerrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organización a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organizacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Periodo de Nómina",
                "verbose_name_plural": "Periodos de Nómina",
                "ordering": ["-fecha_inicio"],
                "unique_together": {("organization", "fecha_inicio", "fecha_fin")},
            },
        ),
        migrations.CreateModel(
            name="NominaSimple",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periodo_inicio", models.DateField()),
                ("periodo_fin", models.DateField()),
                ("dias_trabajados", models.PositiveIntegerField(default=0)),
                (
                    "total_items",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Suma total de todos los items trabajados",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "salario_base_contrato",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Salario base del contrato (usado para seguridad social)",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "base_cotizacion",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="IBC = Salario base del contrato (tope 25 SMMLV)",
                        max_digits=12,
                    ),
                ),
                (
                    "excedente_no_salarial",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Excedente sobre 25 SMMLV (no cotiza)",
                        max_digits=12,
                    ),
                ),
                (
                    "aporte_salud_empleado",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "aporte_pension_empleado",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "aporte_salud_empleador",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "aporte_pension_empleador",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "aporte_arl",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "aporte_sena",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "aporte_icbf",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "aporte_caja_compensacion",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "provision_cesantias",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "provision_intereses_cesantias",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "provision_prima",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "provision_vacaciones",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "deduccion_prestamos",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "deduccion_restaurante",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "deduccion_anticipos",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "otras_deducciones",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_deducciones",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "neto_pagar",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="total_items - total_deducciones",
                        max_digits=12,
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("observaciones", models.TextField(blank=True)),
                ("numero_interno", models.CharField(max_length=50, unique=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BOR", "Borrador"),
                            ("REV", "En Revisión"),
                            ("APR", "Aprobada"),
                            ("PAG", "Pagada"),
                            ("ANU", "Anulada"),
                        ],
                        default="BOR",
                        max_length=3,
                    ),
                ),
                ("fecha_aprobacion", models.DateTimeField(blank=True, null=True)),
                ("fecha_pago", models.DateField(blank=True, null=True)),
                ("comprobante_pago", models.CharField(blank=True, max_length=100)),
                (
                    "aprobada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nominas_simples_aprobadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payroll.empleado",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organización a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organizacion",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payroll.periodonomina",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nómina Simple (RRHH)",
                "verbose_name_plural": "Nóminas Simples (RRHH)",
                "ordering": ["-fecha_creacion"],
                "unique_together": {("organization", "empleado", "periodo")},
            },
        ),
        migrations.CreateModel(
            name="NominaElectronica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periodo_inicio", models.DateField()),
                ("periodo_fin", models.DateField()),
                ("dias_trabajados", models.PositiveIntegerField(default=0)),
                (
                    "total_items",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Suma total de todos los items trabajados",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "salario_base_contrato",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Salario base del contrato (usado para seguridad social)",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "base_cotizacion",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="IBC = Salario base del contrato (tope 25 SMMLV)",
                        max_digits=12,
                    ),
                ),
                (
                    "excedente_no_salarial",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Excedente sobre 25 SMMLV (no cotiza)",
                        max_digits=12,
                    ),
                ),
                (
                    "aporte_salud_empleado",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "aporte_pension_empleado",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "aporte_salud_empleador",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "aporte_pension_empleador",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "aporte_arl",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "aporte_sena",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "aporte_icbf",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "aporte_caja_compensacion",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "provision_cesantias",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "provision_intereses_cesantias",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "provision_prima",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "provision_vacaciones",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "deduccion_prestamos",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "deduccion_restaurante",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "deduccion_anticipos",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "otras_deducciones",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_deducciones",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "neto_pagar",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="total_items - total_deducciones",
                        max_digits=12,
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("observaciones", models.TextField(blank=True)),
                ("numero_documento", models.CharField(max_length=50, unique=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("validado", "Validado"),
                            ("enviado", "Enviado a DIAN"),
                            ("aceptado", "Aceptado por DIAN"),
                            ("rechazado", "Rechazado por DIAN"),
                            ("anulado", "Anulado"),
                        ],
                        default="borrador",
                        max_length=20,
                    ),
                ),
                ("cune", models.CharField(blank=True, max_length=255)),
                ("xml_contenido", models.TextField(blank=True)),
                ("codigo_respuesta_dian", models.CharField(blank=True, max_length=20)),
                ("mensaje_respuesta_dian", models.TextField(blank=True)),
                ("fecha_envio_dian", models.DateTimeField(blank=True, null=True)),
                ("fecha_respuesta_dian", models.DateTimeField(blank=True, null=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payroll.empleado",
                    ),
                ),
                (
                    "nomina_simple",
                    models.OneToOneField(
                        blank=True,
                        help_text="Nómina simple asociada (opcional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nomina_electronica",
                        to="payroll.nominasimple",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organización a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organizacion",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payroll.periodonomina",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nómina Electrónica (DIAN)",
                "verbose_name_plural": "Nóminas Electrónicas (DIAN)",
                "ordering": ["-fecha_creacion"],
                "unique_together": {("organization", "empleado", "periodo")},
            },
        ),
        migrations.AddField(
            model_name="empleado",
            name="tipo_documento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="payroll.tipodocumento",
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="tipo_vinculacion",
            field=models.ForeignKey(
                blank=True,
                help_text="Tipo de vinculación laboral",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="payroll.tipotrabajador",
            ),
        ),
        migrations.CreateModel(
            name="DetalleItemNominaSimple",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="items.item"
                    ),
                ),
                (
                    "nomina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles_items",
                        to="payroll.nominasimple",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organización a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organizacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle Item Nómina Simple",
                "verbose_name_plural": "Detalles Items Nómina Simple",
                "ordering": ["item__nombre"],
            },
        ),
        migrations.CreateModel(
            name="DetalleItemNominaElectronica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("codigo_dian", models.CharField(blank=True, max_length=10)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="items.item"
                    ),
                ),
                (
                    "nomina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles_items",
                        to="payroll.nominaelectronica",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organización a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organizacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle Item Nómina Electrónica",
                "verbose_name_plural": "Detalles Items Nómina Electrónica",
                "ordering": ["item__nombre"],
            },
        ),
        migrations.CreateModel(
            name="Contrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_salario",
                    models.CharField(
                        choices=[("ORD", "Ordinario"), ("INT", "Integral")],
                        default="ORD",
                        max_length=3,
                    ),
                ),
                (
                    "salario_base",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Salario base mensual del contrato",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "jornada",
                    models.CharField(
                        choices=[
                            ("DIU", "Diurna"),
                            ("NOC", "Nocturna"),
                            ("MIX", "Mixta"),
                        ],
                        default="DIU",
                        max_length=3,
                    ),
                ),
                ("auxilio_transporte", models.BooleanField(default=True)),
                (
                    "nivel_riesgo_arl",
                    models.IntegerField(
                        choices=[
                            (1, "Nivel I - Riesgo Mínimo"),
                            (2, "Nivel II - Riesgo Bajo"),
                            (3, "Nivel III - Riesgo Medio"),
                            (4, "Nivel IV - Riesgo Alto"),
                            (5, "Nivel V - Riesgo Máximo"),
                        ],
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ACT", "Activo"),
                            ("SUS", "Suspendido"),
                            ("TER", "Terminado"),
                        ],
                        default="ACT",
                        max_length=3,
                    ),
                ),
                ("motivo_terminacion", models.TextField(blank=True)),
                ("fecha_terminacion_real", models.DateField(blank=True, null=True)),
                ("creado_el", models.DateTimeField(auto_now_add=True)),
                ("actualizado_el", models.DateTimeField(auto_now=True)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contratos",
                        to="payroll.empleado",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organización a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organizacion",
                    ),
                ),
                (
                    "tipo_contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payroll.tipocontrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrato",
                "verbose_name_plural": "Contratos",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="WebhookLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("evento", models.CharField(max_length=50)),
                ("payload", models.JSONField()),
                ("codigo_respuesta", models.IntegerField(blank=True, null=True)),
                ("respuesta", models.TextField(blank=True)),
                ("exitoso", models.BooleanField(default=False)),
                ("error", models.TextField(blank=True)),
                ("tiempo_respuesta", models.FloatField(blank=True, null=True)),
                ("fecha_disparo", models.DateTimeField(auto_now_add=True)),
                (
                    "webhook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="payroll.webhookconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Webhook",
                "verbose_name_plural": "Logs de Webhooks",
                "ordering": ["-fecha_disparo"],
                "indexes": [
                    models.Index(
                        fields=["-fecha_disparo"], name="payroll_web_fecha_d_135131_idx"
                    ),
                    models.Index(
                        fields=["webhook", "-fecha_disparo"],
                        name="payroll_web_webhook_2bad11_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConfiguracionNominaElectronica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                (
                    "ambiente",
                    models.CharField(
                        choices=[
                            ("pruebas", "Ambiente de Pruebas"),
                            ("produccion", "Ambiente de Producción"),
                        ],
                        default="pruebas",
                        max_length=20,
                    ),
                ),
                ("razon_social", models.CharField(max_length=200)),
                ("nit", models.CharField(max_length=20)),
                ("dv", models.CharField(max_length=1)),
                ("direccion", models.CharField(max_length=200)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("prefijo", models.CharField(blank=True, max_length=10)),
                ("resolucion_numero", models.CharField(blank=True, max_length=50)),
                ("resolucion_fecha", models.DateField(blank=True, null=True)),
                ("rango_inicio", models.BigIntegerField(blank=True, null=True)),
                ("rango_fin", models.BigIntegerField(blank=True, null=True)),
                ("consecutivo_actual", models.BigIntegerField(default=1)),
                (
                    "certificado_archivo",
                    models.FileField(
                        blank=True, null=True, upload_to="certificados_digitales/"
                    ),
                ),
                ("certificado_password", models.CharField(blank=True, max_length=200)),
                (
                    "identificador_software",
                    models.CharField(blank=True, max_length=100),
                ),
                ("clave_tecnica", models.CharField(blank=True, max_length=100)),
                ("url_webservice", models.URLField(blank=True)),
                ("url_recepcion", models.URLField(blank=True)),
                ("envio_automatico", models.BooleanField(default=False)),
                ("notificar_empleado", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organización a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organizacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración Nómina Electrónica",
                "verbose_name_plural": "Configuraciones Nómina Electrónica",
                "unique_together": {("organization", "activa")},
            },
        ),
    ]
