# Generated by Django 5.2 on 2025-06-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de contratación'),
        ),
    ]
