# Generated by Django 5.2.5 on 2026-01-08 03:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_logauditoria_objeto_id"),
        ("payroll", "0002_conceptolaboral_detalleconceptonominasimple_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AsientoNomina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_comprobante",
                    models.CharField(
                        help_text="Número único del comprobante contable",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "fecha_asiento",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Fecha del asiento contable",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        help_text="Descripción del asiento (generada automáticamente)"
                    ),
                ),
                (
                    "total_debitos",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Suma total de débitos",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "total_creditos",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Suma total de créditos",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "diferencia",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        help_text="Diferencia (debe ser 0.00 para cuadrar)",
                        max_digits=15,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BOR", "Borrador"),
                            ("CON", "Contabilizado"),
                            ("ANU", "Anulado"),
                        ],
                        default="BOR",
                        help_text="Estado del asiento",
                        max_length=3,
                    ),
                ),
                (
                    "cuadrado",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        help_text="True si débitos == créditos",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("fecha_contabilizacion", models.DateTimeField(blank=True, null=True)),
                (
                    "contabilizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asientos_nomina_contabilizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asientos_nomina_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nomina_electronica",
                    models.OneToOneField(
                        blank=True,
                        help_text="Nómina electrónica asociada",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asiento_contable",
                        to="payroll.nominaelectronica",
                    ),
                ),
                (
                    "nomina_simple",
                    models.OneToOneField(
                        blank=True,
                        help_text="Nómina simple asociada",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asiento_contable",
                        to="payroll.nominasimple",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organización a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organizacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asiento Contable de Nómina",
                "verbose_name_plural": "Asientos Contables de Nómina",
                "ordering": ["-fecha_asiento", "-numero_comprobante"],
            },
        ),
        migrations.CreateModel(
            name="CentroCosto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        help_text="Código único del centro de costo (ej: PRO-001, OBR-A, FAS-CIM)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre descriptivo del centro de costo",
                        max_length=200,
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Descripción detallada, alcance, ubicación",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PRO", "Proyecto"),
                            ("OBR", "Obra"),
                            ("FAS", "Fase"),
                            ("ACT", "Actividad"),
                            ("OTR", "Otro"),
                        ],
                        default="OBR",
                        help_text="Tipo de centro de costo",
                        max_length=3,
                    ),
                ),
                (
                    "nivel",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Nivel en la jerarquía (0=raíz, 1=hijo, 2=nieto...)",
                    ),
                ),
                (
                    "ruta_completa",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Ruta completa desde la raíz (ej: PRO-001/OBR-A/FAS-CIM)",
                        max_length=500,
                    ),
                ),
                (
                    "presupuesto_mano_obra",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Presupuesto total de mano de obra para este centro de costo",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "costo_acumulado_mano_obra",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Costo real acumulado de mano de obra (actualizado automáticamente)",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "ciudad",
                    models.CharField(
                        blank=True,
                        help_text="Ciudad donde se ejecuta la obra",
                        max_length=100,
                    ),
                ),
                (
                    "direccion",
                    models.TextField(
                        blank=True, help_text="Dirección física del proyecto/obra"
                    ),
                ),
                (
                    "fecha_inicio_planificada",
                    models.DateField(
                        blank=True, help_text="Fecha de inicio planificada", null=True
                    ),
                ),
                (
                    "fecha_fin_planificada",
                    models.DateField(
                        blank=True, help_text="Fecha de fin planificada", null=True
                    ),
                ),
                (
                    "fecha_inicio_real",
                    models.DateField(
                        blank=True, help_text="Fecha de inicio real", null=True
                    ),
                ),
                (
                    "fecha_fin_real",
                    models.DateField(
                        blank=True, help_text="Fecha de cierre real", null=True
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PLN", "Planificado"),
                            ("ACT", "Activo"),
                            ("SUS", "Suspendido"),
                            ("CER", "Cerrado"),
                            ("LIQ", "Liquidado"),
                        ],
                        default="PLN",
                        help_text="Estado actual del centro de costo",
                        max_length=3,
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Si está activo, se puede asignar mano de obra",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="centros_costo_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "director_obra",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario responsable del centro de costo",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="centros_costo_dirigidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organización a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organizacion",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Centro de costo padre (para estructura jerárquica)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hijos",
                        to="payroll.centrocosto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Centro de Costo",
                "verbose_name_plural": "Centros de Costo",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="DistribucionCostoNomina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "porcentaje_tiempo",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Porcentaje de tiempo trabajado en este centro de costo (0.01 - 100.00)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "dias_trabajados",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Días trabajados en este centro de costo",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "valor_devengados",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Devengados imputados a este centro de costo",
                        max_digits=12,
                    ),
                ),
                (
                    "valor_salud_empleador",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Aporte salud empleador imputado",
                        max_digits=12,
                    ),
                ),
                (
                    "valor_pension_empleador",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Aporte pensión empleador imputado",
                        max_digits=12,
                    ),
                ),
                (
                    "valor_arl",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Aporte ARL imputado",
                        max_digits=12,
                    ),
                ),
                (
                    "valor_sena",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Aporte SENA imputado",
                        max_digits=12,
                    ),
                ),
                (
                    "valor_icbf",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Aporte ICBF imputado",
                        max_digits=12,
                    ),
                ),
                (
                    "valor_caja_compensacion",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Aporte Caja Compensación imputado",
                        max_digits=12,
                    ),
                ),
                (
                    "valor_cesantias",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Provisión cesantías imputada",
                        max_digits=12,
                    ),
                ),
                (
                    "valor_intereses_cesantias",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Provisión intereses cesantías imputada",
                        max_digits=12,
                    ),
                ),
                (
                    "valor_prima",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Provisión prima imputada",
                        max_digits=12,
                    ),
                ),
                (
                    "valor_vacaciones",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Provisión vacaciones imputada",
                        max_digits=12,
                    ),
                ),
                (
                    "valor_total_imputado",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Costo total imputado (devengados + cargas patronales)",
                        max_digits=12,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "centro_costo",
                    models.ForeignKey(
                        help_text="Centro de costo al que se imputa el costo",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="distribuciones",
                        to="payroll.centrocosto",
                    ),
                ),
                (
                    "nomina_electronica",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nómina electrónica asociada",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distribuciones_costo",
                        to="payroll.nominaelectronica",
                    ),
                ),
                (
                    "nomina_simple",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nómina simple asociada",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distribuciones_costo",
                        to="payroll.nominasimple",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organización a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organizacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Distribución de Costo de Nómina",
                "verbose_name_plural": "Distribuciones de Costo de Nómina",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="EntidadExterna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_entidad",
                    models.CharField(
                        choices=[
                            ("EPS", "EPS - Entidad Promotora de Salud"),
                            ("AFP", "AFP - Fondo de Pensión"),
                            ("ARL", "ARL - Aseguradora de Riesgos Laborales"),
                            ("CCF", "CCF - Caja de Compensación Familiar"),
                            ("BAN", "Banco"),
                            ("COO", "Cooperativa"),
                            ("JUZ", "Juzgado"),
                            ("GOB", "Entidad Gubernamental (ICBF, SENA, etc.)"),
                            ("OTR", "Otra"),
                        ],
                        help_text="Tipo de entidad",
                        max_length=3,
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        help_text="Código único interno (ej: EPS001, AFP002)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "razon_social",
                    models.CharField(help_text="Razón social completa", max_length=250),
                ),
                (
                    "nombre_comercial",
                    models.CharField(
                        blank=True, help_text="Nombre comercial o sigla", max_length=200
                    ),
                ),
                (
                    "nit",
                    models.CharField(
                        db_index=True,
                        help_text="NIT sin dígito de verificación",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "digito_verificacion",
                    models.CharField(
                        help_text="Dígito de verificación del NIT", max_length=1
                    ),
                ),
                (
                    "codigo_superintendencia",
                    models.CharField(
                        blank=True,
                        help_text="Código ante Superintendencia (Salud/Financiera)",
                        max_length=20,
                    ),
                ),
                (
                    "codigo_pila",
                    models.CharField(
                        blank=True, help_text="Código para archivo PILA", max_length=20
                    ),
                ),
                (
                    "direccion",
                    models.TextField(blank=True, help_text="Dirección física"),
                ),
                ("ciudad", models.CharField(blank=True, max_length=100)),
                ("telefono", models.CharField(blank=True, max_length=50)),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email principal de contacto",
                        max_length=254,
                    ),
                ),
                ("sitio_web", models.URLField(blank=True, help_text="Sitio web")),
                (
                    "banco",
                    models.CharField(
                        blank=True, help_text="Banco donde recibe pagos", max_length=100
                    ),
                ),
                (
                    "tipo_cuenta",
                    models.CharField(
                        blank=True,
                        choices=[("AHO", "Ahorros"), ("COR", "Corriente")],
                        help_text="Tipo de cuenta bancaria",
                        max_length=20,
                    ),
                ),
                (
                    "numero_cuenta",
                    models.CharField(
                        blank=True, help_text="Número de cuenta bancaria", max_length=50
                    ),
                ),
                (
                    "aplica_para_pila",
                    models.BooleanField(
                        default=False, help_text="Si debe incluirse en la planilla PILA"
                    ),
                ),
                (
                    "nombre_contacto",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del contacto principal",
                        max_length=200,
                    ),
                ),
                ("cargo_contacto", models.CharField(blank=True, max_length=100)),
                ("telefono_contacto", models.CharField(blank=True, max_length=50)),
                ("email_contacto", models.EmailField(blank=True, max_length=254)),
                (
                    "activo",
                    models.BooleanField(
                        default=True, help_text="Si está activa para nuevas operaciones"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entidades_externas_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organización a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organizacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entidad Externa",
                "verbose_name_plural": "Entidades Externas",
                "ordering": ["tipo_entidad", "razon_social"],
            },
        ),
        migrations.CreateModel(
            name="DetalleAsientoNomina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cuenta_codigo",
                    models.CharField(
                        help_text="Código de cuenta PUC (temporal)", max_length=20
                    ),
                ),
                (
                    "naturaleza",
                    models.CharField(
                        choices=[("DB", "Débito"), ("CR", "Crédito")],
                        help_text="Naturaleza del movimiento",
                        max_length=2,
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor del movimiento",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        help_text="Descripción del movimiento", max_length=500
                    ),
                ),
                (
                    "orden",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Orden de presentación en el asiento"
                    ),
                ),
                (
                    "asiento",
                    models.ForeignKey(
                        help_text="Asiento contable al que pertenece",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="payroll.asientonomina",
                    ),
                ),
                (
                    "centro_costo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Centro de costo para análisis de costos",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimientos_contables",
                        to="payroll.centrocosto",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organización a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organizacion",
                    ),
                ),
                (
                    "entidad_externa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tercero (EPS, AFP, etc.) si aplica",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimientos_contables",
                        to="payroll.entidadexterna",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Asiento Contable",
                "verbose_name_plural": "Detalles de Asientos Contables",
                "ordering": ["asiento", "orden", "naturaleza"],
            },
        ),
        migrations.CreateModel(
            name="TipoNovedad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código único del tipo de novedad (ej: INC_GEN, LIC_MAT)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(help_text="Nombre descriptivo", max_length=100),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True, help_text="Descripción detallada y fundamento legal"
                    ),
                ),
                (
                    "efecto_pago",
                    models.CharField(
                        choices=[
                            ("COM", "Pago Completo (100% empleador)"),
                            ("PAR", "Pago Parcial (empleador + EPS)"),
                            ("EPS", "Pago EPS (66.67% desde día 3)"),
                            ("ARL", "Pago ARL (100%)"),
                            ("NOP", "Sin Pago"),
                        ],
                        default="COM",
                        help_text="Cómo afecta el pago al empleado",
                        max_length=3,
                    ),
                ),
                (
                    "porcentaje_pago_empleador",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100.00"),
                        help_text="% que paga el empleador (0-100%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "porcentaje_pago_eps",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="% que paga la EPS/ARL (0-100%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "dias_carencia_empleador",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Días iniciales que paga 100% el empleador antes de EPS/ARL",
                    ),
                ),
                (
                    "afecta_ibc_salud",
                    models.BooleanField(
                        default=True,
                        help_text="Si afecta la base de cotización de salud",
                    ),
                ),
                (
                    "afecta_ibc_pension",
                    models.BooleanField(
                        default=True,
                        help_text="Si afecta la base de cotización de pensión",
                    ),
                ),
                (
                    "afecta_ibc_arl",
                    models.BooleanField(
                        default=True, help_text="Si afecta la base de cotización de ARL"
                    ),
                ),
                (
                    "afecta_parafiscales",
                    models.BooleanField(
                        default=True,
                        help_text="Si afecta la base de parafiscales (SENA, ICBF, Caja)",
                    ),
                ),
                (
                    "afecta_provisiones",
                    models.BooleanField(
                        default=True,
                        help_text="Si afecta el cálculo de prestaciones sociales",
                    ),
                ),
                (
                    "suspende_auxilio_transporte",
                    models.BooleanField(
                        default=False,
                        help_text="Si suspende el pago del auxilio de transporte",
                    ),
                ),
                (
                    "marca_pila",
                    models.CharField(
                        choices=[
                            ("X", "Normal (sin marca)"),
                            ("IGE", "Incapacidad General"),
                            ("LMA", "Licencia de Maternidad"),
                            ("LPA", "Licencia de Paternidad"),
                            ("VAC", "Vacaciones"),
                            ("SLN", "Suspensión Temporal (Licencia No Remunerada)"),
                            ("VCT", "Variación Centro de Trabajo"),
                        ],
                        default="X",
                        help_text="Marca a reportar en la planilla PILA",
                        max_length=3,
                    ),
                ),
                (
                    "requiere_soporte",
                    models.BooleanField(
                        default=False,
                        help_text="Si requiere adjuntar documento soporte (ej: incapacidad médica)",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "orden",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Orden de presentación"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organización a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organizacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Novedad",
                "verbose_name_plural": "Tipos de Novedad",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="NovedadCalendario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        help_text="Fecha de inicio de la novedad (inclusive)"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(
                        help_text="Fecha de fin de la novedad (inclusive)"
                    ),
                ),
                (
                    "dias_calendario",
                    models.PositiveSmallIntegerField(
                        default=0,
                        editable=False,
                        help_text="Días calendario totales (calculado automáticamente)",
                    ),
                ),
                (
                    "dias_habiles",
                    models.PositiveSmallIntegerField(
                        default=0,
                        editable=False,
                        help_text="Días hábiles (excluyendo domingos/festivos si aplica)",
                    ),
                ),
                (
                    "documento_soporte",
                    models.FileField(
                        blank=True,
                        help_text="Archivo soporte (incapacidad médica, certificado, etc.)",
                        null=True,
                        upload_to="novedades_calendario/%Y/%m/",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(
                        blank=True,
                        help_text="Número del documento soporte (ej: número de incapacidad)",
                        max_length=100,
                    ),
                ),
                (
                    "entidad_emisora",
                    models.CharField(
                        blank=True,
                        help_text="Entidad que emite el soporte (EPS, ARL, Juzgado, etc.)",
                        max_length=200,
                    ),
                ),
                (
                    "valor_pagado_empleador",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Monto que paga el empleador",
                        max_digits=12,
                    ),
                ),
                (
                    "valor_pagado_eps_arl",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Monto que paga EPS/ARL (a cobrar)",
                        max_digits=12,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("REG", "Registrada"),
                            ("APR", "Aprobada"),
                            ("REC", "Rechazada"),
                            ("PRO", "Procesada en Nómina"),
                            ("ANU", "Anulada"),
                        ],
                        default="REG",
                        help_text="Estado actual de la novedad",
                        max_length=3,
                    ),
                ),
                (
                    "fecha_aprobacion",
                    models.DateTimeField(
                        blank=True, help_text="Fecha de aprobación/rechazo", null=True
                    ),
                ),
                (
                    "motivo_rechazo",
                    models.TextField(
                        blank=True, help_text="Motivo del rechazo (si aplica)"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "aprobada_por",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que aprobó/rechazó",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="novedades_aprobadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "centro_costo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Centro de costo donde trabajaba (para estadísticas)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="novedades",
                        to="payroll.centrocosto",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="novedades_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        help_text="Empleado al que aplica la novedad",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="novedades_calendario",
                        to="payroll.empleado",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organización a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organizacion",
                    ),
                ),
                (
                    "tipo_novedad",
                    models.ForeignKey(
                        help_text="Tipo de novedad (Incapacidad, Licencia, etc.)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="novedades",
                        to="payroll.tiponovedad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Novedad de Calendario",
                "verbose_name_plural": "Novedades de Calendario",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.AddIndex(
            model_name="asientonomina",
            index=models.Index(
                fields=["organization", "fecha_asiento"],
                name="payroll_asi_organiz_600005_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="asientonomina",
            index=models.Index(
                fields=["numero_comprobante"], name="payroll_asi_numero__98edb9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asientonomina",
            index=models.Index(
                fields=["estado", "cuadrado"], name="payroll_asi_estado_f68821_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="centrocosto",
            index=models.Index(
                fields=["organization", "estado", "activo"],
                name="payroll_cen_organiz_9fa5e1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="centrocosto",
            index=models.Index(
                fields=["organization", "parent"], name="payroll_cen_organiz_978c3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="centrocosto",
            index=models.Index(fields=["codigo"], name="payroll_cen_codigo_abbbea_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="centrocosto",
            unique_together={("organization", "codigo")},
        ),
        migrations.AddIndex(
            model_name="distribucioncostonomina",
            index=models.Index(
                fields=["organization", "centro_costo"],
                name="payroll_dis_organiz_c45d33_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="distribucioncostonomina",
            index=models.Index(
                fields=["nomina_simple"], name="payroll_dis_nomina__84162a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="distribucioncostonomina",
            index=models.Index(
                fields=["nomina_electronica"], name="payroll_dis_nomina__484b3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entidadexterna",
            index=models.Index(
                fields=["organization", "tipo_entidad", "activo"],
                name="payroll_ent_organiz_7223f5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="entidadexterna",
            index=models.Index(fields=["nit"], name="payroll_ent_nit_c00070_idx"),
        ),
        migrations.AddIndex(
            model_name="entidadexterna",
            index=models.Index(fields=["codigo"], name="payroll_ent_codigo_8fb1a4_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="entidadexterna",
            unique_together={("organization", "nit")},
        ),
        migrations.AddIndex(
            model_name="detalleasientonomina",
            index=models.Index(
                fields=["asiento", "naturaleza"], name="payroll_det_asiento_467e8c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tiponovedad",
            unique_together={("organization", "codigo")},
        ),
        migrations.AddIndex(
            model_name="novedadcalendario",
            index=models.Index(
                fields=["organization", "empleado", "fecha_inicio"],
                name="payroll_nov_organiz_1e191e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="novedadcalendario",
            index=models.Index(
                fields=["organization", "estado"], name="payroll_nov_organiz_a34642_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="novedadcalendario",
            index=models.Index(
                fields=["fecha_inicio", "fecha_fin"],
                name="payroll_nov_fecha_i_de6908_idx",
            ),
        ),
    ]
