# Generated by Django 4.2.7 on 2026-01-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0003_asientonomina_centrocosto_distribucioncostonomina_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conceptolaboral",
            name="afecta_ibc",
            field=models.BooleanField(
                default=True,
                help_text="Si TRUE, este concepto suma para calcular el IBC (Ingreso Base Cotización). FALSE para auxilio transporte, viáticos no salariales, etc.",
            ),
        ),
        migrations.AddField(
            model_name="conceptolaboral",
            name="afecta_parafiscales",
            field=models.BooleanField(
                default=True,
                help_text="Si TRUE, cuenta para base de cálculo de SENA/ICBF/Caja. FALSE para auxilios no salariales",
            ),
        ),
        migrations.AddField(
            model_name="conceptolaboral",
            name="es_provision",
            field=models.BooleanField(
                default=False,
                help_text="Si TRUE, se contabiliza como provisión (cesantías, prima, vacaciones). Impacta contabilización y reportes financieros",
            ),
        ),
        migrations.AddField(
            model_name="conceptolaboral",
            name="formula",
            field=models.TextField(
                blank=True,
                help_text="Fórmula a evaluar cuando tipo_formula='FORMULA'. Ej: 'salario_base * 0.04' | 'horas_hed * (salario_base / 240) * 1.25' | Variables disponibles: salario_base, dias_trabajados, ibc, total_devengados, SMMLV, horas_hed, horas_hen, etc. Ver payroll.constants",
            ),
        ),
        migrations.AddField(
            model_name="conceptolaboral",
            name="tipo_formula",
            field=models.CharField(
                choices=[
                    ("FIJA", "Valor Fijo"),
                    ("FORMULA", "Fórmula Dinámica"),
                    ("MANUAL", "Manual"),
                ],
                default="MANUAL",
                help_text="FIJA: usa valor_fijo | FORMULA: evalúa formula | MANUAL: digita usuario",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="conceptolaboral",
            name="valor_fijo",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Valor fijo cuando tipo_formula='FIJA' (ej: 162.000 para auxilio transporte)",
                max_digits=12,
                null=True,
            ),
        ),
    ]
