# Generated by Django 4.2.7 on 2026-01-08 23:35

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0004_alter_logauditoria_objeto_id"),
        ("payroll", "0004_conceptolaboral_afecta_ibc_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TablaRetencionFuente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vigencia_desde",
                    models.DateField(help_text="Fecha desde la cual aplica esta tabla"),
                ),
                (
                    "vigencia_hasta",
                    models.DateField(
                        blank=True,
                        help_text="Fecha hasta la cual aplica (null = vigente)",
                        null=True,
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                (
                    "numero_tramo",
                    models.IntegerField(
                        help_text="Número del tramo (1-7)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "uvt_desde",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="UVT inicial del tramo (ej: 95)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "uvt_hasta",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="UVT final del tramo (null = sin límite)",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "tarifa_marginal",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Tarifa marginal del tramo (ej: 19.00 para 19%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "impuesto_tramo_anterior",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Impuesto acumulado de tramos anteriores (en UVT)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Tabla Retención Fuente",
                "verbose_name_plural": "Tablas Retención Fuente",
                "ordering": ["vigencia_desde", "numero_tramo"],
                "indexes": [
                    models.Index(
                        fields=["vigencia_desde", "activa"],
                        name="payroll_tab_vigenci_f1571e_idx",
                    ),
                    models.Index(
                        fields=["numero_tramo"], name="payroll_tab_numero__b42e86_idx"
                    ),
                ],
                "unique_together": {("vigencia_desde", "numero_tramo")},
            },
        ),
        migrations.CreateModel(
            name="LiquidacionFIC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anio",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2020),
                            django.core.validators.MaxValueValidator(2100),
                        ]
                    ),
                ),
                (
                    "mes",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                (
                    "numero_empleados",
                    models.IntegerField(
                        default=0,
                        help_text="Número de empleados con cotización > 4 SMMLV",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_ibc",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Sumatoria IBC de todos los empleados con FIC",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_fic",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total liquidado de FIC del período",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "fecha_liquidacion",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha en que se liquidó el FIC"
                    ),
                ),
                (
                    "incluido_en_pila",
                    models.BooleanField(
                        default=False, help_text="Si ya se incluyó en archivo PILA"
                    ),
                ),
                (
                    "fecha_pila",
                    models.DateField(
                        blank=True,
                        help_text="Fecha en que se generó el PILA con este FIC",
                        null=True,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "liquidado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="liquidaciones_fic",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organización a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organizacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liquidación FIC",
                "verbose_name_plural": "Liquidaciones FIC",
                "ordering": ["-anio", "-mes"],
                "indexes": [
                    models.Index(
                        fields=["organization", "anio", "mes"],
                        name="payroll_liq_organiz_c3aeaf_idx",
                    ),
                    models.Index(
                        fields=["incluido_en_pila"],
                        name="payroll_liq_incluid_57723f_idx",
                    ),
                ],
                "unique_together": {("organization", "anio", "mes")},
            },
        ),
        migrations.CreateModel(
            name="EmbargoJudicial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_proceso",
                    models.CharField(
                        help_text="Número de radicado del proceso judicial",
                        max_length=50,
                    ),
                ),
                (
                    "juzgado",
                    models.CharField(
                        help_text="Nombre del juzgado o entidad que ordena el embargo",
                        max_length=200,
                    ),
                ),
                (
                    "tipo_embargo",
                    models.CharField(
                        choices=[
                            ("ALIMENTOS", "Pensión de Alimentos"),
                            ("COOPERATIVA", "Cooperativa o Fondo"),
                            ("FISCAL", "Crédito Fiscal (DIAN, Municipio)"),
                            ("EJECUTIVO", "Ejecutivo (Bancos, Particulares)"),
                            ("LIBRANZA", "Libranza o Préstamo"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "fecha_notificacion",
                    models.DateField(
                        help_text="Fecha en que se notificó el embargo a la empresa"
                    ),
                ),
                (
                    "fecha_inicio_descuento",
                    models.DateField(
                        help_text="Fecha a partir de la cual se inicia el descuento"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True,
                        help_text="Fecha de finalización del embargo (si se conoce)",
                        null=True,
                    ),
                ),
                (
                    "valor_total_deuda",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor total de la deuda embargada",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "porcentaje_descuento",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Porcentaje del salario a embargar (si se especifica porcentaje)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "valor_fijo_mensual",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Valor fijo mensual a embargar (si se especifica monto fijo)",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "saldo_pendiente",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Saldo pendiente por descontar",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_descontado",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total acumulado descontado",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "beneficiario",
                    models.CharField(
                        help_text="Nombre del beneficiario del embargo", max_length=200
                    ),
                ),
                (
                    "numero_cuenta",
                    models.CharField(
                        blank=True,
                        help_text="Número de cuenta para consignación",
                        max_length=50,
                    ),
                ),
                (
                    "banco",
                    models.CharField(
                        blank=True, help_text="Banco para consignación", max_length=100
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ACTIVO", "Activo"),
                            ("SUSPENDIDO", "Suspendido"),
                            ("TERMINADO", "Terminado"),
                        ],
                        default="ACTIVO",
                        max_length=15,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embargos",
                        to="payroll.empleado",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organización a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organizacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Embargo Judicial",
                "verbose_name_plural": "Embargos Judiciales",
                "ordering": ["-fecha_notificacion"],
                "indexes": [
                    models.Index(
                        fields=["organization", "empleado", "estado"],
                        name="payroll_emb_organiz_55fd6f_idx",
                    ),
                    models.Index(
                        fields=["organization", "tipo_embargo"],
                        name="payroll_emb_organiz_263682_idx",
                    ),
                    models.Index(
                        fields=["numero_proceso"], name="payroll_emb_numero__d95d03_idx"
                    ),
                ],
            },
        ),
    ]
