# Generated by Django 5.2 on 2025-06-15 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_position_remove_employee_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payroll',
            options={'ordering': ['-period_end'], 'verbose_name': 'Nómina', 'verbose_name_plural': 'Nóminas'},
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='pay_date',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='salary',
        ),
        migrations.AddField(
            model_name='payroll',
            name='period_end',
            field=models.DateField(blank=True, null=True, verbose_name='Fin del periodo'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='period_start',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio del periodo'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='prestamos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Préstamos'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='production',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Producción'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='restaurante',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Restaurante'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='seguridad',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=10, verbose_name='Seguridad'),
        ),
    ]
