# Generated by Django 4.2.7 on 2026-01-09 22:46

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_logauditoria_objeto_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payroll", "0005_tablaretencionfuente_liquidacionfic_embargojudicial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntregaDotacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_dotacion",
                    models.CharField(
                        choices=[
                            (
                                "VESTUARIO",
                                (
                                    ("UNIFORME", "Uniforme Completo"),
                                    ("CALZADO", "Calzado de Seguridad"),
                                ),
                            ),
                            (
                                "EPP",
                                (
                                    (
                                        "EPP_BASICO",
                                        "EPP Básico (Casco, Guantes, Botas)",
                                    ),
                                    ("EPP_ALTURA", "EPP Trabajo en Alturas"),
                                    ("EPP_RESPIRATORIO", "Protección Respiratoria"),
                                    ("EPP_VISUAL", "Protección Visual"),
                                    ("EPP_AUDITIVO", "Protección Auditiva"),
                                ),
                            ),
                            (
                                "HERRAMIENTAS",
                                (
                                    ("HERRAMIENTAS", "Herramientas de Trabajo"),
                                    ("OTRO", "Otros Elementos"),
                                ),
                            ),
                        ],
                        max_length=30,
                        verbose_name="Tipo de Dotación",
                    ),
                ),
                (
                    "periodo_dotacion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PERIODO_1", "Período 1 (Enero - Abril)"),
                            ("PERIODO_2", "Período 2 (Mayo - Agosto)"),
                            ("PERIODO_3", "Período 3 (Septiembre - Diciembre)"),
                        ],
                        help_text="Aplica solo para uniformes (Art. 230 CST)",
                        max_length=20,
                        null=True,
                        verbose_name="Período de Dotación",
                    ),
                ),
                (
                    "anio",
                    models.PositiveIntegerField(
                        help_text="Año de la dotación", verbose_name="Año"
                    ),
                ),
                (
                    "descripcion_elementos",
                    models.TextField(
                        help_text="Detalle de los elementos entregados",
                        verbose_name="Descripción de Elementos",
                    ),
                ),
                (
                    "cantidad",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Cantidad de unidades entregadas",
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "talla",
                    models.CharField(
                        blank=True,
                        help_text="Talla del uniforme o EPP (XS, S, M, L, XL, etc.)",
                        max_length=20,
                        verbose_name="Talla",
                    ),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Costo unitario del elemento",
                        max_digits=12,
                        verbose_name="Valor Unitario",
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Costo total de la entrega (cantidad * valor_unitario)",
                        max_digits=12,
                        verbose_name="Valor Total",
                    ),
                ),
                (
                    "fecha_programada",
                    models.DateField(
                        help_text="Fecha en que debería entregarse",
                        verbose_name="Fecha Programada",
                    ),
                ),
                (
                    "fecha_entrega_real",
                    models.DateField(
                        blank=True,
                        help_text="Fecha efectiva de entrega al empleado",
                        null=True,
                        verbose_name="Fecha de Entrega Real",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente de Entrega"),
                            ("ENTREGADO", "Entregado"),
                            ("DEVUELTO", "Devuelto"),
                            ("EXTRAVIADO", "Extraviado/Perdido"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "recibido_por",
                    models.CharField(
                        blank=True,
                        help_text="Nombre de quien recibió (generalmente el empleado)",
                        max_length=200,
                        verbose_name="Recibido Por",
                    ),
                ),
                (
                    "documento_recibido",
                    models.CharField(
                        blank=True,
                        help_text="Cédula de quien recibió",
                        max_length=50,
                        verbose_name="Documento",
                    ),
                ),
                (
                    "firma_digital",
                    models.ImageField(
                        blank=True,
                        help_text="Captura de firma al recibir",
                        null=True,
                        upload_to="dotaciones/firmas/%Y/%m/",
                        verbose_name="Firma Digital",
                    ),
                ),
                (
                    "archivo_adjunto",
                    models.FileField(
                        blank=True,
                        help_text="Acta de entrega, fotos, etc.",
                        null=True,
                        upload_to="dotaciones/docs/%Y/%m/",
                        verbose_name="Archivo Adjunto",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Notas adicionales sobre la entrega",
                        verbose_name="Observaciones",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Modificación"
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dotaciones",
                        to="payroll.empleado",
                        verbose_name="Empleado",
                    ),
                ),
                (
                    "entregado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dotaciones_entregadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Entregado Por",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organización a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organizacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrega de Dotación",
                "verbose_name_plural": "Entregas de Dotación",
                "ordering": ["-fecha_programada"],
                "indexes": [
                    models.Index(
                        fields=["organization", "empleado", "anio"],
                        name="payroll_ent_organiz_3c5d6a_idx",
                    ),
                    models.Index(
                        fields=["periodo_dotacion", "anio"],
                        name="payroll_ent_periodo_6f9abb_idx",
                    ),
                    models.Index(
                        fields=["estado"], name="payroll_ent_estado_678413_idx"
                    ),
                    models.Index(
                        fields=["fecha_programada"],
                        name="payroll_ent_fecha_p_1a666e_idx",
                    ),
                ],
                "unique_together": {
                    (
                        "organization",
                        "empleado",
                        "tipo_dotacion",
                        "periodo_dotacion",
                        "anio",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="CertificadoEmpleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_certificado",
                    models.CharField(
                        choices=[
                            (
                                "MEDICOS",
                                (
                                    ("MEDICO_INGRESO", "Examen Médico de Ingreso"),
                                    ("MEDICO_PERIODICO", "Examen Médico Periódico"),
                                    ("MEDICO_EGRESO", "Examen Médico de Egreso"),
                                ),
                            ),
                            (
                                "TRABAJO EN ALTURAS",
                                (
                                    ("ALTURA", "Trabajo en Alturas"),
                                    ("ESPACIOS_CONFINADOS", "Espacios Confinados"),
                                ),
                            ),
                            (
                                "FORMACION SST",
                                (
                                    ("SST_BASICO", "Capacitación SST Básica"),
                                    ("SST_50_HORAS", "Curso SST 50 Horas"),
                                    ("SST_COORDINADOR", "Certificado Coordinador SST"),
                                ),
                            ),
                            (
                                "EMERGENCIAS",
                                (
                                    ("BRIGADA_EMERGENCIAS", "Brigada de Emergencias"),
                                    ("PRIMEROS_AUXILIOS", "Primeros Auxilios"),
                                    ("MANEJO_EXTINTORES", "Manejo de Extintores"),
                                ),
                            ),
                            (
                                "OPERACION",
                                (
                                    ("OPERACION_VEHICULOS", "Operación de Vehículos"),
                                    ("OPERACION_MAQUINARIA", "Operación de Maquinaria"),
                                    (
                                        "MANIPULACION_ALIMENTOS",
                                        "Manipulación de Alimentos",
                                    ),
                                ),
                            ),
                            (
                                "RIESGOS",
                                (
                                    ("RIESGO_ELECTRICO", "Riesgo Eléctrico"),
                                    ("RIESGO_QUIMICO", "Riesgo Químico"),
                                    ("RIESGO_BIOLOGICO", "Riesgo Biológico"),
                                ),
                            ),
                            (
                                "LICENCIAS",
                                (
                                    ("LICENCIA_CONDUCCION", "Licencia de Conducción"),
                                    (
                                        "CERTIFICADO_COMPETENCIA",
                                        "Certificado de Competencia",
                                    ),
                                ),
                            ),
                            ("OTROS", (("OTRO", "Otro Certificado"),)),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Certificado",
                    ),
                ),
                (
                    "numero_certificado",
                    models.CharField(
                        blank=True,
                        help_text="Número de registro o identificación del certificado",
                        max_length=100,
                        null=True,
                        verbose_name="Número de Certificado",
                    ),
                ),
                (
                    "entidad_emisora",
                    models.CharField(
                        help_text="Empresa, institución o profesional que emitió el certificado",
                        max_length=200,
                        verbose_name="Entidad Emisora",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Detalles adicionales del certificado",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "fecha_emision",
                    models.DateField(
                        help_text="Fecha en que fue expedido el certificado",
                        verbose_name="Fecha de Emisión",
                    ),
                ),
                (
                    "fecha_vencimiento",
                    models.DateField(
                        help_text="Fecha límite de vigencia del certificado",
                        verbose_name="Fecha de Vencimiento",
                    ),
                ),
                (
                    "dias_alerta_vencimiento",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Días antes del vencimiento para enviar alerta (default: 30)",
                        verbose_name="Días de Alerta",
                    ),
                ),
                (
                    "obligatorio_para_nomina",
                    models.BooleanField(
                        default=False,
                        help_text="Si TRUE, bloquea procesamiento de nómina si está vencido",
                        verbose_name="Obligatorio para Nómina",
                    ),
                ),
                (
                    "alerta_enviada",
                    models.BooleanField(
                        default=False,
                        help_text="Control para evitar enviar múltiples alertas",
                        verbose_name="Alerta Enviada",
                    ),
                ),
                (
                    "fecha_alerta_enviada",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Alerta Enviada"
                    ),
                ),
                (
                    "archivo_pdf",
                    models.FileField(
                        blank=True,
                        help_text="Escaneo o PDF del certificado",
                        null=True,
                        upload_to="certificados/%Y/%m/",
                        verbose_name="Archivo PDF",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Notas adicionales o comentarios",
                        verbose_name="Observaciones",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Modificación"
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificados_creados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado Por",
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificados",
                        to="payroll.empleado",
                        verbose_name="Empleado",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organización a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organizacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificado de Empleado",
                "verbose_name_plural": "Certificados de Empleados",
                "ordering": ["-fecha_vencimiento"],
                "indexes": [
                    models.Index(
                        fields=["organization", "empleado", "tipo_certificado"],
                        name="payroll_cer_organiz_6dc488_idx",
                    ),
                    models.Index(
                        fields=["fecha_vencimiento"],
                        name="payroll_cer_fecha_v_7e010d_idx",
                    ),
                    models.Index(
                        fields=["obligatorio_para_nomina"],
                        name="payroll_cer_obligat_63be34_idx",
                    ),
                ],
            },
        ),
    ]
