# Generated by Django 4.2.7 on 2026-01-09 23:00

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_logauditoria_objeto_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payroll", "0006_entregadotacion_certificadoempleado"),
    ]

    operations = [
        migrations.CreateModel(
            name="NominaAjuste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_ajuste",
                    models.CharField(
                        choices=[
                            (
                                "REEMPLAZAR",
                                "Reemplazar - Reemplaza completamente la nómina original",
                            ),
                            ("ELIMINAR", "Eliminar - Anula la nómina original"),
                            (
                                "ADICIONAR",
                                "Adicionar - Agrega conceptos a la nómina original",
                            ),
                            ("CORREGIR", "Corregir - Corrige valores específicos"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Ajuste",
                    ),
                ),
                (
                    "numero_ajuste",
                    models.CharField(
                        help_text="Número consecutivo del ajuste (NADJ-2026-00001)",
                        max_length=50,
                        unique=True,
                        verbose_name="Número de Ajuste",
                    ),
                ),
                (
                    "fecha_ajuste",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Ajuste",
                    ),
                ),
                (
                    "motivo_ajuste",
                    models.TextField(
                        help_text="Descripción detallada del motivo del ajuste",
                        verbose_name="Motivo del Ajuste",
                    ),
                ),
                (
                    "cune",
                    models.CharField(
                        blank=True,
                        help_text="Código Único de Nómina Electrónica (CUNE) del ajuste",
                        max_length=100,
                        null=True,
                        verbose_name="CUNE",
                    ),
                ),
                (
                    "xml_contenido",
                    models.TextField(
                        blank=True,
                        help_text="XML UBL 2.1 del ajuste generado",
                        null=True,
                        verbose_name="Contenido XML",
                    ),
                ),
                (
                    "xml_firmado",
                    models.TextField(
                        blank=True,
                        help_text="XML con firma digital XMLDSIG",
                        null=True,
                        verbose_name="XML Firmado",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("generado", "XML Generado"),
                            ("enviado", "Enviado a DIAN"),
                            ("aceptado", "Aceptado por DIAN"),
                            ("rechazado", "Rechazado por DIAN"),
                            ("error", "Error en Procesamiento"),
                        ],
                        default="borrador",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "codigo_respuesta_dian",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Código Respuesta DIAN",
                    ),
                ),
                (
                    "mensaje_respuesta_dian",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mensaje Respuesta DIAN"
                    ),
                ),
                (
                    "fecha_envio_dian",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Envío DIAN"
                    ),
                ),
                (
                    "fecha_respuesta_dian",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Respuesta DIAN"
                    ),
                ),
                (
                    "total_devengado_ajustado",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Total Devengado Ajustado",
                    ),
                ),
                (
                    "total_deducido_ajustado",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Total Deducido Ajustado",
                    ),
                ),
                (
                    "neto_ajustado",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Neto Ajustado",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Modificación"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Notas adicionales internas",
                        verbose_name="Observaciones",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ajustes_nomina_creados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado Por",
                    ),
                ),
                (
                    "nomina_original",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ajustes",
                        to="payroll.nominaelectronica",
                        verbose_name="Nómina Original",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organización a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organizacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ajuste de Nómina Electrónica",
                "verbose_name_plural": "Ajustes de Nómina Electrónica",
                "ordering": ["-fecha_ajuste", "-numero_ajuste"],
            },
        ),
        migrations.CreateModel(
            name="DetalleAjuste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_original",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Valor Original",
                    ),
                ),
                (
                    "valor_ajustado",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Valor Ajustado",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Motivo específico del ajuste de este concepto",
                        verbose_name="Observaciones",
                    ),
                ),
                (
                    "ajuste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="payroll.nominaajuste",
                        verbose_name="Ajuste",
                    ),
                ),
                (
                    "concepto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payroll.conceptolaboral",
                        verbose_name="Concepto Laboral",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organización a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organizacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Ajuste",
                "verbose_name_plural": "Detalles de Ajuste",
                "ordering": ["concepto__codigo"],
            },
        ),
        migrations.AddIndex(
            model_name="nominaajuste",
            index=models.Index(
                fields=["organization", "nomina_original"],
                name="payroll_nom_organiz_cc5db1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="nominaajuste",
            index=models.Index(
                fields=["numero_ajuste"], name="payroll_nom_numero__012ca6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nominaajuste",
            index=models.Index(fields=["cune"], name="payroll_nom_cune_a75ae9_idx"),
        ),
        migrations.AddIndex(
            model_name="nominaajuste",
            index=models.Index(fields=["estado"], name="payroll_nom_estado_827763_idx"),
        ),
        migrations.AddIndex(
            model_name="nominaajuste",
            index=models.Index(
                fields=["fecha_ajuste"], name="payroll_nom_fecha_a_44924d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="detalleajuste",
            index=models.Index(
                fields=["ajuste", "concepto"], name="payroll_det_ajuste__16c8c7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="detalleajuste",
            unique_together={("organization", "ajuste", "concepto")},
        ),
    ]
