# Generated by Django 4.2.7 on 2026-01-03 22:41

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_logauditoria_objeto_id"),
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConceptoLaboral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código único del concepto (ej: SAL_BASE, AUX_TRANS, HOR_EXTRA)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "tipo_concepto",
                    models.CharField(
                        choices=[
                            ("DEV", "Devengado"),
                            ("DED", "Deducción"),
                            ("APO", "Aporte"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "es_salarial",
                    models.BooleanField(
                        default=False,
                        help_text="Si aporta a base de cotización de seguridad social",
                    ),
                ),
                (
                    "aplica_seguridad_social",
                    models.BooleanField(
                        default=False,
                        help_text="Si se calcula automáticamente (ej: salud, pensión)",
                    ),
                ),
                (
                    "es_item_construccion",
                    models.BooleanField(
                        default=False,
                        help_text="Si es un item de construcción (vinculado a Item model)",
                    ),
                ),
                (
                    "codigo_dian",
                    models.CharField(
                        blank=True,
                        help_text="Código según catálogo DIAN para nómina electrónica",
                        max_length=10,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "orden",
                    models.IntegerField(
                        default=0, help_text="Orden de presentación en formularios"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organización a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organizacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Concepto Laboral",
                "verbose_name_plural": "Conceptos Laborales",
                "ordering": ["tipo_concepto", "orden", "nombre"],
                "unique_together": {("organization", "codigo")},
            },
        ),
        migrations.CreateModel(
            name="DetalleConceptoNominaSimple",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Cantidad de unidades (ej: días, horas, etc.)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor por unidad",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "concepto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payroll.conceptolaboral",
                    ),
                ),
                (
                    "nomina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles_conceptos",
                        to="payroll.nominasimple",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organización a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organizacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle Concepto Nómina Simple",
                "verbose_name_plural": "Detalles Conceptos Nómina Simple",
                "ordering": ["concepto__tipo_concepto", "concepto__orden"],
                "unique_together": {("nomina", "concepto")},
            },
        ),
        migrations.CreateModel(
            name="DetalleConceptoNominaElectronica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Cantidad de unidades (ej: días, horas, etc.)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor por unidad",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "codigo_dian",
                    models.CharField(
                        blank=True,
                        help_text="Código DIAN automático del concepto o personalizado",
                        max_length=10,
                    ),
                ),
                (
                    "concepto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payroll.conceptolaboral",
                    ),
                ),
                (
                    "nomina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles_conceptos",
                        to="payroll.nominaelectronica",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organización a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organizacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle Concepto Nómina Electrónica",
                "verbose_name_plural": "Detalles Conceptos Nómina Electrónica",
                "ordering": ["concepto__tipo_concepto", "concepto__orden"],
                "unique_together": {("nomina", "concepto")},
            },
        ),
    ]
