# Generated by Django 4.2.7 on 2026-02-25 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_seed_plans_and_convert_fk"),
        ("prestamos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prestamo",
            name="numero_prestamo",
            field=models.CharField(
                blank=True,
                help_text="Número único del préstamo (se genera automáticamente)",
                max_length=20,
                verbose_name="Número de préstamo",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="prestamo",
            unique_together={("organization", "numero_prestamo")},
        ),
    ]
