# Generated by Django 5.2.5 on 2026-02-28 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_activeproject_asignacionproyecto_and_more"),
        ("prestamos", "0002_numero_prestamo_unique_per_org"),
    ]

    operations = [
        migrations.AddField(
            model_name="prestamo",
            name="proyecto",
            field=models.ForeignKey(
                blank=True,
                help_text="Proyecto al que pertenece este préstamo",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prestamos",
                to="dashboard.project",
                verbose_name="Proyecto",
            ),
        ),
    ]
