# Generated by Django 5.2 on 2025-06-30 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre único del rol', max_length=100, unique=True, verbose_name='Nombre del rol')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del rol y sus responsabilidades', null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, help_text='Si está activo, el rol estará disponible para asignar', verbose_name='Activo')),
                ('es_sistema', models.BooleanField(default=False, help_text='Los roles del sistema no se pueden eliminar', verbose_name='Es del sistema')),
                ('tiene_restriccion_horario', models.BooleanField(default=False, help_text='Si está activo, se aplicarán las restricciones de horario', verbose_name='Tiene restricción de horario')),
                ('hora_inicio', models.TimeField(blank=True, help_text='Hora de inicio de acceso permitido', null=True, verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(blank=True, help_text='Hora de fin de acceso permitido', null=True, verbose_name='Hora de fin')),
                ('dias_semana', models.CharField(default='1234567', help_text='Días permitidos (1=Lunes, 7=Domingo). Ej: 12345 para L-V', max_length=7, verbose_name='Días de la semana')),
                ('fecha_inicio_vigencia', models.DateField(blank=True, help_text='Fecha desde la cual el rol está vigente', null=True, verbose_name='Fecha inicio vigencia')),
                ('fecha_fin_vigencia', models.DateField(blank=True, help_text='Fecha hasta la cual el rol está vigente', null=True, verbose_name='Fecha fin vigencia')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['activo'], name='roles_rol_activo_491541_idx'), models.Index(fields=['nombre'], name='roles_rol_nombre_c781a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='AsignacionRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True, help_text='Si está activa, el usuario tiene este rol', verbose_name='Asignación activa')),
                ('fecha_inicio', models.DateTimeField(blank=True, help_text='Fecha desde la cual la asignación es válida', null=True, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, help_text='Fecha hasta la cual la asignación es válida', null=True, verbose_name='Fecha de fin')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre la asignación', null=True, verbose_name='Observaciones')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('asignado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_rol', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='roles.rol', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Asignación de Rol',
                'verbose_name_plural': 'Asignaciones de Rol',
                'ordering': ['-fecha_asignacion'],
                'indexes': [models.Index(fields=['usuario', 'activa'], name='roles_asign_usuario_3542e7_idx'), models.Index(fields=['rol', 'activa'], name='roles_asign_rol_id_255f1c_idx')],
                'unique_together': {('usuario', 'rol')},
            },
        ),
    ]
