# Generated by Django 5.2 on 2025-08-22 01:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva'), ('EXPIRADA', 'Expirada'), ('REVOCADA', 'Revocada')], max_length=20, unique=True, verbose_name='Estado')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('color', models.CharField(blank=True, max_length=7, null=True, verbose_name='Color')),
                ('organization', models.ForeignKey(blank=True, help_text='Organización a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organizacion')),
            ],
            options={
                'verbose_name': 'Estado de Asignación',
                'verbose_name_plural': 'Estados de Asignación',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('nombre', models.CharField(help_text='Nombre único del rol', max_length=100, unique=True, verbose_name='Nombre del rol')),
                ('codigo', models.CharField(default='NUEVO_ROL', help_text='Código único alfanumérico del rol', max_length=50, unique=True, verbose_name='Código')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del rol y sus responsabilidades', null=True, verbose_name='Descripción')),
                ('nivel_jerarquico', models.IntegerField(default=0, help_text='Nivel en la jerarquía (0=raíz, mayor número=más bajo)', verbose_name='Nivel jerárquico')),
                ('hereda_permisos', models.BooleanField(default=True, help_text='Si hereda permisos del rol padre', verbose_name='Hereda permisos')),
                ('categoria', models.CharField(blank=True, help_text='Categoría o departamento del rol', max_length=100, null=True, verbose_name='Categoría')),
                ('activo', models.BooleanField(default=True, help_text='Si está activo, el rol estará disponible para asignar', verbose_name='Activo')),
                ('es_sistema', models.BooleanField(default=False, help_text='Los roles del sistema no se pueden eliminar', verbose_name='Es del sistema')),
                ('es_publico', models.BooleanField(default=False, help_text='Si es público, cualquier usuario puede solicitarlo', verbose_name='Es público')),
                ('requiere_aprobacion', models.BooleanField(default=False, help_text='La asignación requiere aprobación', verbose_name='Requiere aprobación')),
                ('tiene_restriccion_horario', models.BooleanField(default=False, help_text='Si está activo, se aplicarán las restricciones de horario', verbose_name='Tiene restricción de horario')),
                ('hora_inicio', models.TimeField(blank=True, help_text='Hora de inicio de acceso permitido', null=True, verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(blank=True, help_text='Hora de fin de acceso permitido', null=True, verbose_name='Hora de fin')),
                ('dias_semana', models.CharField(default='1234567', help_text='Días permitidos (1=Lunes, 7=Domingo). Ej: 12345 para L-V', max_length=7, verbose_name='Días de la semana')),
                ('fecha_inicio_vigencia', models.DateField(blank=True, help_text='Fecha desde la cual el rol está vigente', null=True, verbose_name='Fecha inicio vigencia')),
                ('fecha_fin_vigencia', models.DateField(blank=True, help_text='Fecha hasta la cual el rol está vigente', null=True, verbose_name='Fecha fin vigencia')),
                ('prioridad', models.IntegerField(default=0, help_text='Prioridad del rol (mayor número = mayor prioridad)', verbose_name='Prioridad')),
                ('peso', models.IntegerField(default=1, help_text='Peso para cálculos de autorización', verbose_name='Peso')),
                ('color', models.CharField(blank=True, help_text='Color hexadecimal para UI (#FFFFFF)', max_length=7, null=True, verbose_name='Color')),
                ('icono', models.CharField(blank=True, help_text='Clase CSS del icono', max_length=50, null=True, verbose_name='Icono')),
                ('metadatos', models.JSONField(blank=True, default=dict, help_text='Datos adicionales en formato JSON', verbose_name='Metadatos')),
                ('configuracion', models.JSONField(blank=True, default=dict, help_text='Configuración específica del rol', verbose_name='Configuración')),
                ('tenant_id', models.CharField(blank=True, help_text='ID del tenant/organización', max_length=100, null=True, verbose_name='ID del tenant')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('total_asignaciones', models.IntegerField(default=0, help_text='Número total de asignaciones de este rol', verbose_name='Total de asignaciones')),
                ('asignaciones_activas', models.IntegerField(default=0, help_text='Número de asignaciones activas', verbose_name='Asignaciones activas')),
                ('ultima_asignacion', models.DateTimeField(blank=True, null=True, verbose_name='Última asignación')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roles_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roles_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('organization', models.ForeignKey(blank=True, help_text='Organización a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organizacion')),
                ('rol_padre', models.ForeignKey(blank=True, help_text='Rol del cual hereda permisos', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles_hijo', to='roles.rol', verbose_name='Rol padre')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['nivel_jerarquico', 'prioridad', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MetaRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del meta-rol')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('reglas', models.JSONField(default=dict, help_text='Reglas JSON que definen el comportamiento del meta-rol', verbose_name='Reglas de meta-rol')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Organización a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organizacion')),
                ('roles_aplicables', models.ManyToManyField(blank=True, related_name='meta_roles', to='roles.rol', verbose_name='Roles aplicables')),
            ],
            options={
                'verbose_name': 'Meta-rol',
                'verbose_name_plural': 'Meta-roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuracion_ui', models.JSONField(blank=True, default=dict, help_text='Configuración específica para la interfaz de usuario', verbose_name='Configuración de UI')),
                ('configuracion_seguridad', models.JSONField(blank=True, default=dict, help_text='Configuraciones de seguridad específicas del rol', verbose_name='Configuración de seguridad')),
                ('configuracion_notificaciones', models.JSONField(blank=True, default=dict, help_text='Configuración de notificaciones para el rol', verbose_name='Configuración de notificaciones')),
                ('configuracion_integraciones', models.JSONField(blank=True, default=dict, help_text='Configuraciones para integraciones externas', verbose_name='Configuración de integraciones')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('organization', models.ForeignKey(blank=True, help_text='Organización a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organizacion')),
                ('rol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_dinamica', to='roles.rol', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Configuración de Rol',
                'verbose_name_plural': 'Configuraciones de Roles',
            },
        ),
        migrations.CreateModel(
            name='AsignacionRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True, help_text='Si está activa, el usuario tiene este rol', verbose_name='Asignación activa')),
                ('fecha_inicio', models.DateTimeField(blank=True, help_text='Fecha desde la cual la asignación es válida', null=True, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, help_text='Fecha hasta la cual la asignación es válida', null=True, verbose_name='Fecha de fin')),
                ('contexto_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID del contexto')),
                ('justificacion', models.TextField(blank=True, help_text='Razón de la asignación', null=True, verbose_name='Justificación')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre la asignación', null=True, verbose_name='Observaciones')),
                ('metadatos', models.JSONField(blank=True, default=dict, help_text='Datos adicionales en formato JSON', verbose_name='Metadatos')),
                ('prioridad', models.IntegerField(default=0, help_text='Prioridad de la asignación', verbose_name='Prioridad')),
                ('configuracion', models.JSONField(blank=True, default=dict, help_text='Configuración específica de la asignación', verbose_name='Configuración')),
                ('tenant_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID del tenant')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('fecha_revocacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revocación')),
                ('razon_revocacion', models.TextField(blank=True, null=True, verbose_name='Razón de revocación')),
                ('ip_asignacion', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de asignación')),
                ('user_agent_asignacion', models.TextField(blank=True, null=True, verbose_name='User Agent de asignación')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('asignado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('contexto_tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de contexto')),
                ('organization', models.ForeignKey(blank=True, help_text='Organización a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organizacion')),
                ('revocado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_revocadas', to=settings.AUTH_USER_MODEL, verbose_name='Revocado por')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_rol', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='roles.estadoasignacion', verbose_name='Estado')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='roles.rol', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Asignación de Rol',
                'verbose_name_plural': 'Asignaciones de Rol',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.CreateModel(
            name='RolCondicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condiciones_activacion', models.JSONField(default=list, help_text='Lista de condiciones que deben cumplirse para activar el rol', verbose_name='Condiciones de activación')),
                ('condiciones_desactivacion', models.JSONField(default=list, help_text='Lista de condiciones que desactivan el rol automáticamente', verbose_name='Condiciones de desactivación')),
                ('evaluacion_automatica', models.BooleanField(default=True, help_text='Si se evalúan las condiciones automáticamente', verbose_name='Evaluación automática')),
                ('frecuencia_evaluacion', models.CharField(choices=[('tiempo_real', 'Tiempo real'), ('cada_hora', 'Cada hora'), ('diaria', 'Diaria'), ('semanal', 'Semanal'), ('manual', 'Manual')], default='cada_hora', max_length=20, verbose_name='Frecuencia de evaluación')),
                ('ultima_evaluacion', models.DateTimeField(blank=True, null=True, verbose_name='Última evaluación')),
                ('resultado_ultima_evaluacion', models.JSONField(default=dict, verbose_name='Resultado de última evaluación')),
                ('organization', models.ForeignKey(blank=True, help_text='Organización a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organizacion')),
                ('rol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_condicional', to='roles.rol', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Rol Condicional',
                'verbose_name_plural': 'Roles Condicionales',
            },
        ),
        migrations.CreateModel(
            name='TipoRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del tipo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden de presentación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Organización a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organizacion')),
            ],
            options={
                'verbose_name': 'Tipo de Rol',
                'verbose_name_plural': 'Tipos de Rol',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='rol',
            name='tipo_rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='roles.tiporol', verbose_name='Tipo de rol'),
        ),
        migrations.CreateModel(
            name='PlantillaRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la plantilla')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('configuracion_base', models.JSONField(default=dict, help_text='Configuración predeterminada para roles creados con esta plantilla', verbose_name='Configuración base')),
                ('permisos_incluidos', models.JSONField(default=list, help_text='Lista de permisos que se asignarán automáticamente', verbose_name='Permisos incluidos')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('es_sistema', models.BooleanField(default=False, verbose_name='Es del sistema')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantillas_rol_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('organization', models.ForeignKey(blank=True, help_text='Organización a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organizacion')),
                ('tipo_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.tiporol', verbose_name='Tipo de rol')),
            ],
            options={
                'verbose_name': 'Plantilla de Rol',
                'verbose_name_plural': 'Plantillas de Rol',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistorialAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(help_text='Tipo de acción realizada', max_length=50, verbose_name='Acción')),
                ('estado_anterior', models.CharField(blank=True, max_length=20, null=True, verbose_name='Estado anterior')),
                ('estado_nuevo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Estado nuevo')),
                ('detalles', models.JSONField(blank=True, default=dict, help_text='Detalles del cambio', verbose_name='Detalles')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del cambio')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='roles.asignacionrol', verbose_name='Asignación')),
                ('organization', models.ForeignKey(blank=True, help_text='Organización a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organizacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó el cambio')),
            ],
            options={
                'verbose_name': 'Historial de Asignación',
                'verbose_name_plural': 'Historial de Asignaciones',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['asignacion', 'fecha'], name='roles_histo_asignac_92e188_idx'), models.Index(fields=['usuario', 'fecha'], name='roles_histo_usuario_53e815_idx'), models.Index(fields=['accion'], name='roles_histo_accion_32cb22_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear_rol', 'Crear rol'), ('modificar_rol', 'Modificar rol'), ('eliminar_rol', 'Eliminar rol'), ('asignar_rol', 'Asignar rol'), ('revocar_rol', 'Revocar rol'), ('modificar_asignacion', 'Modificar asignación'), ('activar_rol', 'Activar rol'), ('desactivar_rol', 'Desactivar rol')], max_length=50, verbose_name='Acción')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('detalles_anterior', models.JSONField(default=dict, help_text='Estado del objeto antes del cambio', verbose_name='Estado anterior')),
                ('detalles_nuevo', models.JSONField(default=dict, help_text='Estado del objeto después del cambio', verbose_name='Estado nuevo')),
                ('contexto_adicional', models.JSONField(default=dict, help_text='Información adicional del contexto', verbose_name='Contexto adicional')),
                ('justificacion', models.TextField(blank=True, help_text='Justificación del cambio', null=True, verbose_name='Justificación')),
                ('organization', models.ForeignKey(blank=True, help_text='Organización a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organizacion')),
                ('usuario_afectado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditoria_roles', to=settings.AUTH_USER_MODEL, verbose_name='Usuario afectado')),
                ('usuario_ejecutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acciones_roles_ejecutadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario ejecutor')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoria', to='roles.rol', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Auditoría de Rol',
                'verbose_name_plural': 'Auditorías de Roles',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['rol', 'timestamp'], name='roles_audit_rol_id_8440ec_idx'), models.Index(fields=['usuario_afectado', 'timestamp'], name='roles_audit_usuario_61731e_idx'), models.Index(fields=['accion', 'timestamp'], name='roles_audit_accion_365f2c_idx'), models.Index(fields=['usuario_ejecutor', 'timestamp'], name='roles_audit_usuario_a637fa_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='asignacionrol',
            index=models.Index(fields=['usuario', 'activa'], name='roles_asign_usuario_3542e7_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionrol',
            index=models.Index(fields=['rol', 'activa'], name='roles_asign_rol_id_255f1c_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionrol',
            index=models.Index(fields=['estado'], name='roles_asign_estado__7c1dda_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionrol',
            index=models.Index(fields=['fecha_inicio'], name='roles_asign_fecha_i_e37d55_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionrol',
            index=models.Index(fields=['fecha_fin'], name='roles_asign_fecha_f_4a7c7c_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionrol',
            index=models.Index(fields=['contexto_tipo', 'contexto_id'], name='roles_asign_context_b27221_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionrol',
            index=models.Index(fields=['tenant_id'], name='roles_asign_tenant__fd845f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='asignacionrol',
            unique_together={('usuario', 'rol', 'contexto_tipo', 'contexto_id')},
        ),
        migrations.AddIndex(
            model_name='rol',
            index=models.Index(fields=['activo'], name='roles_rol_activo_491541_idx'),
        ),
        migrations.AddIndex(
            model_name='rol',
            index=models.Index(fields=['nombre'], name='roles_rol_nombre_c781a9_idx'),
        ),
        migrations.AddIndex(
            model_name='rol',
            index=models.Index(fields=['codigo'], name='roles_rol_codigo_ea36e4_idx'),
        ),
        migrations.AddIndex(
            model_name='rol',
            index=models.Index(fields=['nivel_jerarquico'], name='roles_rol_nivel_j_a03f1f_idx'),
        ),
        migrations.AddIndex(
            model_name='rol',
            index=models.Index(fields=['prioridad'], name='roles_rol_priorid_5fc57a_idx'),
        ),
        migrations.AddIndex(
            model_name='rol',
            index=models.Index(fields=['tenant_id'], name='roles_rol_tenant__f47385_idx'),
        ),
        migrations.AddIndex(
            model_name='rol',
            index=models.Index(fields=['tipo_rol'], name='roles_rol_tipo_ro_2dfc79_idx'),
        ),
        migrations.AddConstraint(
            model_name='rol',
            constraint=models.UniqueConstraint(fields=('codigo', 'tenant_id'), name='unique_codigo_tenant'),
        ),
    ]
