# Generated by Django 4.2.7 on 2025-10-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("permisos", "0001_initial"),
        ("roles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rol",
            name="permisos",
            field=models.ManyToManyField(
                blank=True,
                help_text="Permisos asignados a este rol",
                related_name="roles_asignados",
                to="permisos.permiso",
                verbose_name="Permisos",
            ),
        ),
    ]
