# Generated by Django 4.2.7 on 2026-01-01 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("roles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asignacionrol",
            name="estado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="roles.estadoasignacion",
                verbose_name="Estado",
            ),
        ),
    ]
