# Generated by Django 4.2.7 on 2026-03-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roles", "0003_remove_asignacionrol_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rol",
            name="codigo",
            field=models.CharField(
                default="NUEVO_ROL",
                help_text="Código único alfanumérico del rol",
                max_length=50,
                verbose_name="Código",
            ),
        ),
        migrations.AlterField(
            model_name="rol",
            name="nombre",
            field=models.CharField(
                help_text="Nombre único del rol",
                max_length=100,
                verbose_name="Nombre del rol",
            ),
        ),
        migrations.AddConstraint(
            model_name="rol",
            constraint=models.UniqueConstraint(
                fields=("nombre", "tenant_id"), name="unique_nombre_tenant"
            ),
        ),
    ]
