# Generated by Django 5.2 on 2025-08-22 01:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionPermiso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional en formato JSON', verbose_name='Metadatos')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la condición')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código único')),
                ('tipo', models.CharField(choices=[('python', 'Código Python'), ('sql', 'Consulta SQL'), ('json', 'Configuración JSON'), ('time', 'Restricción temporal'), ('location', 'Restricción por ubicación'), ('custom', 'Personalizada')], max_length=20, verbose_name='Tipo de condición')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('configuracion', models.JSONField(blank=True, default=dict, help_text='Parámetros específicos de la condición', verbose_name='Configuración')),
                ('codigo_evaluacion', models.TextField(blank=True, help_text='Código para evaluar la condición', null=True, verbose_name='Código de evaluación')),
                ('cacheable', models.BooleanField(default=True, help_text='Si se puede cachear el resultado', verbose_name='Cacheable')),
                ('tiempo_cache', models.PositiveIntegerField(default=300, verbose_name='Tiempo de cache (segundos)')),
                ('activa', models.BooleanField(default=True, verbose_name='Condición activa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('organization', models.ForeignKey(blank=True, help_text='Organización a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organizacion')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Condición de Permiso',
                'verbose_name_plural': 'Condiciones de Permiso',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ModuloSistema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional en formato JSON', verbose_name='Metadatos')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del módulo')),
                ('codigo', models.CharField(help_text='Código único del módulo (snake_case)', max_length=50, unique=True, verbose_name='Código único')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('version', models.CharField(default='1.0.0', max_length=20, verbose_name='Versión')),
                ('icono', models.CharField(blank=True, help_text='Clase CSS del icono', max_length=100, null=True, verbose_name='Icono')),
                ('color', models.CharField(default='#6366f1', help_text='Color hexadecimal', max_length=7, verbose_name='Color')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('url_base', models.CharField(blank=True, max_length=200, null=True, verbose_name='URL base')),
                ('nivel', models.PositiveIntegerField(default=0, verbose_name='Nivel en jerarquía')),
                ('activo', models.BooleanField(default=True, verbose_name='Módulo activo')),
                ('es_sistema', models.BooleanField(default=False, verbose_name='Es módulo del sistema')),
                ('requiere_licencia', models.BooleanField(default=False, verbose_name='Requiere licencia')),
                ('configuracion_avanzada', models.JSONField(blank=True, default=dict, verbose_name='Configuración avanzada')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('organization', models.ForeignKey(blank=True, help_text='Organización a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organizacion')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='permisos.modulosistema', verbose_name='Módulo padre')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Módulo del Sistema',
                'verbose_name_plural': 'Módulos del Sistema',
                'ordering': ['nivel', 'orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional en formato JSON', verbose_name='Metadatos')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del permiso')),
                ('codigo', models.CharField(help_text='Formato: modulo.tipo.recurso (ej: payroll.view.nomina)', max_length=100, unique=True, verbose_name='Código único')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('ambito', models.CharField(choices=[('global', 'Global'), ('modulo', 'Módulo específico'), ('Organizacion', 'Organización'), ('recurso', 'Recurso específico'), ('usuario', 'Usuario específico')], default='modulo', max_length=20, verbose_name='Ámbito del permiso')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID del objeto')),
                ('es_heredable', models.BooleanField(default=True, help_text='Se hereda a través de la jerarquía de roles', verbose_name='Es heredable')),
                ('es_revocable', models.BooleanField(default=True, help_text='Se puede revocar temporalmente', verbose_name='Es revocable')),
                ('prioridad', models.PositiveIntegerField(default=0, help_text='Mayor número = mayor prioridad', verbose_name='Prioridad')),
                ('vigencia_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Inicio de vigencia')),
                ('vigencia_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fin de vigencia')),
                ('activo', models.BooleanField(default=True, verbose_name='Permiso activo')),
                ('es_sistema', models.BooleanField(default=False, verbose_name='Es del sistema')),
                ('Organizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='core.organizacion', verbose_name='Organización')),
                ('condiciones', models.ManyToManyField(blank=True, related_name='permisos', to='permisos.condicionpermiso', verbose_name='Condiciones')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de contenido')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='permisos.modulosistema', verbose_name='Módulo')),
                ('organization', models.ForeignKey(blank=True, help_text='Organización a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organizacion')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'ordering': ['modulo__orden', 'tipo_permiso__codigo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionEntorno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entorno', models.CharField(help_text='Ejemplo: dev, staging, prod', max_length=50, verbose_name='Entorno')),
                ('configuracion', models.JSONField(blank=True, default=dict, verbose_name='Configuración específica')),
                ('organization', models.ForeignKey(blank=True, help_text='Organización a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organizacion')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_entorno', to='permisos.permiso', verbose_name='Permiso')),
            ],
            options={
                'verbose_name': 'Configuración por Entorno',
                'verbose_name_plural': 'Configuraciones por Entorno',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaPermisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(help_text='Ejemplo: Crear, Editar, Eliminar', max_length=50, verbose_name='Acción realizada')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la acción')),
                ('detalles', models.JSONField(blank=True, default=dict, verbose_name='Detalles adicionales')),
                ('organization', models.ForeignKey(blank=True, help_text='Organización a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organizacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='permisos.permiso', verbose_name='Permiso')),
            ],
            options={
                'verbose_name': 'Auditoría de Permiso',
                'verbose_name_plural': 'Auditorías de Permisos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PermisoDirecto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional en formato JSON', verbose_name='Metadatos')),
                ('tipo', models.CharField(choices=[('grant', 'Concedido'), ('deny', 'Denegado'), ('temporary', 'Temporal')], default='grant', max_length=20, verbose_name='Tipo de permiso')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo de la asignación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('asignado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permisos_directos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('organization', models.ForeignKey(blank=True, help_text='Organización a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organizacion')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_directas', to='permisos.permiso', verbose_name='Permiso')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_directos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Permiso Directo',
                'verbose_name_plural': 'Permisos Directos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PermisoI18N',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(help_text='Ejemplo: es, en, fr', max_length=10, verbose_name='Idioma')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre traducido')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción traducida')),
                ('organization', models.ForeignKey(blank=True, help_text='Organización a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organizacion')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traducciones', to='permisos.permiso', verbose_name='Permiso')),
            ],
            options={
                'verbose_name': 'Permiso Internacionalizado',
                'verbose_name_plural': 'Permisos Internacionalizados',
            },
        ),
        migrations.CreateModel(
            name='TipoPermiso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional en formato JSON', verbose_name='Metadatos')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del tipo')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código único')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('crud', 'CRUD (Crear, Leer, Actualizar, Eliminar)'), ('workflow', 'Flujo de trabajo (Aprobar, Rechazar, etc.)'), ('report', 'Reportes y Análisis'), ('admin', 'Administración'), ('custom', 'Personalizado')], default='crud', max_length=20, verbose_name='Categoría')),
                ('icono', models.CharField(blank=True, max_length=100, null=True, verbose_name='Icono')),
                ('color', models.CharField(default='#6b7280', max_length=7, verbose_name='Color')),
                ('es_critico', models.BooleanField(default=False, help_text='Los permisos críticos requieren confirmación adicional', verbose_name='Es crítico')),
                ('requiere_auditoria', models.BooleanField(default=False, help_text='Se registra cada uso de este permiso', verbose_name='Requiere auditoría')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('organization', models.ForeignKey(blank=True, help_text='Organización a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organizacion')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Tipo de Permiso',
                'verbose_name_plural': 'Tipos de Permiso',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='permiso',
            name='tipo_permiso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='permisos.tipopermiso', verbose_name='Tipo de permiso'),
        ),
        migrations.AddIndex(
            model_name='condicionpermiso',
            index=models.Index(fields=['activa', 'tipo'], name='permisos_co_activa_e8aa33_idx'),
        ),
        migrations.AddIndex(
            model_name='condicionpermiso',
            index=models.Index(fields=['codigo'], name='permisos_co_codigo_ad615f_idx'),
        ),
        migrations.AddIndex(
            model_name='modulosistema',
            index=models.Index(fields=['activo', 'es_sistema'], name='permisos_mo_activo_284a09_idx'),
        ),
        migrations.AddIndex(
            model_name='modulosistema',
            index=models.Index(fields=['padre', 'activo'], name='permisos_mo_padre_i_c5513b_idx'),
        ),
        migrations.AddIndex(
            model_name='modulosistema',
            index=models.Index(fields=['codigo'], name='permisos_mo_codigo_5428c9_idx'),
        ),
        migrations.AddIndex(
            model_name='permisodirecto',
            index=models.Index(fields=['usuario', 'activo'], name='permisos_pe_usuario_98ea99_idx'),
        ),
        migrations.AddIndex(
            model_name='permisodirecto',
            index=models.Index(fields=['permiso', 'activo'], name='permisos_pe_permiso_2fe355_idx'),
        ),
        migrations.AddIndex(
            model_name='permisodirecto',
            index=models.Index(fields=['fecha_inicio', 'fecha_fin'], name='permisos_pe_fecha_i_02df62_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='permisodirecto',
            unique_together={('usuario', 'permiso')},
        ),
        migrations.AlterUniqueTogether(
            name='permisoi18n',
            unique_together={('permiso', 'idioma')},
        ),
        migrations.AddIndex(
            model_name='tipopermiso',
            index=models.Index(fields=['activo', 'categoria'], name='permisos_ti_activo_e5e492_idx'),
        ),
        migrations.AddIndex(
            model_name='tipopermiso',
            index=models.Index(fields=['codigo'], name='permisos_ti_codigo_2a5756_idx'),
        ),
        migrations.AddIndex(
            model_name='permiso',
            index=models.Index(fields=['activo', 'es_sistema'], name='permisos_pe_activo_90116e_idx'),
        ),
        migrations.AddIndex(
            model_name='permiso',
            index=models.Index(fields=['codigo'], name='permisos_pe_codigo_29b14a_idx'),
        ),
        migrations.AddIndex(
            model_name='permiso',
            index=models.Index(fields=['modulo', 'activo'], name='permisos_pe_modulo__85a103_idx'),
        ),
        migrations.AddIndex(
            model_name='permiso',
            index=models.Index(fields=['ambito', 'activo'], name='permisos_pe_ambito_fa366b_idx'),
        ),
    ]
