# Generated by Django 4.2.7 on 2026-02-05 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0007_rename_core_searc_user_id_7e0f95_idx_core_search_user_id_287ae0_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrupoUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organización a la que pertenece este registro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organizacion",
                    ),
                ),
                (
                    "usuarios",
                    models.ManyToManyField(
                        blank=True,
                        related_name="grupos_usuario",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuarios",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupo de Usuario",
                "verbose_name_plural": "Grupos de Usuario",
                "ordering": ["nombre"],
            },
        ),
    ]
