# Generated by Django 4.2.7 on 2026-01-01 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_logauditoria_objeto_id"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historialusuario",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organización a la que pertenece este registro",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organizacion",
            ),
        ),
    ]
