# Generated by Django 5.2 on 2025-06-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Código'),
        ),
    ]
