# Generated by Django 5.2 on 2025-06-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_municipio_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código'),
        ),
    ]
