# Generated by Django 4.2.7 on 2026-01-10 21:18

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfiguracionSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        verbose_name="Fecha de modificación",
                    ),
                ),
                (
                    "clave",
                    models.CharField(
                        help_text="Clave identificadora de la configuración",
                        max_length=100,
                        unique=True,
                        verbose_name="Clave",
                    ),
                ),
                (
                    "valor",
                    models.TextField(
                        help_text="Valor de la configuración", verbose_name="Valor"
                    ),
                ),
                (
                    "tipo_dato",
                    models.CharField(
                        choices=[
                            ("string", "Texto"),
                            ("integer", "Número entero"),
                            ("float", "Número decimal"),
                            ("boolean", "Verdadero/Falso"),
                            ("json", "JSON"),
                        ],
                        default="string",
                        max_length=20,
                        verbose_name="Tipo de dato",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Descripción de para qué sirve esta configuración",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "activa",
                    models.BooleanField(
                        default=True,
                        help_text="Si la configuración está activa",
                        verbose_name="Activa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración del Sistema",
                "verbose_name_plural": "Configuraciones del Sistema",
                "ordering": ["clave"],
            },
        ),
        migrations.CreateModel(
            name="LogAuditoria",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        verbose_name="Fecha de modificación",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "accion",
                    models.CharField(
                        help_text="Acción realizada",
                        max_length=100,
                        verbose_name="Acción",
                    ),
                ),
                (
                    "modelo",
                    models.CharField(
                        help_text="Modelo afectado",
                        max_length=100,
                        verbose_name="Modelo",
                    ),
                ),
                (
                    "objeto_id",
                    models.CharField(
                        blank=True,
                        help_text="ID del objeto afectado",
                        max_length=100,
                        null=True,
                        verbose_name="ID del objeto",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dirección IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "datos_antes",
                    models.JSONField(
                        blank=True,
                        help_text="Estado del objeto antes del cambio",
                        null=True,
                        verbose_name="Datos antes",
                    ),
                ),
                (
                    "datos_despues",
                    models.JSONField(
                        blank=True,
                        help_text="Estado del objeto después del cambio",
                        null=True,
                        verbose_name="Datos después",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadatos adicionales"
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Auditoría",
                "verbose_name_plural": "Logs de Auditoría",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        default="Notificación",
                        help_text="Título de la notificación",
                        max_length=200,
                        verbose_name="Título",
                    ),
                ),
                (
                    "mensaje",
                    models.TextField(
                        help_text="Contenido de la notificación", verbose_name="Mensaje"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("info", "Información"),
                            ("success", "Éxito"),
                            ("warning", "Advertencia"),
                            ("error", "Error"),
                            ("system", "Sistema"),
                        ],
                        default="info",
                        help_text="Tipo de notificación",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "leida",
                    models.BooleanField(
                        default=False,
                        help_text="Si la notificación ha sido leída",
                        verbose_name="Leída",
                    ),
                ),
                (
                    "fecha_leida",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de lectura"
                    ),
                ),
                (
                    "url_accion",
                    models.URLField(
                        blank=True,
                        help_text="URL a la que redirigir cuando se hace clic",
                        verbose_name="URL de acción",
                    ),
                ),
                (
                    "icono",
                    models.CharField(
                        blank=True,
                        help_text="Clase CSS del icono a mostrar",
                        max_length=50,
                        verbose_name="Icono",
                    ),
                ),
                (
                    "datos_adicionales",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Información adicional en formato JSON",
                        verbose_name="Datos adicionales",
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                ("mensaje", models.TextField(verbose_name="Mensaje")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("info", "Información"),
                            ("warning", "Advertencia"),
                            ("error", "Error"),
                            ("success", "Éxito"),
                        ],
                        default="info",
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("sistema", "Sistema"),
                            ("payroll", "Nómina"),
                            ("prestamos", "Préstamos"),
                            ("contabilidad", "Contabilidad"),
                            ("dashboard", "Dashboard"),
                            ("usuarios", "Usuarios"),
                            ("seguridad", "Seguridad"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=15,
                        verbose_name="Categoría",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Leída")),
                (
                    "fecha_leida",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de lectura"
                    ),
                ),
                (
                    "url_accion",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="URL de acción"
                    ),
                ),
                (
                    "texto_accion",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Texto del botón de acción",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Datos adicionales"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de expiración"
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Organizacion",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        verbose_name="Fecha de modificación",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre completo de la organización",
                        max_length=200,
                        unique=True,
                        verbose_name="Nombre de la organización",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código identificador único de la organización",
                        max_length=50,
                        unique=True,
                        verbose_name="Código único",
                    ),
                ),
                (
                    "razon_social",
                    models.CharField(
                        blank=True,
                        help_text="Razón social legal de la organización",
                        max_length=250,
                        verbose_name="Razón social",
                    ),
                ),
                (
                    "nit",
                    models.CharField(
                        blank=True,
                        help_text="Número de identificación tributaria",
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="NIT",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email de contacto principal",
                        max_length=254,
                        verbose_name="Email principal",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True,
                        help_text="Teléfono de contacto principal",
                        max_length=20,
                        verbose_name="Teléfono",
                    ),
                ),
                (
                    "direccion",
                    models.TextField(
                        blank=True,
                        help_text="Dirección física de la organización",
                        verbose_name="Dirección",
                    ),
                ),
                (
                    "activa",
                    models.BooleanField(
                        default=True,
                        help_text="Si está activa, la organización puede operar en el sistema",
                        verbose_name="Organización activa",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Logo de la organización",
                        null=True,
                        upload_to="organizaciones/logos/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "configuracion",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Configuraciones personalizadas en formato JSON",
                        verbose_name="Configuración específica",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Información adicional en formato JSON",
                        verbose_name="Metadatos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organización",
                "verbose_name_plural": "Organizaciones",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único de la organización",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre completo de la organización o empresa",
                        max_length=200,
                        verbose_name="Nombre de la organización",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Identificador único para URL (ej: empresa.cortesec.com)",
                        unique=True,
                        verbose_name="Slug/Subdominio",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Nombre corto para mostrar en la interfaz",
                        max_length=100,
                        verbose_name="Nombre para mostrar",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción de la organización y su actividad",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email principal de la organización",
                        max_length=254,
                        verbose_name="Email de contacto",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Teléfono de contacto principal",
                        max_length=20,
                        verbose_name="Teléfono",
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="Sitio web oficial de la organización",
                        verbose_name="Sitio web",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="Dirección física de la organización",
                        verbose_name="Dirección",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="Ciudad donde se ubica la organización",
                        max_length=100,
                        verbose_name="Ciudad",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        help_text="Estado o provincia",
                        max_length=100,
                        verbose_name="Estado/Provincia",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="País donde opera la organización",
                        max_length=100,
                        verbose_name="País",
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        help_text="Código postal o ZIP",
                        max_length=20,
                        verbose_name="Código postal",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("FREE", "Gratuito"),
                            ("BASIC", "Básico"),
                            ("PRO", "Profesional"),
                            ("ENTERPRISE", "Empresarial"),
                        ],
                        default="FREE",
                        help_text="Plan actual de la organización",
                        max_length=20,
                        verbose_name="Plan de suscripción",
                    ),
                ),
                (
                    "max_users",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Número máximo de usuarios permitidos",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                        verbose_name="Máximo de usuarios",
                    ),
                ),
                (
                    "max_storage_mb",
                    models.PositiveIntegerField(
                        default=1024,
                        help_text="Espacio de almacenamiento máximo en megabytes",
                        validators=[django.core.validators.MinValueValidator(100)],
                        verbose_name="Almacenamiento máximo (MB)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Si la organización está activa y operativa",
                        verbose_name="Activa",
                    ),
                ),
                (
                    "is_trial",
                    models.BooleanField(
                        default=True,
                        help_text="Si la organización está en periodo de prueba",
                        verbose_name="En periodo de prueba",
                    ),
                ),
                (
                    "trial_ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora cuando termina el periodo de prueba",
                        null=True,
                        verbose_name="Fin del periodo de prueba",
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Configuraciones específicas de la organización",
                        verbose_name="Configuraciones",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Logo de la organización",
                        null=True,
                        upload_to="organizations/logos/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#007bff",
                        help_text="Color primario para la interfaz (formato hex)",
                        max_length=7,
                        verbose_name="Color primario",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="America/Bogota",
                        help_text="Zona horaria predeterminada",
                        max_length=50,
                        verbose_name="Zona horaria",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="es",
                        help_text="Idioma predeterminado",
                        max_length=10,
                        verbose_name="Idioma",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="COP",
                        help_text="Moneda predeterminada (código ISO)",
                        max_length=3,
                        verbose_name="Moneda",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha y hora de creación de la organización",
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha y hora de la última actualización",
                        verbose_name="Última actualización",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organización",
                "verbose_name_plural": "Organizaciones",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email de la persona a invitar",
                        max_length=254,
                        verbose_name="Email del invitado",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrador"),
                            ("MANAGER", "Gerente"),
                            ("MEMBER", "Miembro"),
                            ("VIEWER", "Visualizador"),
                        ],
                        default="MEMBER",
                        help_text="Rol que tendrá el usuario en la organización",
                        max_length=20,
                        verbose_name="Rol propuesto",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Mensaje opcional para incluir en la invitación",
                        verbose_name="Mensaje personalizado",
                    ),
                ),
                (
                    "is_accepted",
                    models.BooleanField(
                        default=False,
                        help_text="Si la invitación ha sido aceptada",
                        verbose_name="Aceptada",
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora cuando se aceptó la invitación",
                        null=True,
                        verbose_name="Fecha de aceptación",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Fecha y hora cuando expira la invitación",
                        verbose_name="Fecha de expiración",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Invitación a organización",
                "verbose_name_plural": "Invitaciones a organización",
            },
        ),
    ]
