# Generated by Django 5.2 on 2025-08-22 01:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Fecha de modificación')),
                ('clave', models.CharField(help_text='Clave identificadora de la configuración', max_length=100, unique=True, verbose_name='Clave')),
                ('valor', models.TextField(help_text='Valor de la configuración', verbose_name='Valor')),
                ('tipo_dato', models.CharField(choices=[('string', 'Texto'), ('integer', 'Número entero'), ('float', 'Número decimal'), ('boolean', 'Verdadero/Falso'), ('json', 'JSON')], default='string', max_length=20, verbose_name='Tipo de dato')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de para qué sirve esta configuración', verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, help_text='Si la configuración está activa', verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
                'ordering': ['clave'],
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Fecha de modificación')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accion', models.CharField(help_text='Acción realizada', max_length=100, verbose_name='Acción')),
                ('modelo', models.CharField(help_text='Modelo afectado', max_length=100, verbose_name='Modelo')),
                ('objeto_id', models.CharField(help_text='ID del objeto afectado', max_length=100, verbose_name='ID del objeto')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('datos_antes', models.JSONField(blank=True, help_text='Estado del objeto antes del cambio', null=True, verbose_name='Datos antes')),
                ('datos_despues', models.JSONField(blank=True, help_text='Estado del objeto después del cambio', null=True, verbose_name='Datos después')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos adicionales')),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Notificación', help_text='Título de la notificación', max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(help_text='Contenido de la notificación', verbose_name='Mensaje')),
                ('tipo', models.CharField(choices=[('info', 'Información'), ('success', 'Éxito'), ('warning', 'Advertencia'), ('error', 'Error'), ('system', 'Sistema')], default='info', help_text='Tipo de notificación', max_length=20, verbose_name='Tipo')),
                ('leida', models.BooleanField(default=False, help_text='Si la notificación ha sido leída', verbose_name='Leída')),
                ('fecha_leida', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura')),
                ('url_accion', models.URLField(blank=True, help_text='URL a la que redirigir cuando se hace clic', verbose_name='URL de acción')),
                ('icono', models.CharField(blank=True, help_text='Clase CSS del icono a mostrar', max_length=50, verbose_name='Icono')),
                ('datos_adicionales', models.JSONField(blank=True, default=dict, help_text='Información adicional en formato JSON', verbose_name='Datos adicionales')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('tipo', models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('error', 'Error'), ('success', 'Éxito')], default='info', max_length=10, verbose_name='Tipo')),
                ('categoria', models.CharField(choices=[('sistema', 'Sistema'), ('payroll', 'Nómina'), ('prestamos', 'Préstamos'), ('contabilidad', 'Contabilidad'), ('dashboard', 'Dashboard'), ('usuarios', 'Usuarios'), ('seguridad', 'Seguridad'), ('general', 'General')], default='general', max_length=15, verbose_name='Categoría')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('fecha_leida', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura')),
                ('url_accion', models.CharField(blank=True, max_length=500, verbose_name='URL de acción')),
                ('texto_accion', models.CharField(blank=True, max_length=100, verbose_name='Texto del botón de acción')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Datos adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de expiración')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Fecha de modificación')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre completo de la organización', max_length=200, unique=True, verbose_name='Nombre de la organización')),
                ('codigo', models.CharField(help_text='Código identificador único de la organización', max_length=50, unique=True, verbose_name='Código único')),
                ('razon_social', models.CharField(blank=True, help_text='Razón social legal de la organización', max_length=250, verbose_name='Razón social')),
                ('nit', models.CharField(blank=True, help_text='Número de identificación tributaria', max_length=20, null=True, unique=True, verbose_name='NIT')),
                ('email', models.EmailField(blank=True, help_text='Email de contacto principal', max_length=254, verbose_name='Email principal')),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto principal', max_length=20, verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, help_text='Dirección física de la organización', verbose_name='Dirección')),
                ('activa', models.BooleanField(default=True, help_text='Si está activa, la organización puede operar en el sistema', verbose_name='Organización activa')),
                ('logo', models.ImageField(blank=True, help_text='Logo de la organización', null=True, upload_to='organizaciones/logos/', verbose_name='Logo')),
                ('configuracion', models.JSONField(blank=True, default=dict, help_text='Configuraciones personalizadas en formato JSON', verbose_name='Configuración específica')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional en formato JSON', verbose_name='Metadatos')),
            ],
            options={
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organizaciones',
                'ordering': ['nombre'],
            },
        ),
    ]
