# Generated by Django 4.2.7 on 2026-01-10 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationinvitation",
            name="accepted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que aceptó la invitación",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accepted_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organizationinvitation",
            name="invited_by",
            field=models.ForeignKey(
                help_text="Usuario que envió la invitación",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organizationinvitation",
            name="organization",
            field=models.ForeignKey(
                help_text="Organización que envía la invitación",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="core.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["slug"], name="core_organi_slug_517c11_idx"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["is_active"], name="core_organi_is_acti_9518a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["plan"], name="core_organi_plan_a11d8a_idx"),
        ),
        migrations.AddField(
            model_name="organizacion",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="organizacion",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="core.organizacion",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AddField(
            model_name="notificacion",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notificaciones",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AddField(
            model_name="logauditoria",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AddField(
            model_name="configuracionsistema",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="configuracionsistema",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddIndex(
            model_name="organizationinvitation",
            index=models.Index(fields=["email"], name="core_organi_email_4aad5a_idx"),
        ),
        migrations.AddIndex(
            model_name="organizationinvitation",
            index=models.Index(
                fields=["expires_at"], name="core_organi_expires_7843e2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="organizationinvitation",
            unique_together={("organization", "email")},
        ),
        migrations.AddIndex(
            model_name="organizacion",
            index=models.Index(fields=["codigo"], name="core_organi_codigo_c4ca52_idx"),
        ),
        migrations.AddIndex(
            model_name="organizacion",
            index=models.Index(fields=["activa"], name="core_organi_activa_978b23_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["organization", "usuario", "is_read"],
                name="core_notifi_organiz_855785_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["tipo", "categoria"], name="core_notifi_tipo_465aea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["created_at"], name="core_notifi_created_d0c445_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificacion",
            index=models.Index(
                fields=["usuario", "leida"], name="core_notifi_usuario_c30a38_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificacion",
            index=models.Index(fields=["tipo"], name="core_notifi_tipo_d45161_idx"),
        ),
        migrations.AddIndex(
            model_name="notificacion",
            index=models.Index(fields=["fecha"], name="core_notifi_fecha_fa2c60_idx"),
        ),
        migrations.AddIndex(
            model_name="logauditoria",
            index=models.Index(
                fields=["usuario", "created_at"], name="core_logaud_usuario_caec05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="logauditoria",
            index=models.Index(
                fields=["modelo", "accion"], name="core_logaud_modelo_afdfdb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="logauditoria",
            index=models.Index(
                fields=["ip_address"], name="core_logaud_ip_addr_b3bcc8_idx"
            ),
        ),
    ]
