# Generated by Django 4.2.7 on 2026-01-24 03:56

from django.db import migrations, models
from django.utils.text import slugify


def _unique_slug(base_slug, existing_slugs):
    if base_slug not in existing_slugs:
        return base_slug
    idx = 1
    while f"{base_slug}-{idx}" in existing_slugs:
        idx += 1
    return f"{base_slug}-{idx}"


def migrate_organization_to_organizacion(apps, schema_editor):
    Organizacion = apps.get_model("core", "Organizacion")
    Organization = apps.get_model("core", "Organization")

    existing_slugs = set(
        Organizacion.objects.exclude(slug__isnull=True).exclude(slug="").values_list("slug", flat=True)
    )

    for org in Organization.objects.all():
        base_slug = org.slug or slugify(org.name or "org")
        slug = _unique_slug(base_slug, existing_slugs)
        existing_slugs.add(slug)

        codigo = (slug or (org.name or "ORG")).upper()[:50]

        existing = (
            Organizacion.objects.filter(slug__iexact=slug).first()
            or Organizacion.objects.filter(codigo__iexact=codigo).first()
            or Organizacion.objects.filter(nombre__iexact=org.name).first()
        )

        data = {
            "nombre": org.name,
            "codigo": codigo,
            "slug": slug,
            "razon_social": org.display_name or "",
            "email": org.email or "",
            "telefono": org.phone or "",
            "website": org.website or "",
            "direccion": org.address or "",
            "city": org.city or "",
            "state": org.state or "",
            "country": org.country or "",
            "postal_code": org.postal_code or "",
            "activa": org.is_active,
            "plan": org.plan,
            "max_users": org.max_users,
            "max_storage_mb": org.max_storage_mb,
            "is_trial": org.is_trial,
            "trial_ends_at": org.trial_ends_at,
            "primary_color": org.primary_color or "#007bff",
            "settings": org.settings or {},
        }

        if existing:
            for key, value in data.items():
                current = getattr(existing, key, None)
                if current in [None, "", {}, []]:
                    setattr(existing, key, value)
            # Guardar descripción en metadata si existe
            if org.description:
                existing.metadata = existing.metadata or {}
                existing.metadata.setdefault("description", org.description)
            if org.display_name:
                existing.metadata = existing.metadata or {}
                existing.metadata.setdefault("display_name", org.display_name)
            existing.save()
        else:
            metadata = {}
            if org.description:
                metadata["description"] = org.description
            if org.display_name:
                metadata["display_name"] = org.display_name
            Organizacion.objects.create(
                **data,
                metadata=metadata
            )


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="organizationinvitation",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="organizationinvitation",
            name="accepted_by",
        ),
        migrations.RemoveField(
            model_name="organizationinvitation",
            name="invited_by",
        ),
        migrations.RemoveField(
            model_name="organizationinvitation",
            name="organization",
        ),
        migrations.AddField(
            model_name="organizacion",
            name="city",
            field=models.CharField(
                blank=True,
                help_text="Ciudad donde se ubica la organización",
                max_length=100,
                verbose_name="Ciudad",
            ),
        ),
        migrations.AddField(
            model_name="organizacion",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="País donde opera la organización",
                max_length=100,
                verbose_name="País",
            ),
        ),
        migrations.AddField(
            model_name="organizacion",
            name="is_trial",
            field=models.BooleanField(
                default=True,
                help_text="Si la organización está en periodo de prueba",
                verbose_name="En periodo de prueba",
            ),
        ),
        migrations.AddField(
            model_name="organizacion",
            name="max_storage_mb",
            field=models.PositiveIntegerField(
                default=1024,
                help_text="Espacio de almacenamiento máximo en MB",
                verbose_name="Almacenamiento máximo (MB)",
            ),
        ),
        migrations.AddField(
            model_name="organizacion",
            name="max_users",
            field=models.PositiveIntegerField(
                default=5,
                help_text="Número máximo de usuarios permitidos",
                verbose_name="Máximo de usuarios",
            ),
        ),
        migrations.AddField(
            model_name="organizacion",
            name="plan",
            field=models.CharField(
                choices=[
                    ("FREE", "Gratuito"),
                    ("BASIC", "Básico"),
                    ("PRO", "Profesional"),
                    ("ENTERPRISE", "Empresarial"),
                ],
                default="FREE",
                help_text="Plan actual de la organización",
                max_length=20,
                verbose_name="Plan de suscripción",
            ),
        ),
        migrations.AddField(
            model_name="organizacion",
            name="postal_code",
            field=models.CharField(
                blank=True,
                help_text="Código postal o ZIP",
                max_length=20,
                verbose_name="Código postal",
            ),
        ),
        migrations.AddField(
            model_name="organizacion",
            name="primary_color",
            field=models.CharField(
                default="#007bff",
                help_text="Color principal para branding",
                max_length=7,
                verbose_name="Color primario",
            ),
        ),
        migrations.AddField(
            model_name="organizacion",
            name="settings",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Configuraciones SaaS adicionales en formato JSON",
                verbose_name="Settings SaaS",
            ),
        ),
        migrations.AddField(
            model_name="organizacion",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Identificador único para URL/subdominio (ej: empresa)",
                unique=True,
                verbose_name="Slug/Subdominio",
            ),
        ),
        migrations.AddField(
            model_name="organizacion",
            name="state",
            field=models.CharField(
                blank=True,
                help_text="Estado o provincia",
                max_length=100,
                verbose_name="Estado/Provincia",
            ),
        ),
        migrations.AddField(
            model_name="organizacion",
            name="trial_ends_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha y hora cuando termina el periodo de prueba",
                null=True,
                verbose_name="Fin del periodo de prueba",
            ),
        ),
        migrations.AddField(
            model_name="organizacion",
            name="website",
            field=models.URLField(
                blank=True,
                help_text="Sitio web oficial de la organización",
                verbose_name="Sitio web",
            ),
        ),
        migrations.RunPython(migrate_organization_to_organizacion, reverse_noop),
        migrations.DeleteModel(
            name="Organization",
        ),
        migrations.DeleteModel(
            name="OrganizationInvitation",
        ),
    ]
