# Generated by Django 4.x on 2026-01-23
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_organizationinvitation_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Fecha de modificación')),
                ('code', models.CharField(help_text='Identificador único del plan (ej: FREE, PRO)', max_length=30, unique=True, verbose_name='Código')),
                ('name', models.CharField(help_text='Nombre visible del plan', max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, help_text='Descripción corta del plan', verbose_name='Descripción')),
                ('price_monthly_cop', models.PositiveIntegerField(blank=True, help_text='Valor mensual en COP. Nulo para cotización.', null=True, verbose_name='Precio mensual (COP)')),
                ('price_yearly_cop', models.PositiveIntegerField(blank=True, help_text='Valor anual en COP. Nulo para cotización.', null=True, verbose_name='Precio anual (COP)')),
                ('max_users', models.PositiveIntegerField(default=5, help_text='Límite de usuarios permitidos', verbose_name='Máximo de usuarios')),
                ('max_storage_mb', models.PositiveIntegerField(default=1024, help_text='Límite de almacenamiento en MB', verbose_name='Almacenamiento máximo (MB)')),
                ('features', models.JSONField(blank=True, default=list, help_text='Lista de características del plan', verbose_name='Características')),
                ('is_public', models.BooleanField(default=True, help_text='Mostrar en la landing pública', verbose_name='Visible en landing')),
                ('is_active', models.BooleanField(default=True, help_text='Plan activo para asignación', verbose_name='Activo')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Orden de visualización en la landing', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['sort_order', 'price_monthly_cop', 'name'],
            },
        ),
    ]
