# Generated by Django 4.2.7 on 2025-12-31 23:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_organization_organizationinvitation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logauditoria",
            name="objeto_id",
            field=models.CharField(
                blank=True,
                help_text="ID del objeto afectado",
                max_length=100,
                null=True,
                verbose_name="ID del objeto",
            ),
        ),
    ]
