# Generated by Django 4.x on 2026-01-23
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_plan_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Fecha de modificación')),
                ('previous_plan', models.CharField(blank=True, max_length=30, verbose_name='Plan anterior')),
                ('new_plan', models.CharField(blank=True, max_length=30, verbose_name='Plan nuevo')),
                ('previous_limits', models.JSONField(blank=True, default=dict, verbose_name='Límites anteriores')),
                ('new_limits', models.JSONField(blank=True, default=dict, verbose_name='Límites nuevos')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Nota')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_changes', to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_changes', to='core.organizacion', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Cambio de plan',
                'verbose_name_plural': 'Cambios de plan',
                'ordering': ['-created_at'],
            },
        ),
    ]
