# Generated by Django 4.x on 2026-01-24
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_plan_change_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Fecha de modificación')),
                ('query', models.CharField(max_length=255, verbose_name='Búsqueda')),
                ('module', models.CharField(default='all', max_length=50, verbose_name='Módulo')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='Filtros')),
                ('results_count', models.PositiveIntegerField(default=0, verbose_name='Cantidad de resultados')),
                ('execution_time_ms', models.FloatField(default=0, verbose_name='Tiempo de ejecución (ms)')),
                ('clicked_result', models.BooleanField(default=False, verbose_name='Resultado clickeado')),
                ('last_clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='Último click')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Búsqueda',
                'verbose_name_plural': 'Historial de búsquedas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Fecha de modificación')),
                ('result_id', models.CharField(blank=True, max_length=100, verbose_name='ID resultado')),
                ('result_type', models.CharField(blank=True, max_length=50, verbose_name='Tipo resultado')),
                ('module', models.CharField(blank=True, max_length=50, verbose_name='Módulo')),
                ('position', models.PositiveIntegerField(blank=True, null=True, verbose_name='Posición')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='URL')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='core.searchhistory', verbose_name='Búsqueda')),
            ],
            options={
                'verbose_name': 'Click de búsqueda',
                'verbose_name_plural': 'Clicks de búsqueda',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['user', 'created_at'], name='core_searc_user_id_7e0f95_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['query'], name='core_searc_query_6b0f1a_idx'),
        ),
    ]
