# Generated by Django 4.2.7 on 2026-01-27 02:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_search_history_and_clicks"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="searchhistory",
            new_name="core_search_user_id_287ae0_idx",
            old_name="core_searc_user_id_7e0f95_idx",
        ),
        migrations.RenameIndex(
            model_name="searchhistory",
            new_name="core_search_query_4a6777_idx",
            old_name="core_searc_query_6b0f1a_idx",
        ),
    ]
