# Generated by Django 4.2.7 on 2026-02-16 23:52

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "core",
            "0007_rename_core_searc_user_id_7e0f95_idx_core_search_user_id_287ae0_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitacion",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        verbose_name="Fecha de modificación",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email al que se envía la invitación",
                        max_length=254,
                        verbose_name="Email del invitado",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrador"),
                            ("MANAGER", "Gerente"),
                            ("MEMBER", "Miembro"),
                            ("VIEWER", "Visor"),
                        ],
                        default="MEMBER",
                        help_text="Rol que tendrá el usuario al aceptar la invitación",
                        max_length=20,
                        verbose_name="Rol asignado",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="Token único para validar la invitación",
                        max_length=64,
                        unique=True,
                        verbose_name="Token de invitación",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("ACCEPTED", "Aceptada"),
                            ("EXPIRED", "Expirada"),
                            ("CANCELLED", "Cancelada"),
                        ],
                        default="PENDING",
                        help_text="Estado actual de la invitación",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "mensaje",
                    models.TextField(
                        blank=True,
                        help_text="Mensaje opcional del invitador",
                        verbose_name="Mensaje personalizado",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=core.models._default_invitation_expiry,
                        help_text="Fecha y hora en que expira la invitación",
                        verbose_name="Fecha de expiración",
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de aceptación"
                    ),
                ),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitaciones_aceptadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aceptada por",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitaciones_enviadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Invitado por",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitaciones",
                        to="core.organizacion",
                        verbose_name="Organización",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invitación",
                "verbose_name_plural": "Invitaciones",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["token"], name="core_invita_token_fb7458_idx"),
                    models.Index(fields=["email"], name="core_invita_email_039451_idx"),
                    models.Index(
                        fields=["organization", "estado"],
                        name="core_invita_organiz_b5a261_idx",
                    ),
                ],
                "unique_together": {("organization", "email", "estado")},
            },
        ),
    ]
