# Generated by Django 4.2.7 on 2026-02-27 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_seed_plans_and_convert_fk"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="notificacion",
            name="core_notifi_usuario_c30a38_idx",
        ),
        migrations.RemoveIndex(
            model_name="notificacion",
            name="core_notifi_tipo_d45161_idx",
        ),
        migrations.AddField(
            model_name="notificacion",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("nomina", "Nómina"),
                    ("prestamos", "Préstamos"),
                    ("contratos", "Contratos"),
                    ("empleados", "Empleados"),
                    ("contabilidad", "Contabilidad"),
                    ("proyectos", "Proyectos"),
                    ("seguridad", "Seguridad"),
                    ("sistema", "Sistema"),
                ],
                default="general",
                help_text="Categoría para agrupación y filtrado",
                max_length=20,
                verbose_name="Categoría",
            ),
        ),
        migrations.AddField(
            model_name="notificacion",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="La notificación se eliminará automáticamente después de esta fecha",
                null=True,
                verbose_name="Fecha de expiración",
            ),
        ),
        migrations.AddField(
            model_name="notificacion",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organización a la que pertenece esta notificación",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notificaciones_org",
                to="core.organizacion",
                verbose_name="Organización",
            ),
        ),
        migrations.AddField(
            model_name="notificacion",
            name="origen_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="ID del objeto que generó la notificación",
                max_length=100,
                verbose_name="ID de origen",
            ),
        ),
        migrations.AddField(
            model_name="notificacion",
            name="origen_tipo",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Modelo que generó la notificación (ej: 'nomina', 'prestamo')",
                max_length=50,
                verbose_name="Tipo de origen",
            ),
        ),
        migrations.AddField(
            model_name="notificacion",
            name="prioridad",
            field=models.CharField(
                choices=[
                    ("baja", "Baja"),
                    ("normal", "Normal"),
                    ("alta", "Alta"),
                    ("urgente", "Urgente"),
                ],
                default="normal",
                help_text="Nivel de prioridad de la notificación",
                max_length=10,
                verbose_name="Prioridad",
            ),
        ),
        migrations.AddField(
            model_name="notificacion",
            name="texto_accion",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Texto del botón de acción (ej: 'Ver nómina')",
                max_length=100,
                verbose_name="Texto del botón de acción",
            ),
        ),
        migrations.AlterField(
            model_name="notificacion",
            name="url_accion",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Ruta a la que redirigir cuando se hace clic (ej: /dashboard/nomina)",
                max_length=500,
                verbose_name="URL de acción",
            ),
        ),
        migrations.AddIndex(
            model_name="notificacion",
            index=models.Index(
                fields=["organization", "usuario", "leida"],
                name="core_notifi_organiz_9e319f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificacion",
            index=models.Index(
                fields=["tipo", "categoria"], name="core_notifi_tipo_f8578b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificacion",
            index=models.Index(
                fields=["prioridad"], name="core_notifi_priorid_5bb5f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificacion",
            index=models.Index(
                fields=["expires_at"], name="core_notifi_expires_fc6d50_idx"
            ),
        ),
    ]
