# Generated by Django 5.2.5 on 2026-02-27 01:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_notificacion_unified_model"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="notificacion",
            name="core_notifi_fecha_fa2c60_idx",
        ),
    ]
