# Generated by Django 5.2.5 on 2026-02-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_remove_notificacion_core_notifi_fecha_fa2c60_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitacion",
            name="rbac_rol_id",
            field=models.IntegerField(
                blank=True,
                help_text="ID del rol del sistema de roles/permisos que se asignará al aceptar",
                null=True,
                verbose_name="Rol RBAC",
            ),
        ),
        migrations.AlterField(
            model_name="invitacion",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrador"),
                    ("MANAGER", "Gerente"),
                    ("MEMBER", "Miembro"),
                    ("VIEWER", "Visor"),
                ],
                default="MEMBER",
                help_text="Nivel de acceso organizacional del usuario",
                max_length=20,
                verbose_name="Nivel de acceso",
            ),
        ),
    ]
