# Generated by Django 5.2 on 2025-06-30 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre único del módulo del sistema', max_length=100, unique=True, verbose_name='Nombre del módulo')),
                ('codigo', models.CharField(help_text='Código único del módulo (ej: payroll, prestamos)', max_length=50, unique=True, verbose_name='Código')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del módulo', null=True, verbose_name='Descripción')),
                ('icono', models.CharField(blank=True, help_text='Clase CSS del icono (ej: fas fa-users)', max_length=100, null=True, verbose_name='Icono')),
                ('url_base', models.CharField(blank=True, help_text='URL base del módulo', max_length=200, null=True, verbose_name='URL base')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización en el menú', verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, help_text='Si está activo, el módulo estará disponible', verbose_name='Activo')),
                ('es_sistema', models.BooleanField(default=False, help_text='Los módulos del sistema no se pueden eliminar', verbose_name='Es del sistema')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('view', 'Ver'), ('add', 'Crear'), ('change', 'Editar'), ('delete', 'Eliminar'), ('export', 'Exportar'), ('import', 'Importar'), ('approve', 'Aprobar'), ('reject', 'Rechazar'), ('custom', 'Personalizado')], help_text='Código único del tipo de permiso', max_length=50, unique=True, verbose_name='Código del tipo')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del tipo de permiso', max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del tipo de permiso', null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Permiso',
                'verbose_name_plural': 'Tipos de Permiso',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del permiso específico', max_length=200, verbose_name='Nombre del permiso')),
                ('codigo', models.CharField(help_text='Código único del permiso (ej: payroll.view_nomina)', max_length=100, unique=True, verbose_name='Código')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del permiso', null=True, verbose_name='Descripción')),
                ('vista_asociada', models.CharField(blank=True, help_text='Nombre de la vista o función asociada', max_length=200, null=True, verbose_name='Vista asociada')),
                ('activo', models.BooleanField(default=True, help_text='Si está activo, el permiso estará disponible', verbose_name='Activo')),
                ('tiene_restriccion_horario', models.BooleanField(default=False, help_text='Si está activo, se aplicarán restricciones de horario', verbose_name='Tiene restricción de horario')),
                ('hora_inicio', models.TimeField(blank=True, help_text='Hora de inicio para usar este permiso', null=True, verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(blank=True, help_text='Hora de fin para usar este permiso', null=True, verbose_name='Hora de fin')),
                ('fecha_inicio_vigencia', models.DateField(blank=True, null=True, verbose_name='Fecha inicio vigencia')),
                ('fecha_fin_vigencia', models.DateField(blank=True, null=True, verbose_name='Fecha fin vigencia')),
                ('es_sistema', models.BooleanField(default=False, help_text='Los permisos del sistema no se pueden eliminar', verbose_name='Es del sistema')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='permisos.modulo', verbose_name='Módulo')),
                ('tipo_permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='permisos.tipopermiso', verbose_name='Tipo de permiso')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'ordering': ['modulo__orden', 'tipo_permiso__codigo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Si está activo, el rol tiene este permiso', verbose_name='Activo')),
                ('fecha_inicio', models.DateTimeField(blank=True, help_text='Fecha desde la cual el permiso es válido para el rol', null=True, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, help_text='Fecha hasta la cual el permiso es válido para el rol', null=True, verbose_name='Fecha de fin')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre la asignación', null=True, verbose_name='Observaciones')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_permiso', to='permisos.permiso', verbose_name='Permiso')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_rol', to='roles.rol', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Rol - Permiso',
                'verbose_name_plural': 'Roles - Permisos',
                'ordering': ['rol__nombre', 'permiso__modulo__orden'],
                'indexes': [models.Index(fields=['rol', 'activo'], name='permisos_ro_rol_id_32fcc4_idx'), models.Index(fields=['permiso', 'activo'], name='permisos_ro_permiso_749cba_idx')],
                'unique_together': {('rol', 'permiso')},
            },
        ),
        migrations.AddIndex(
            model_name='permiso',
            index=models.Index(fields=['activo'], name='permisos_pe_activo_ad28b4_idx'),
        ),
        migrations.AddIndex(
            model_name='permiso',
            index=models.Index(fields=['codigo'], name='permisos_pe_codigo_29b14a_idx'),
        ),
        migrations.AddIndex(
            model_name='permiso',
            index=models.Index(fields=['modulo', 'activo'], name='permisos_pe_modulo__85a103_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='permiso',
            unique_together={('modulo', 'tipo_permiso', 'codigo')},
        ),
    ]
