# Generated by Django 4.2.7 on 2026-03-13 02:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_add_rbac_rol_to_invitacion"),
        ("documentacion", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoriadocumento",
            name="nombre",
            field=models.CharField(
                max_length=100, verbose_name="Nombre de la categoría"
            ),
        ),
        migrations.AlterField(
            model_name="documento",
            name="archivo",
            field=models.FileField(
                help_text="Archivo del documento",
                upload_to="documentacion/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "pdf",
                            "doc",
                            "docx",
                            "xls",
                            "xlsx",
                            "csv",
                            "txt",
                            "png",
                            "jpg",
                            "jpeg",
                            "gif",
                        ]
                    )
                ],
                verbose_name="Archivo",
            ),
        ),
        migrations.AlterField(
            model_name="versiondocumento",
            name="archivo",
            field=models.FileField(
                upload_to="documentacion/versiones/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "pdf",
                            "doc",
                            "docx",
                            "xls",
                            "xlsx",
                            "csv",
                            "txt",
                            "png",
                            "jpg",
                            "jpeg",
                            "gif",
                        ]
                    )
                ],
                verbose_name="Archivo de la versión",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="categoriadocumento",
            unique_together={("organization", "nombre")},
        ),
    ]
